#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\HZShow\list.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/HZShow/list.cshtml")]
    public partial class _Views_HZShow_list_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_HZShow_list_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\HZShow\list.cshtml"
  
    Layout = "~/Areas/Core/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(function () {
            JQ.datagrid.datagrid({
                JQButtonTypes: ['export','moreSearch'],//需要显示的按钮
                JQPrimaryID: 'Id',//主键的字段
                JQID: 'HZShowGrid',//数据表格ID
                JQDialogTitle: '信息',//弹出窗体标题
                JQWidth: '768',//弹出窗体宽
                JQHeight: '100%',//弹出窗体高
                JQLoadingType: 'datagrid',//数据表格类型 [datagrid,treegrid]
                url: '");

            
            #line 16 "..\..\Views\HZShow\list.cshtml"
                 Write(Url.Action("json","HZShow",new { @area="Bussiness"}));

            
            #line default
            #line hidden
WriteLiteral("\',//请求的地址\r\n                checkOnSelect: true,//是否包含check\r\n                toolb" +
"ar: \'#HZShowGridPanel\',//工具栏的容器ID\r\n                JQExcludeCol: [1,8],//导出execl" +
"排除的列\r\n                columns: [[\r\n                    { field: \'ck\', align: \'ce" +
"nter\', checkbox: true, JQIsExclude: true },\r\n                    { title: \'项目编号\'" +
", field: \'ProjNumber\', width: \'10%\', align: \'center\', sortable: true },\r\n       " +
"             { title: \'项目名称\', field: \'ProjName\', width: \'20%\', align: \'center\', " +
"sortable: true },\r\n                    { title: \'阶段\', field: \'PhaseNames\', width" +
": \'10%\', align: \'center\', sortable: true },\r\n                    { title: \'合同状态\'" +
", field: \'ConStateName\', width: \'5%\', align: \'center\', sortable: true },\r\n      " +
"              { title: \'是否收清\', field: \'IsFinish\', width: \'5%\', align: \'center\', " +
"sortable: true },\r\n                    { title: \'所属公司\', field: \'CompanyID\', widt" +
"h: \'5%\', align: \'center\', sortable: true }\r\n                ]]\r\n            });\r" +
"\n\r\n            $(\"#JQSearch\").textbox({\r\n                buttonText: \'筛选\',\r\n    " +
"            buttonIcon: \'fa fa-search\',\r\n                height: 25,\r\n          " +
"      prompt: \'项目编号、项目名称\',\r\n                queryOptions: { \'Key\': \'\', \'Contract" +
"\': \'like\' },\r\n                onClickButton: function () {\r\n                    " +
"JQ.datagrid.searchGrid(\r\n                        {\r\n                            " +
"dgID: \'HZShowGrid\',\r\n                            loadingType: \'datagrid\',\r\n     " +
"                       queryParams: null\r\n                        });\r\n         " +
"       }\r\n            });\r\n        });\r\n    </script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("Body_Content", () => {

WriteLiteral("\r\n    <table");

WriteLiteral(" id=\"HZShowGrid\"");

WriteLiteral("></table>\r\n    <div");

WriteLiteral(" id=\"HZShowGridPanel\"");

WriteLiteral(" JQPanel=\"searchPanel\"");

WriteLiteral(" style=\"padding:5px;height:auto;\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" JQPanel=\"toolbarPanel\"");

WriteLiteral(">\r\n            \r\n        </span>\r\n\r\n        <input");

WriteLiteral(" id=\"JQSearch\"");

WriteLiteral(" style=\"width:250px;\"");

WriteLiteral(" JQWhereOptions=\"{ Key:\'ProjNumber,ProjName\', Contract:\'like\'}\"");

WriteLiteral(" />\r\n        <div");

WriteLiteral(" class=\"moreSearchPanel\"");

WriteLiteral(">\r\n            ");

WriteLiteral("\r\n            合同状态：");

            
            #line 60 "..\..\Views\HZShow\list.cshtml"
            Write(BaseData.getBases(new Params()
            {
                isMult = false,
                controlName = "ConStatus",
                isRequired = false,
                engName = "ConStatus",
                queryOptions = "{'Key':'ConStatus','Contract':'in','filedType':'Int'}",
                width = "120px",
            }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
