#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\HREmployee\list.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/HREmployee/list.cshtml")]
    public partial class _Views_HREmployee_list_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_HREmployee_list_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\HREmployee\list.cshtml"
  
    Layout = "~/Areas/Core/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\t var requestUrl = \'");

            
            #line 7 "..\..\Views\HREmployee\list.cshtml"
               Write(Url.Action("json", "HREmployee",new { @area="Hr"}));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            addUrl = \'");

            
            #line 8 "..\..\Views\HREmployee\list.cshtml"
                 Write(Url.Action("add","HREmployee",new {@area="Hr" }));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            editUrl = \'");

            
            #line 9 "..\..\Views\HREmployee\list.cshtml"
                  Write(Url.Action("edit", "HREmployee",new {@area="Hr" }));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            delUrl = \'");

            
            #line 10 "..\..\Views\HREmployee\list.cshtml"
                 Write(Url.Action("del", "HREmployee", new { @area = "Hr" }));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        $(function () {\r\n            debugger;\r\n            var btnPer=");

            
            #line 13 "..\..\Views\HREmployee\list.cshtml"
                  Write(Html.Raw(ViewBag.strPer));

            
            #line default
            #line hidden
WriteLiteral(";\r\n            if($.inArray(\"btnChoice\",btnPer)==-1){\r\n                $(\"#btnCho" +
"ice\").hide();\r\n            }\r\n\r\n            JQ.datagrid.datagrid({\r\n            " +
"    JQButtonTypes: ");

            
            #line 19 "..\..\Views\HREmployee\list.cshtml"
                          Write(Html.Raw(ViewBag.strPer));

            
            #line default
            #line hidden
WriteLiteral(",//需要显示的按钮\r\n                JQAddUrl: addUrl, //添加的路径\r\n                JQEditUrl:" +
" editUrl,//编辑的路径\r\n                JQDelUrl: delUrl, //删除的路径\r\n                JQP" +
"rimaryID: \'Id\',//主键的字段\r\n                JQID: \'HREmployeeGrid\',//数据表格ID\r\n       " +
"         JQDialogTitle: \'信息\',//弹出窗体标题\r\n                JQWidth: \'768\',//弹出窗体宽\r\n " +
"               JQHeight: \'100%\',//弹出窗体高\r\n                JQLoadingType: \'datagri" +
"d\',//数据表格类型 [datagrid,treegrid]\r\n                JQFields: [\"Id\"],//追加的字段名\r\n\t\t\t\t" +
"JQSearch: {\r\n                    id: \'JQSearch\',\r\n                    prompt: \'筛" +
"选字段\',\r\n                    loadingType: \'datagrid\',//默认值为datagrid可以不传\r\n         " +
"       },\r\n                url: requestUrl,//请求的地址\r\n                checkOnSelec" +
"t: true,//是否包含check\r\n\t\t\t\tfitColumns: false,\r\n                nowrap: false,\r\n   " +
"             toolbar: \'#HREmployeePanel\',//工具栏的容器ID\r\n                JQExcludeCo" +
"l:[1,11],\r\n                columns: [[\r\n                    { field: \'ck\', align" +
": \'center\', checkbox: true, JQIsExclude: true },\r\n                    { title: \'" +
"部门\', field: \'DepName\', width: 100, align: \'center\', sortable: true },\r\n         " +
"           { title: \'姓名\', field: \'EmpName\', width: 100, align: \'center\', sortabl" +
"e: true },\r\n                    { title: \'入职日期\', field: \'EmpJoinDate\', width: 10" +
"0, align: \'center\', sortable: true, formatter: JQ.tools.DateTimeFormatterByT },\r" +
"\n                    { title: \'性别\', field: \'EmpSexName\', width: 100, align: \'cen" +
"ter\', sortable: true },\r\n                    { title: \'手机\', field: \'EmpPhoneNumb" +
"er\', width: 100, align: \'center\', sortable: true },\r\n                    { title" +
": \'最高学历\', field: \'LastEducationName\', width: 100, align: \'center\', sortable: tru" +
"e },\r\n                    { title: \'个人资质\', field: \'ZZCount\', width: 100, align: " +
"\'center\', sortable: true,formatter:function(value,row,index){\r\n                 " +
"       return \"<a href=\\\"javascript:void(0)\\\" onclick=\\\"ZZDetail(\'\" + row.Id + \"" +
"\');\\\">\"+row.ZZCount+\"</a>\"\r\n                    }},\r\n                    { title" +
": \'个人获奖信息\', field: \'HJCount\', width: 100, align: \'center\', sortable: true,format" +
"ter:function(value,row,index){\r\n                        return \"<a href=\\\"javasc" +
"ript:void(0)\\\" onclick=\\\"HJDetail(\'\" + row.Id + \"\');\\\">\"+row.HJCount+\"</a>\"\r\n   " +
"                 }},\r\n                    { title: \'年休天数\', field: \'VacationDays1" +
"\', width: 100, align: \'center\', sortable: true },\r\n                    {\r\n      " +
"                  field: \'opt\', title: \'操作\', width: 100, align: \'center\', JQIsEx" +
"clude: true,\r\n                        formatter: function (value, row, index) {\r" +
"\n                            var html=\"\";\r\n                            if($.inAr" +
"ray(\"edit\", btnPer)!=-1){\r\n                                html+=\"<a href=\\\"java" +
"script:void(0)\\\" onclick=\\\"openDetailDialog(\'\" + row.Id + \"\');\\\">修改</a>&nbsp;&nb" +
"sp;\";\r\n                            }\r\n                            if($.inArray(\"" +
"del\", btnPer)!=-1){\r\n                                html+=\"<a href=\\\"javascript" +
":void(0)\\\" onclick=\\\"delRow(\'\" + row.Id + \"\');\\\" style=\'margin-left:2px;\'>删除</a>" +
"\";\r\n                            }\r\n                            return html;\r\n   " +
"                     }\r\n                    }\r\n                ]],\r\n            " +
"    onLoadSuccess: function (data) {\r\n                }\r\n            });\r\n      " +
"      $(\"#JQSearch\").textbox({\r\n                buttonText: \'筛选\',\r\n             " +
"   buttonIcon: \'fa fa-search\',\r\n                height: 25,\r\n                pro" +
"mpt: \'姓名\',\r\n                queryOptions: { \'Key\': \'EmpName\', \'Contract\': \'like\'" +
" },\r\n                onClickButton: function () {\r\n                    JQ.datagr" +
"id.searchGrid(\r\n                        {\r\n                            dgID: \'HR" +
"EmployeeGrid\',\r\n                            loadingType: \'datagrid\',\r\n          " +
"                  queryParams: { endDate: $(\"#endDate\").datebox(\"getValue\") }\r\n " +
"                       });\r\n                }\r\n            });\r\n        });\r\n\r\n " +
"       function ZZDetail(empId){\r\n            JQ.dialog.dialog({\r\n              " +
"  title: \"个人资质明细\",\r\n                url: \'");

            
            #line 93 "..\..\Views\HREmployee\list.cshtml"
                 Write(Url.Action("EmpAptiudeDetail", "HRAptitudeManager", new { @area = "Hr" }));

            
            #line default
            #line hidden
WriteLiteral(@"?EmpId='+empId+'',
                width: '1024',
                height: '100%',
                JQID: 'HREmployeeGrid',
                JQLoadingType: 'datagrid',
                iconCls: 'fa fa-plus'
            });
        }

        function HJDetail(empId){
            JQ.dialog.dialog({
                title: ""个人获奖明细"",
                url: '");

            
            #line 105 "..\..\Views\HREmployee\list.cshtml"
                 Write(Url.Action("HREmpWinDetail", "HREmpWinManager", new { @area = "Hr" }));

            
            #line default
            #line hidden
WriteLiteral(@"?EmpId='+empId+'',
                width: '1024',
                height: '100%',
                JQID: 'HREmployeeGrid',
                JQLoadingType: 'datagrid',
                iconCls: 'fa fa-plus'
            });
        }

        function openDetailDialog(rowID) {
            jQuery(""#HREmployeeGrid"").datagrid('reload');
            JQ.dialog.dialog({
                title: ""修改"",
                url: '");

            
            #line 118 "..\..\Views\HREmployee\list.cshtml"
                 Write(Url.Action("edit"));

            
            #line default
            #line hidden
WriteLiteral(@"' + '?Id=' + rowID,
                width: '1024',
                height: '100%',
                JQID: 'HREmployeeGrid',
                JQLoadingType: 'datagrid',
                iconCls: 'fa fa-plus'
            });
        }
        function delRow(rowID)
        {
            window.top.JQ.dialog.confirm(""确定要删除吗？"",function(){
                jQuery.post(""");

            
            #line 129 "..\..\Views\HREmployee\list.cshtml"
                        Write(Url.Action("del", "HREmployee", new {area="Hr"}));

            
            #line default
            #line hidden
WriteLiteral("\",\"id=\"+rowID,function(data){\r\n                    jQuery(\"#HREmployeeGrid\").data" +
"grid(\'reload\');\r\n                },\"json\");\r\n            });\r\n        }\r\n\r\n     " +
"   function SyncEmployee(){\r\n            jQuery.post(\"");

            
            #line 136 "..\..\Views\HREmployee\list.cshtml"
                    Write(Url.Action("SyncEmployee", "HREmployee", new {area="Hr"}));

            
            #line default
            #line hidden
WriteLiteral("\",\'\',function(data){\r\n                jQuery(\"#HREmployeeGrid\").datagrid(\'reload\'" +
");\r\n            },\"json\");\r\n        }\r\n    </script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("Body_Content", () => {

WriteLiteral("\r\n    <table");

WriteLiteral(" id=\"HREmployeeGrid\"");

WriteLiteral("></table>\r\n    <div");

WriteLiteral(" id=\"HREmployeePanel\"");

WriteLiteral(" JQPanel=\"searchPanel\"");

WriteLiteral(" style=\"padding:5px;height:auto;\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" JQPanel=\"toolbarPanel\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" name=\"btnChoice\"");

WriteLiteral(" id=\"btnChoice\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'fa fa-minus-circle\'\"");

WriteLiteral(" onclick=\"SyncEmployee()\"");

WriteLiteral(">同步人员</a>\r\n        </span>\r\n\r\n        <input");

WriteLiteral(" id=\"JQSearch\"");

WriteLiteral(" style=\"width:250px;\"");

WriteLiteral("  JQWhereOptions=\"{ \'Key\': \'EmpName\', \'Contract\': \'like\' }\"");

WriteLiteral("/>\r\n        <div");

WriteLiteral(" class=\"moreSearchPanel\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 152 "..\..\Views\HREmployee\list.cshtml"
       Write(BaseData.getBases(new Params() { isMult = false, engName = "department", isAll = "1", allVal = "0", allText = "全部", queryOptions = "{ Key:'DepID', Contract:'in',filedType:'Int'}" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 153 "..\..\Views\HREmployee\list.cshtml"
       Write(BaseData.getBases(new Params() { isMult = false, engName = "EmpStatus", isAll="1", allVal="0", allText="全部", queryOptions = "{ Key:'EmpStatusID', Contract:'in',filedType:'Int'}" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <input");

WriteLiteral(" id=\"startTime\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" style=\"width:110px\"");

WriteLiteral(" data-options=\"prompt: \'入职日期\'\"");

WriteLiteral(" JQWhereOptions=\"{ Key:\'CreationTime\', Contract:\'>=\',filedType:\'Date\' }\"");

WriteLiteral(">\r\n            至\r\n            <input");

WriteLiteral(" id=\"endDate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" style=\"width:110px\"");

WriteLiteral(" data-options=\"prompt: \'入职日期\'\"");

WriteLiteral(">&nbsp;\r\n        </div>\r\n    </div>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
