#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/ExportPreview.cshtml")]
    public partial class _Views_Shared_ExportPreview_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared_ExportPreview_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <title>导出预览</title>\r\n");

WriteLiteral("    ");

            
            #line 6 "..\..\Views\Shared\ExportPreview.cshtml"
Write(RenderPage("_Header.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 177), Tuple.Create("\"", 245)
            
            #line 7 "..\..\Views\Shared\ExportPreview.cshtml"
, Tuple.Create(Tuple.Create("", 184), Tuple.Create<System.Object, System.Int32>(Url.Content("~/lib/rwpUI/skins/lightblue/css/rwpLayout.css")
            
            #line default
            #line hidden
, 184), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
        .printbutton
        {
            padding: 10px 0 10px 0;
        }
        .printbutton .inputWidth
        {
            float: left;
            padding: 0 5px 0 3px;
            height: 22px;
        }
        /*.printTable
        {            
            border-left: #000 1px solid;
            border-top: #000 1px solid;
        }*/
        /*.printTable td
        {
            border-bottom: #000 1px solid;
            border-right: #000 1px solid;
            text-align: center;
            padding-top: 5px;
            padding-bottom:5px;
            line-height:22px;

        }*/
        /*.printTable .tableHead td
        {
            background: #fff;
            font-weight: 700;            
        }*/
    </style>
    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1107), Tuple.Create("\"", 1161)
            
            #line 40 "..\..\Views\Shared\ExportPreview.cshtml"
, Tuple.Create(Tuple.Create("", 1113), Tuple.Create<System.Object, System.Int32>(Url.Content("~/lib/rwpUI/js/ui/rwpDatagrid.js")
            
            #line default
            #line hidden
, 1113), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" ></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1209), Tuple.Create("\"", 1270)
            
            #line 41 "..\..\Views\Shared\ExportPreview.cshtml"
, Tuple.Create(Tuple.Create("", 1215), Tuple.Create<System.Object, System.Int32>(Url.Content("~/lib/rwpUI/js/ui/rwpDatagrid.plugin.js")
            
            #line default
            #line hidden
, 1215), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var gridManager;\r\n        var gridData = { itemsPerPage: 100 };\r\n     " +
"   var parentGridManager, parentGridOptions, parentUrl, parentGridParams = [];\r\n" +
"        function initGridData() {\r\n            gridData.totalPages = 1;\r\n       " +
"     gridData.currentPage = 1;\r\n            gridData.items = [];\r\n        }\r\n\r\n " +
"       //获取所有分页数据\r\n        function getAllPageData() {\r\n            initGridData" +
"();    //每次请求时 初始化变量\r\n            for (; gridData.currentPage <= gridData.totalP" +
"ages; gridData.currentPage++) {\r\n                getPageData();\r\n            }\r\n" +
"            return gridData;\r\n        }\r\n\r\n        //获取某页数据\r\n        function ge" +
"tPageData() {\r\n            var param = [];\r\n            if (parentGridParams && " +
"parentGridParams.length > 0) {\r\n                $(parentGridParams).each(functio" +
"n () {\r\n                    param.push({ name: this.name, value: this.value });\r" +
"\n                })\r\n            }\r\n            param.push({ name: \'page\', value" +
": gridData.currentPage });\r\n            param.push({ name: \'pagesize\', value: gr" +
"idData.itemsPerPage });\r\n\r\n            $.rwpUI.post(parentUrl, param, null,\r\n   " +
"             function (data) {\r\n                    addPageData(data);\r\n        " +
"        }, null, null, false, true);\r\n        }\r\n\r\n        //添加某页数据\r\n        fun" +
"ction addPageData(pageData) {\r\n            if (pageData) {\r\n                if (" +
"pageData[\'totalPages\'])  //分页时才更新总页数\r\n                    gridData.totalPages = " +
"pageData[\'totalPages\'];\r\n                $(pageData[\'items\']).each(function (i, " +
"item) {\r\n                    gridData.items.push(item);\r\n                });\r\n  " +
"          }\r\n        }\r\n\r\n        //设置表格数据\r\n        function setGridData() {\r\n  " +
"          var waiting = $.rwpUI.waitting(\'数据量大,正在加载中,请稍候...\');\r\n            setT" +
"imeout(function () {\r\n                gridManager.refreshData({ data: getAllPage" +
"Data() });\r\n                setPrintTableHtml();   //同步打印表格的html\r\n              " +
"  waiting.close();\r\n            }, 0);\r\n        }\r\n\r\n        //设置打印表格的html\r\n    " +
"    function setPrintTableHtml() {\r\n            var rwpUIHeaderTable = $(\'.expor" +
"tContentHidden .rwpGridTableHead table\');\r\n            var rwpUIBodyTable = $(\'." +
"exportContentHidden .rwpGridTableBody > table\');\r\n            var printTable = $" +
"(\'.printContent .printTable\');\r\n            $(\'tr:not(:first)\', printTable).remo" +
"ve();  //删除所有非首行元素(标题行不会重新加载)            \r\n            $(\'tr\', rwpUIHeaderTable)" +
".each(function (i, item) {\r\n                printTable.append(item);   //插入表头\r\n " +
"           });\r\n            $(\'tr\', rwpUIBodyTable).each(function (i, item) {\r\n " +
"               printTable.append(item);   //插入body\r\n            });\r\n\r\n         " +
"   $(\'*\', printTable).removeClass();   //移除所有元素的类名            \r\n            $(\'t" +
"d >div\', printTable).css({ height: \'auto\', width: \'auto\' });   //移除td中div的高度和宽度 " +
"           \r\n            $(\'tr\', printTable).unbind(\'mouseover\').unbind(\'mouseou" +
"t\');  //解除mouseover绑定\r\n\r\n            $(\'th, td\', printTable).css({ \'text-align\':" +
" \'center\', \'paddingTop\': \'5px\', \'paddingBottom\': \'5px\', \'line-height\': \'22px\', \'" +
"border-color\': \'#000\' });\r\n            $(\'tr:first th\', printTable).css({ \'backg" +
"round\': \'#fff\', \'font-weight\': \'700\' });\r\n        }\r\n\r\n        function htmlEnco" +
"de(value) {\r\n            //create a in-memory div, set it\'s inner text(which jQu" +
"ery automatically encodes)\r\n            //then grab the encoded contents back ou" +
"t.  The div never exists on the page.\r\n            return $(\'<div/>\').text(value" +
").html();\r\n        }\r\n\r\n        function exportExcel() {\r\n            var tableH" +
"tml = htmlEncode($(\'.printTable\')[0].outerHTML);//做html编码\r\n            $(\'#fileH" +
"tmlStr\').val(tableHtml);\r\n            $(\'#exportform\').submit(); //表单提交\r\n       " +
" }\r\n\r\n        function doSave() {\r\n            //alert(document.getElementById(\'" +
"theexecel\').innerHTML);\r\n            var winname = window.open(\'\', \'excel1\', \'to" +
"p=0\');\r\n            winname.document.open(\'text/html\', \'replace\');\r\n            " +
"execelcontent = document.getElementById(\'Report_DIV\').innerHTML\r\n            win" +
"name.document.writeln(execelcontent);\r\n            winname.document.execCommand(" +
"\'saveas\', \'\', \'导出的excel.xls\');\r\n            winname.close();\r\n        }\r\n\r\n     " +
"   $(function () {\r\n            parentGridManager = window.opener.rwpListLayout." +
"getCurrentGrid();\r\n            parentGridOptions = parentGridManager.getOptions(" +
");\r\n            parentUrl = parentGridOptions.url;  //重新获取url\r\n            paren" +
"tGridParams = parentGridOptions.params;   //获取表格查询参数            \r\n            va" +
"r parentGridExportOpts = window.opener.rwpTemp.exportgridopts;  //父窗体的导出表格参数    " +
"        \r\n            parentGridExportOpts.url = null;  //取消url, 用data静态数据\r\n    " +
"        parentGridExportOpts.toolbar = null;  //取消工具栏\r\n            parentGridExp" +
"ortOpts.checkbox = false;  //取消复选框\r\n            parentGridExportOpts.onContextme" +
"nu = null;  //取消表格的右键菜单\r\n            parentGridExportOpts.onAfterShowData = null" +
";  //取消表格的数据加载完成事件\r\n            var columnRemove = [];\r\n            for (var i =" +
" 0; i < parentGridExportOpts.columns.length; i++) {\r\n                if (!parent" +
"GridExportOpts.columns[i].name || parentGridExportOpts.columns[i].isHide === tru" +
"e)\r\n                    columnRemove.push(i);   //获取表格列中 操作栏的索引 及主键隐藏列的索引\r\n     " +
"       }\r\n            for (var i = 0; i < columnRemove.length; i++)\r\n           " +
"     parentGridExportOpts.columns.splice(columnRemove[i] - i, 1);  //删除指定索引处的元素 " +
"           \r\n            parentGridExportOpts.usePager = false;   //不使用分页       " +
"     \r\n            $(\'.exportContentHidden:first\').rwpUIDatagrid(parentGridExpor" +
"tOpts);\r\n            gridManager = $(\'.exportContentHidden:first\').data(\'rwpUIDa" +
"tagrid\');\r\n            setGridData();  //开始加载表格数据\r\n            $(\'#export\').clic" +
"k(function (e) {\r\n                e.preventDefault();  //IE6阻止默认事件\r\n            " +
"    //exportExcel();\r\n                doSave();\r\n            });\r\n            $(" +
"\'#close\').click(function () {\r\n                window.close();\r\n            });\r" +
"\n            $(\'#refresh\').click(function () {\r\n                setGridData();  " +
" //重新加载表格数据\r\n            });\r\n        });\r\n    </script>\r\n</head>\r\n<body>\r\n    <" +
"div");

WriteLiteral(" class=\"printbutton\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"clear\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"inputWidth\"");

WriteLiteral("><a");

WriteLiteral(" id=\"export\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"rwpButton\"");

WriteLiteral(">导出</a></li>\r\n            <li");

WriteLiteral(" class=\"inputWidth\"");

WriteLiteral("><a");

WriteLiteral(" id=\"refresh\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"rwpButton\"");

WriteLiteral(">刷新</a></li>\r\n            <li");

WriteLiteral(" class=\"inputWidth\"");

WriteLiteral("><a");

WriteLiteral(" id=\"close\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral(" class=\"rwpButton\"");

WriteLiteral(">关闭</a></li>\r\n        </ul>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"tablepanel\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"Report_DIV\"");

WriteLiteral(" class =\"printContent\">\r\n            <table");

WriteLiteral(" class=\"printTable\"");

WriteLiteral(" border=\"1\"");

WriteLiteral(" style=\"border-color:#000;\"");

WriteLiteral("></table>\r\n        </div>        \r\n        <div class =\"exportContentHidden\" styl" +
"e=\"display:none;\"></div>");

WriteLiteral("\r\n    </div>\r\n    <form");

WriteLiteral(" id=\"exportform\"");

WriteLiteral("  method=\"post\"");

WriteAttribute("action", Tuple.Create(" action=\"", 8169), Tuple.Create("\"", 8236)
            
            #line 192 "..\..\Views\Shared\ExportPreview.cshtml"
, Tuple.Create(Tuple.Create("", 8178), Tuple.Create<System.Object, System.Int32>(Url.Action("exportexcel", "main", new { @area = "Core" })
            
            #line default
            #line hidden
, 8178), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 193 "..\..\Views\Shared\ExportPreview.cshtml"
   Write(Html.Hidden("fileName", (string)ViewBag.fileName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 194 "..\..\Views\Shared\ExportPreview.cshtml"
   Write(Html.Hidden("fileHtmlStr"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
