#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DesTask/ProjectProgressListPW.cshtml")]
    public partial class _Views_DesTask_ProjectProgressListPW_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DesTask_ProjectProgressListPW_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
  
    Layout = "~/Areas/Core/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n            JQ.datagrid.datagrid({\r\n                p" +
"agination: true,\r\n                JQButtonTypes: [\'moreSearch\'],//需要显示的按钮\r\n     " +
"           JQAddUrl: \'");

            
            #line 11 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
                      Write(Url.Action("add"));

            
            #line default
            #line hidden
WriteLiteral("\',//添加的路径\r\n                JQEditUrl: \'");

            
            #line 12 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
                       Write(Url.Action("edit"));

            
            #line default
            #line hidden
WriteLiteral("\',//编辑的路径\r\n                JQDelUrl: \'");

            
            #line 13 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
                      Write(Url.Action("del", "ProjectPW", new { @area="Project"}));

            
            #line default
            #line hidden
WriteLiteral(@"?FormMenu=ProjectProgressListPW',//删除的路径
                JQPrimaryID: 'Id',//主键的字段
                idField: 'Id',
                JQID: 'ProjectGrid',//数据表格ID
                JQDialogTitle: '信息',//弹出窗体标题
                JQWidth: '1024',//弹出窗体宽
                JQHeight: '100%',//弹出窗体高
                JQLoadingType: 'datagrid',//数据表格类型 [datagrid,treegrid]
                url: '");

            
            #line 21 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
                 Write(Url.Action("jsonNew", "ProjectPW", new { @area="Project"}));

            
            #line default
            #line hidden
WriteLiteral("?FormMenu=ProjectProgressListPW\',//请求的地址\r\n                checkOnSelect: true,//是" +
"否包含check\r\n                singleSelect: false,\r\n                toolbar: \'#Proje" +
"ctPanel\',//工具栏的容器ID\r\n                queryParams: { IsShowMain: 1, FormMenu: \"Pr" +
"ojProgressPW\" },\r\n                nowrap: false,\r\n                columns: [[\r\n " +
"                 { title: \'项目编号\', field: \'ProjNumber\', width: \"8%\", halign: \'cen" +
"ter\', align: \'left\' },\r\n\t              { title: \'项目名称\', field: \'ProjName\', width" +
": \"16%\", halign: \'center\', align: \'left\', sortable: true },\r\n                  {" +
"\r\n                      title: \'项目地区\', field: \'ProjAreaID\', width: \"4%\", halign:" +
" \'center\', sortable: true, align: \'center\', formatter: function (value, row, ind" +
"ex) {\r\n                          row.ProjAreaID = row.ProjAreaName;\r\n           " +
"               return row.ProjAreaName;\r\n                      }\r\n              " +
"    },\r\n                  { title: \'客户名称\', field: \'CustName\', width: \"10%\", hali" +
"gn: \'center\', align: \'left\' },\r\n                  { title: \'主办部门\', field: \'ProjD" +
"eptName\', width: \"5%\", halign: \'center\', align: \'center\' },\r\n                  {" +
" title: \'协办部门\', field: \'ProjJoinDeptName\', width: \"5%\", halign: \'center\', align:" +
" \'center\' },\r\n                  { title: \'下达时间\', field: \'DateCreate\', width: \"5%" +
"\", halign: \'center\', align: \'center\', formatter: JQ.tools.DateTimeFormatterByT }" +
",\r\n                  {\r\n                      title: \'建设性质\', field: \'ProjPropert" +
"yID\', width: \"5%\", halign: \'center\', align: \'center\', sortable: true, formatter:" +
" function (value, row, index) {\r\n                          row.ProjPropertyID = " +
"row.ProjPropertyName;\r\n                          return row.ProjPropertyName;\r\n " +
"                     }\r\n                  },\r\n                  {\r\n             " +
"         title: \'任务来源\', field: \'ProjTaskSource\', width: \"5%\", halign: \'center\', " +
"align: \'center\', sortable: true, formatter: function (value, row, index) {\r\n    " +
"                      row.ProjTaskSource = row.ProjTaskSourceName;\r\n            " +
"              return row.ProjTaskSourceName;\r\n                      }\r\n         " +
"         },\r\n                  {\r\n                      title: \'任务依据\', field: \'C" +
"olAttType1\', width: \"5%\", halign: \'center\', align: \'center\', sortable: true, for" +
"matter: function (value, row, index) {\r\n                          row.ColAttType" +
"1 = row.ProjTaskTypeName;\r\n                          return row.ProjTaskTypeName" +
";\r\n                      }\r\n                  },\r\n                  {\r\n         " +
"             title: \'任务类型\', field: \'ColAttType2\', width: \"5%\", halign: \'center\'," +
" align: \'center\', sortable: true, formatter: function (value, row, index) {\r\n   " +
"                       row.ColAttType2 = row.ProjectTaskName;\r\n                 " +
"         return row.ProjectTaskName;\r\n                      }\r\n                 " +
" },\r\n                  {\r\n                      title: \'项目负责人\', field: \'ProjEmpI" +
"d\', width: \"4%\", halign: \'center\', align: \'center\', sortable: true, formatter: f" +
"unction (value, row, index) {\r\n                          row.ProjEmpId = row.Pro" +
"jEmpName;\r\n                          return row.ProjEmpName;\r\n                  " +
"    }\r\n                  },\r\n                  {\r\n                      title: \'" +
"项目阶段\', field: \'PhaseNames\', width: \"5%\", halign: \'center\', align: \'center\', form" +
"atter: function (value) {\r\n                          if (value != \"\") {\r\n       " +
"                       return value.substring(0, value.length - 1);\r\n           " +
"               }\r\n                      }\r\n                  },\r\n\t\t          {\r\n" +
"\t\t              title: \'电压级别\', field: \'ProjVoltID\', width: \"5%\", halign: \'center" +
"\', align: \'center\', sortable: true, formatter: function (value, row, index) {\r\n\t" +
"\t                  row.ProjVoltID = row.ProjVoltName;\r\n\t\t                  retur" +
"n row.ProjVoltName;\r\n\t\t              }\r\n\t\t          },\r\n                  {\r\n   " +
"                   title: \"操作\", field: \"Operate\", width: \"5%\", halign: \"center\"," +
" align: \"center\", formatter: function (value, rowData) {\r\n                      " +
"    return \"<a href=\\\"javascript:void(0)\\\" onclick=\\\"openViewProgressDialog(\'\" +" +
" rowData.Id + \"\',\'\" + encodeURIComponent(rowData.ProjName) + \"\');\\\">查看</a>\"\r\n   " +
"                   }\r\n                  }\r\n                ]]\r\n            });\r\n" +
"            $(\"#JQSearch\").textbox({\r\n                buttonText: \'筛选\',\r\n       " +
"         buttonIcon: \'fa fa-search\',\r\n                height: 25,\r\n             " +
"   prompt: \'项目编号,项目名称\',\r\n                //queryOptions: { \'Key\': \'ProjNumber\', " +
"\'Contract\': \'like\' },\r\n                onClickButton: function () {\r\n           " +
"         JQ.datagrid.searchGrid(\r\n                        {\r\n                   " +
"         dgID: \'ProjectGrid\',\r\n                            loadingType: \'datagri" +
"d\',\r\n                            queryParams: {\r\n                               " +
" IsShowMain: 1,\r\n                                FormMenu: \"ProjProgressPW\"\r\n   " +
"                         }\r\n                        });\r\n                }\r\n    " +
"        });\r\n        });\r\n\r\n        window.refreshGrid = function () {\r\n        " +
"    $(\"#JQSearch\").textbox(\"button\").click();\r\n        }\r\n\r\n\r\n        function o" +
"penViewProgressDialog(projectID, projectName) {\r\n            JQ.dialog.dialogIfr" +
"ame({\r\n                title: decodeURIComponent(projectName) + \" 进度\",\r\n        " +
"        url: \'");

            
            #line 118 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
                 Write(Url.Action("ProgressDetail", "ProjectPW",new { @area = "Project" }));

            
            #line default
            #line hidden
WriteLiteral("?projectID=\' + projectID,\r\n                width: \"1200\",\r\n                height" +
": \"800\"\r\n            });\r\n        }\r\n\r\n    </script>\r\n");

WriteLiteral("    ");

            
            #line 125 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
Write(RenderPage("~/Areas/Core/Views/Shared/_Init.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("Body_Content", () => {

WriteLiteral("\r\n    <table");

WriteLiteral(" id=\"ProjectGrid\"");

WriteLiteral("></table>\r\n    <div");

WriteLiteral(" id=\"ProjectPanel\"");

WriteLiteral(" JQPanel=\"searchPanel\"");

WriteLiteral(" style=\"padding:5px;height:auto;\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" JQPanel=\"toolbarPanel\"");

WriteLiteral(">\r\n\r\n        </span>\r\n        主办部门\r\n");

WriteLiteral("        ");

            
            #line 135 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
   Write(BaseData.getBases(new Params() { isMult = true, engName = "department", queryOptions = "{ Key:'ProjDepId', Contract:'in',filedType:'Int'}" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        下达时间\r\n        <input");

WriteLiteral(" id=\"startTime\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" validtype=\"dateISO\"");

WriteLiteral(" style=\"width:110px\"");

WriteLiteral(" data-options=\"prompt: \'下达开始时间\'\"");

WriteLiteral(" JQWhereOptions=\"{ Key:\'DateCreateS\', Contract:\'>=\',filedType:\'Date\' }\"");

WriteLiteral(">\r\n        至\r\n        <input");

WriteLiteral(" id=\"endTime\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" validtype=\"dateISO\"");

WriteLiteral(" style=\"width:110px\"");

WriteLiteral(" data-options=\"prompt: \'下达结束时间\'\"");

WriteLiteral(" JQWhereOptions=\"{ Key:\'DateCreateE\', Contract:\'<=\',filedType:\'Date\' }\"");

WriteLiteral(">&nbsp;\r\n        <input");

WriteLiteral(" id=\"JQSearch\"");

WriteLiteral(" style=\"width:250px;\"");

WriteLiteral(" JQWhereOptions=\"{ Key: \'txtLike\', \'Contract\': \'like\' }\"");

WriteLiteral(" />\r\n        <div");

WriteLiteral(" class=\"moreSearchPanel\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 142 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
       Write(BaseData.getBases(new Params() { isMult = true, engName = "ProjectArea", queryOptions = "{ Key:'ProjAreaID', Contract:'in',filedType:'Int'}" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 143 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
       Write(BaseData.getBases(new Params()
       {
           isMult = true,
           engName = "ProjProperty",
           typeName = "ProjProperty",
           typeAtt = "BaseAtt4",
           typeId = "1",
           queryOptions = "{ Key:'ProjPropertyID', Contract:'in',filedType:'Int'}"
       }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 152 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
       Write(BaseData.getBases(new Params()
       {
           isMult = true,
           engName = "ProjectVolt",
           typeName = "ProjectVolt",
           typeAtt = "BaseAtt2",
           typeId = "1",
           queryOptions = "{ Key:'ProjVoltID', Contract:'in',filedType:'Int'}"
       }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 161 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
       Write(BaseData.getBases(new Params() { isMult = true, engName = "ProjTaskSource", queryOptions = "{ Key:'ProjTaskSource', Contract:'in',filedType:'Int'}" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 162 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
       Write(BaseData.getBases(new Params() { isMult = true, engName = "TaskType", queryOptions = "{ Key:'ColAttType1', Contract:'in',filedType:'Int'}" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 163 "..\..\Views\DesTask\ProjectProgressListPW.cshtml"
       Write(BaseData.getBases(new Params()
       {
           isMult = true,
           engName = "ProjectTask",
           typeName = "ProjectTask",
           typeAtt = "BaseAtt4",
           typeId = "1",
           queryOptions = "{ Key:'ColAttType2', Contract:'in',filedType:'Int'}"
       }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n        </div>\r\n    </div>\r\n    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"IsShowFile\"");

WriteLiteral(" name=\"IsShowFile\"");

WriteLiteral(" value=\"1\"");

WriteLiteral(" />\r\n");

});

        }
    }
}
#pragma warning restore 1591
