#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DesTask/ProjectProgressInfoPlan.cshtml")]
    public partial class _Views_DesTask_ProjectProgressInfoPlan_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DesTask_ProjectProgressInfoPlan_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(@">
    #ProjectProgressInfoPlanDiv .tree-file,
    #ProjectProgressInfoPlanDiv .tree-folder {
        background-image: none;
    }
    #ProjectProgressInfoPlanDiv .fa-folder.text-info,
    #ProjectProgressInfoPlanDiv .fa-folder-open.text-info {
        color: #ffb300;
    }

    .FlowNodeClass td {
        font-size: 12px !important;
        height: 20px !important;
        border: 1px solid #D3D3D3;
    }
</style>

<div");

WriteLiteral(" id=\"ProjectProgressInfoPlanDiv\"");

WriteLiteral(" class=\"easyui-layout\"");

WriteLiteral(" data-options=\"fit:true\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" data-options=\"region:\'center\',border:false\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"easyui-layout\"");

WriteLiteral(" data-options=\"fit:true\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" data-options=\"region:\'north\',border:false\"");

WriteLiteral(" style=\"border-right-width:1px;border-bottom-width:1px;overflow:hidden\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"height:30px;padding:5px 0px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"float:left;margin-left:5px;\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" id=\"reloadPlans\"");

WriteLiteral(" data-options=\"iconCls:\'fa fa-repeat\',plain:true\"");

WriteLiteral(">刷新</a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" style=\"float:right;margin-right:5px;margin-top:7px;\"");

WriteLiteral(">\r\n                        节点状态：\r\n                        <span");

WriteLiteral(" class=\"node-example node-status-0-bg\"");

WriteLiteral(">未启动</span>\r\n                        <span");

WriteLiteral(" class=\"node-example node-status-1-bg\"");

WriteLiteral(">已安排</span>\r\n                        <span");

WriteLiteral(" class=\"node-example node-status-2-bg\"");

WriteLiteral(">进行中</span>\r\n                        <span");

WriteLiteral(" class=\"node-example node-status-3-bg\"");

WriteLiteral(">已完成</span>\r\n                        <span");

WriteLiteral(" class=\"node-example node-status-4-bg\"");

WriteLiteral(">已回退</span>\r\n                    </div>\r\n                </div>\r\n            </di" +
"v>\r\n            <div");

WriteLiteral(" data-options=\"region:\'center\',border:false\"");

WriteLiteral(" style=\"border-right-width:1px;\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" id=\"_desupload_$_1_temp\"");

WriteLiteral("></span>\r\n                <table");

WriteLiteral(" id=\"ProjectProgressInfoPlan_plans\"");

WriteLiteral("></table>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1938), Tuple.Create("\"", 1985)
            
            #line 44 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
, Tuple.Create(Tuple.Create("", 1944), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/JQ/DesFlow.js")
            
            #line default
            #line hidden
, 1944), false)
);

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n    var _enum_Design_NodeType_专业 = ");

            
            #line 48 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
                               Write((int)DataModel.NodeType.专业);

            
            #line default
            #line hidden
WriteLiteral(";\r\n    var _enum_Design_NodeType_设计 = ");

            
            #line 49 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
                               Write((int)DataModel.NodeType.设计);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n    var _enum_Design_TaskStatus_进行中 = ");

            
            #line 51 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
                                  Write((int)DBSql.Design.TaskStatus.进行中);

            
            #line default
            #line hidden
WriteLiteral(";\r\n    var _enum_Design_TaskStatus_已停止 = ");

            
            #line 52 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
                                  Write((int)DBSql.Design.TaskStatus.已停止);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n    var _enum_Design_FlowNodeStatus_未安排 = ");

            
            #line 54 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
                                      Write((int)DBSql.Design.FlowNodeStatus.未安排);

            
            #line default
            #line hidden
WriteLiteral(";\r\n    var _enum_Design_FlowNodeStatus_已安排 = ");

            
            #line 55 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
                                      Write((int)DBSql.Design.FlowNodeStatus.已安排);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n    var _enum_Design_TaskLevelType_层级父 = ");

            
            #line 57 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
                                     Write((int)DBSql.Design.TaskLevelType.层级父);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n    var _ProjectProgressInfoPlan_projId = ");

            
            #line 59 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
                                     Write(ViewBag.projId);

            
            #line default
            #line hidden
WriteLiteral(";\r\n    var _ProjectProgressInfoPlan_taskGroupId = ");

            
            #line 60 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
                                          Write(ViewBag.taskGroupId);

            
            #line default
            #line hidden
WriteLiteral(";\r\n\r\n    // 打开模态对话框\r\n    function ProjectProgressInfoPlan_showModelDialog(title, " +
"url, width, height, onclose) {\r\n        var _ProjectProgressInfoPlan_DialogdivId" +
" = JQ.dialog.dialog({\r\n            title: decodeURIComponent(title),\r\n          " +
"  url: url,\r\n            width: width,\r\n            height: height,\r\n           " +
" JQID: \"\",\r\n            JQLoadingType: \"\",\r\n            iconCls: \"fa fa-table\",\r" +
"\n            onClose: onclose\r\n        });\r\n        JQ.Flow.stopBubble();\r\n\r\n   " +
"     // 刷新列表\r\n        window.top[\"_DialogCallback_\" +_ProjectProgressInfoPlan_Di" +
"alogdivId] = function () {\r\n            $(\"#ProjectProgressInfoPlan_plans\", $(\"#" +
"ProjectProgressInfoPlanDiv\")).treegrid(\"reload\");\r\n        }\r\n    }\r\n\r\n    // 初始" +
"化附件列表\r\n    function ProjectProgressInfoPlanInit() {\r\n        //$.extend($.fn.tre" +
"egrid.defaults.view, {\r\n        //    onAfterRender: function (target) {\r\n      " +
"  //        if (target.id == \"ProjectProgressInfoPlan_plans\") {\r\n        //     " +
"       var roots = $(target).treegrid(\"getRoots\");\r\n        //            if (ro" +
"ots.length > 0) {\r\n        //                $.each(roots, function (i, e) {\r\n  " +
"      //                    if (e.TaskLevelType > 1) {\r\n        //              " +
"          $(target).treegrid(\"update\", { id: e.Id, row: { iconCls: \"fa-folder\" }" +
" });\r\n        //                    }\r\n        //                    //判断是否子节点\r\n" +
"        //                    var Chiledroots = $(target).treegrid(\"getChildren\"" +
", e.Id);\r\n        //                    if (Chiledroots.length > 1) {\r\n        /" +
"/                        $.each(Chiledroots, function (ic, ec) {\r\n        //    " +
"                        if (ec.TaskLevelType > 1) {\r\n        //                 " +
"               $(target).treegrid(\"update\", { id: ec.Id, row: { iconCls: \"fa-fol" +
"der\" } });\r\n        //                            }\r\n        //                 " +
"       })\r\n        //                    }\r\n        //                });\r\n     " +
"   //            }\r\n        //        }\r\n        //    }\r\n        //});\r\n\r\n     " +
"   $(\"#ProjectProgressInfoPlan_plans\", $(\"#ProjectProgressInfoPlanDiv\")).treegri" +
"d({\r\n            idField: \'Id\',\r\n            treeField: \'TaskName\',\r\n           " +
" border: 0,\r\n            fit: true,\r\n            lines: true,\r\n            //ani" +
"mate: true,\r\n            selectOnCheck: false,\r\n            checkOnSelect: false" +
",\r\n            singleSelect: true,\r\n            ctrlSelect: false,\r\n            " +
"url: \'");

            
            #line 119 "..\..\Views\DesTask\ProjectProgressInfoPlan.cshtml"
             Write(Url.Action("ProjectProgressInfoPlanGetListJson"));

            
            #line default
            #line hidden
WriteLiteral("?projId=\' + _ProjectProgressInfoPlan_projId + \'&taskGroupId=\' + _ProjectProgressI" +
"nfoPlan_taskGroupId,\r\n            rownumbers: false,\r\n            //frozenColumn" +
"s: [[  ]],\r\n            columns: [[\r\n                {title: \'ID\', field: \'Id\', " +
"width: 50, align: \'center\', formatter:function (value,row,index) {\r\n            " +
"        return (row.Id <= 0 || row.TaskType == 1) ? \"\" : row.Id;\r\n              " +
"  }},\r\n                { title: \'任务名称\', field: \'TaskName\', align: \'left\',halign:" +
"\'center\',formatter:function (value,row,index) {\r\n                    var TaskNam" +
"e=\"\";\r\n                    row._groupName = \"\";\r\n                    if (row.Tas" +
"kLevelType > 1) {\r\n                        if (row.Id < 0) {\r\n                  " +
"          row._groupName = ProjectProgressInfoPlan_createTaskPathText(row); //保存" +
"分组名称，用于批量下载时创建对应的分组文件夹\r\n                            TaskName=\"<strong>\"+row._gro" +
"upName+\"</strong>\";\r\n                        } else {\r\n                         " +
"   TaskName=\"<strong>\"+row.TaskName+\"</strong>\";\r\n                        }\r\n   " +
"                 }else {\r\n                        TaskName=\"<div>\"+value+\"</a>\";" +
"\r\n                        TaskName+=\"</div>\";\r\n                    }\r\n          " +
"          return TaskName;\r\n                }},\r\n                { title: \'负责人\'," +
" field: \'TaskEmpName\', width: 80, align: \'center\',halign:\'center\' },\r\n          " +
"      { title: \'人员安排\', field: \'12\', width: 400, align: \'left\',halign:\'center\',fo" +
"rmatter:function (value,row,index) {\r\n                    return \"<div class=\\\"s" +
"wipe\\\"><div empPlan rootId=\'\"+row.Id+\"\' specId=\'\"+row.TaskSpecId+\"\' class=\'appro" +
"ve-progress\' remark=\'0\'></div></div>\";\r\n                } },\r\n                { " +
"title: \'计划开始\', field: \'DatePlanStart\', width: 80, align: \'center\',halign:\'center" +
"\',formatter:JQ.tools.DateTimeFormatterByT },\r\n                { title: \'计划完成\', f" +
"ield: \'DatePlanFinish\', width: 80, align: \'center\',halign:\'center\',formatter:JQ." +
"tools.DateTimeFormatterByT },\r\n                //{ title: \'操作\', field: \'123\', wi" +
"dth: 145, align: \'left\',halign:\'center\' ,formatter:function (value,row,index) {\r" +
"\n                //    var btnHtml=\"<a rootId=\'\"+row.Id+\"\' specId=\'\"+row.TaskSpe" +
"cId+\"\' remark=\'0\' btn  onclick=\\\"SpecDel(\'\"+row.TaskSpecId+\"\',\'\"+row.Id+\"\')\\\"  c" +
"lass=\\\"easyui-linkbutton\\\">删除</a> \";\r\n                //    if (row.Id>0) {\r\n   " +
"             //        btnHtml+=\"<a rootId=\'\"+row.Id+\"\' specId=\'\"+row.TaskSpecId" +
"+\"\' remark=\'0\' btnEdit  onclick=\\\"return GetTask(\'\"+row.TaskSpecId+\"\',\'\"+row.Id+" +
"\"\')\\\"  class=\\\"easyui-linkbutton\\\">查看</a> \";\r\n                //    }\r\n         " +
"       //    return btnHtml;\r\n                //} },\r\n                { title: \'" +
"父任务\', field: \'TaskNextFlowNodeId\', width: 60, align: \'center\', formatter:functio" +
"n (value,row,index) {\r\n                    return (row.TaskNextFlowNodeId <= 0 |" +
"| row.TaskType == 1) ? \"\" : row.TaskNextFlowNodeId;\r\n                }},\r\n      " +
"          { title: \'备注\', field: \'TaskNote\', width: 150, align: \'center\'}\r\n      " +
"      ]],\r\n            onLoadSuccess:function (row,data) {\r\n                if (" +
"data.total > 0) {\r\n\r\n                    // 统一数据的分组\r\n                    Enumera" +
"ble.From(data.rows).Where(\"x => x._parentId == 0\").ForEach(function(x,index) {\r\n" +
"                        Enumerable.From(data.rows).Where(\"s => s._parentId != 0 " +
"&& s.TaskGroupId == {0}\".format(x.TaskGroupId)).ForEach(function(s){\r\n          " +
"                  s._groupName = x._groupName;\r\n                        });\r\n   " +
"                 });\r\n\r\n                    $.each(data.rows,function (i,e) {\r\n " +
"                       var jsonNode = [];\r\n                        if (e.TaskFlo" +
"wModelJson!=\"\") {\r\n                            jsonNode=JSON.parse(e.TaskFlowMod" +
"elJson).root.item;\r\n                            if (e.TaskType == 0) {\r\n        " +
"                        var $table=$(\"div[empPlan][rootId=\'\"+e.Id+\"\']\", $(\"#Proj" +
"ectProgressInfoPlanDiv\"));\r\n                                if (e.TaskFlowModelJ" +
"son!=\"\") {\r\n                                    JQ.DesFlow.show({\r\n             " +
"                           Ctl:$table,\r\n                                        " +
"FlowData:jsonNode,\r\n                                        setNode: false\r\n    " +
"                                });\r\n                                }\r\n        " +
"                    }\r\n                        }\r\n                    });\r\n     " +
"           }\r\n            }\r\n        });\r\n            \r\n\r\n        // 刷新文件列表\r\n   " +
"     $(\"#reloadPlans\", $(\"#ProjectProgressInfoPlanDiv\")).click(function () {\r\n  " +
"          //_dialogClose = false;\r\n            $(\"#ProjectProgressInfoPlan_plans" +
"\", $(\"#ProjectProgressInfoPlanDiv\")).treegrid(\"reload\");\r\n        });\r\n    }\r\n\r\n" +
"    // 获取任务路径（纯文本）\r\n    function ProjectProgressInfoPlan_createTaskPathText(row)" +
" {\r\n        var jsonItemPath1 = row.GroupPathJson;\r\n\r\n        var separator = \"<" +
"i class=\'fa fa-caret-right\' style=\'margin: 0 5px;\'></i>\"; //＞\r\n        var arrIt" +
"emPath1 = JSON.parse(jsonItemPath1);\r\n\r\n        var path1 = (Enumerable.From(arr" +
"ItemPath1).OrderBy(\"x=>x.rownum\").Select(function (x) { return x.text; }).ToArra" +
"y());\r\n        var path = [];\r\n        if (path1 != undefined && path1 != null) " +
"{\r\n            path.push(path1.join(separator));\r\n        }\r\n\r\n        return pa" +
"th.join(separator);\r\n    }\r\n\r\n    $(function () {\r\n        // 初始化附件列表\r\n        P" +
"rojectProgressInfoPlanInit();\r\n    });\r\n</script>\r\n");

        }
    }
}
#pragma warning restore 1591
