#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2016-09-06 20:09:27
#endregion
using System;
using System.Collections.Generic;
namespace DataModel.Models
{
    public class BaseAttachVer 
    {
        public BaseAttachVer()
        {
			#region DefaultValue
			AttachVerId=0;
			AttachID=0;
			AttachDir="";
			AttachSize=0;
			AttachDateUpload= new DateTime(1900,1,1);
			AttachDateChange= new DateTime(1900,1,1);
			AttachEmpID=0;
			AttachEmpName="";
			AttachVer=0;
			#endregion
			#region 默认实例化
			#endregion
        }
		///<summary>----附件版本记录----（更新附件先插BaseAttachVer，再插BaseAttach）</summary>
        public long AttachVerId  { get; set; }

		///<summary>对应文件id</summary>
        public long AttachID  { get; set; }

		///<summary>文件路径（含文件名，文件名用Guid存储）</summary>
        public string AttachDir  { get; set; }

		///<summary>文件大小</summary>
        public long AttachSize  { get; set; }

		///<summary>上传日期</summary>
        public DateTime AttachDateUpload  { get; set; }

		///<summary>修改日期</summary>
        public DateTime AttachDateChange  { get; set; }

		///<summary>上传人</summary>
        public int AttachEmpID  { get; set; }

		///<summary>上传人姓名</summary>
        public string AttachEmpName  { get; set; }

		///<summary>文件版本</summary>
        public int AttachVer  { get; set; }

		public virtual BaseAttach FK_BaseAttachVer_AttachID { get; set; }
    }
}
