#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2016-09-06 20:09:27
#endregion
using System;
using System.Collections.Generic;
namespace DataModel.Models
{
    public class DesPlanTable 
    {
        public DesPlanTable()
        {
			#region DefaultValue
			Id=0;
			ProjId=0;
			PhaseId=0;
			TaskGroupId=0;
			DesignBasis="";
			DesignScope="";
			DesignProduct="";
			OtherDescription="";
			DesignInput="";
			DesignPrinciple="";
			QualityParget="";
			QualityAssurance="";
			DangerType="";
			DangerAction="";
			EmergencyType="";
			EmergencyAction="";
			PlanStatus=0;
			LastModificationTime= new DateTime(1900,1,1);
			LastModifierEmpId=0;
			LastModifierEmpName="";
			FlowID=0;
			FlowTime= new DateTime(1900,1,1);
			AgenEmpId=0;
			AgenEmpName="";
			CreationTime= new DateTime(1900,1,1);
			CreatorEmpId=0;
			CreatorEmpName="";
			CreatorDepId=0;
			CreatorDepName="";
			#endregion
			#region 默认实例化
			#endregion
        }
		///<summary>---项目计划表---</summary>
        public int Id  { get; set; }

		///<summary>对应项目Id</summary>
        public int ProjId  { get; set; }

		///<summary>对应专业Id</summary>
        public int PhaseId  { get; set; }

		///<summary>对应任务分组</summary>
        public int TaskGroupId  { get; set; }

		///<summary>设计依据</summary>
        public string DesignBasis  { get; set; }

		///<summary>设计范围</summary>
        public string DesignScope  { get; set; }

		///<summary>设计成品</summary>
        public string DesignProduct  { get; set; }

		///<summary>其他说明</summary>
        public string OtherDescription  { get; set; }

		///<summary>设计输入</summary>
        public string DesignInput  { get; set; }

		///<summary>主要设计原则</summary>
        public string DesignPrinciple  { get; set; }

		///<summary>质量目标</summary>
        public string QualityParget  { get; set; }

		///<summary>质量保证措施</summary>
        public string QualityAssurance  { get; set; }

		///<summary></summary>
        public string DangerType  { get; set; }

		///<summary></summary>
        public string DangerAction  { get; set; }

		///<summary></summary>
        public string EmergencyType  { get; set; }

		///<summary></summary>
        public string EmergencyAction  { get; set; }

		///<summary>状态</summary>
        public int PlanStatus  { get; set; }

		///<summary>最后修改时间</summary>
        public DateTime LastModificationTime  { get; set; }

		///<summary>最后修改人ID</summary>
        public int LastModifierEmpId  { get; set; }

		///<summary>最后修改人姓名</summary>
        public string LastModifierEmpName  { get; set; }

		///<summary>流程ID</summary>
        public long FlowID  { get; set; }

		///<summary>审批结束时间</summary>
        public DateTime FlowTime  { get; set; }

		///<summary>代理人ID</summary>
        public int AgenEmpId  { get; set; }

		///<summary>代理人姓名</summary>
        public string AgenEmpName  { get; set; }

		///<summary>创建时间</summary>
        public DateTime CreationTime  { get; set; }

		///<summary>创建人ID</summary>
        public int CreatorEmpId  { get; set; }

		///<summary>创建人姓名</summary>
        public string CreatorEmpName  { get; set; }

		///<summary>创建部门</summary>
        public int CreatorDepId  { get; set; }

		///<summary>创建部门姓名</summary>
        public string CreatorDepName  { get; set; }

		    }
}
