#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2017-03-14 14:08:23
#endregion
using System;
using System.Collections.Generic;
namespace DataModel.Models
{
    public class HREquipmentLedger
    {
        public HREquipmentLedger()
        {
            #region DefaultValue
            Id = 0;
            EquipmentName = "";
            EquipmentType = "";
            PurchasingTime = new DateTime(1900, 1, 1);
            ScrapTime = new DateTime(1900, 1, 1);
            EquipmentEmpId = 0;
            EquipmentEmpName = "";
            State = 0;
            DeletionTime = new DateTime(1900, 1, 1);
            CreationTime = new DateTime(1900, 1, 1);
            CreatorEmpId = 0;
            CreatorEmpName = "";
            CreatorDepId = 0;
            CreatorDepName = "";
            LastModificationTime = new DateTime(1900, 1, 1);
            LastModifierEmpId = 0;
            LastModifierEmpName = "";
            AgenCreatorEmpId = 0;
            AgenCreatorEmpName = "";
            AgenLastModifierEmpId = 0;
            AgenLastModifierEmpName = "";
            AgenDeleterEmpId = 0;
            AgenDeleterEmpName = "";
            DeleterEmpId = 0;
            DeleterEmpName = "";
            CompanyID = 0;
            #endregion
            #region 默认实例化
            #endregion
        }
        ///<summary>设备台账表</summary>
        public int Id { get; set; }

        ///<summary>设备名称</summary>
        public string EquipmentName { get; set; }

        ///<summary>设备型号</summary>
        public string EquipmentType { get; set; }

        ///<summary>采购时间</summary>
        public DateTime PurchasingTime { get; set; }

        ///<summary>报废时间</summary>
        public DateTime ScrapTime { get; set; }

        ///<summary>设备保管人ID</summary>
        public int EquipmentEmpId { get; set; }

        ///<summary>设备保管人姓名</summary>
        public string EquipmentEmpName { get; set; }

        ///<summary>设备状态 0正常 1报废 2维修 3其它</summary>
        public int State { get; set; }

        ///<summary>删除日期</summary>
        public DateTime DeletionTime { get; set; }

        ///<summary>创建时间</summary>
        public DateTime CreationTime { get; set; }

        ///<summary>创建人ID</summary>
        public int CreatorEmpId { get; set; }

        ///<summary>创建人姓名</summary>
        public string CreatorEmpName { get; set; }

        ///<summary>创建部门</summary>
        public int CreatorDepId { get; set; }

        ///<summary>创建部门姓名</summary>
        public string CreatorDepName { get; set; }

        ///<summary>最后修改时间</summary>
        public DateTime LastModificationTime { get; set; }

        ///<summary>最后修改人ID</summary>
        public int LastModifierEmpId { get; set; }

        ///<summary>最后修改人姓名</summary>
        public string LastModifierEmpName { get; set; }

        ///<summary>代理创建人ID</summary>
        public int AgenCreatorEmpId { get; set; }

        ///<summary>代理创建人姓名</summary>
        public string AgenCreatorEmpName { get; set; }

        ///<summary>代理最后修改人ID</summary>
        public int AgenLastModifierEmpId { get; set; }

        ///<summary>代理最后修改人姓名</summary>
        public string AgenLastModifierEmpName { get; set; }

        ///<summary>代理删除人ID</summary>
        public int AgenDeleterEmpId { get; set; }

        ///<summary>代理删除人姓名</summary>
        public string AgenDeleterEmpName { get; set; }

        ///<summary>删除人员</summary>
        public int DeleterEmpId { get; set; }

        ///<summary>删除人员姓名</summary>
        public string DeleterEmpName { get; set; }

        ///<summary>所属公司</summary>
        public int CompanyID { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        public string Remark { get; set; }

    }
}
