#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2017-04-01 03:55:49
#endregion
using System;
using System.Collections.Generic;
namespace DataModel.Models
{
    public class IsoBCD 
    {
        public IsoBCD()
        {
			#region DefaultValue
			Id=0;
			Number="";
			ProjId=0;
			ProjNumber="";
			ProjName="";
            ProjPhaseId = "";
            ProjPhaseName = "";
            ProjTypeID =0;
			ProjTypeName="";
			JCNumber="";
			JCName="";
			BCS=0;
			CDS=0;
			ZL=0;
			IsJCZD=0;
			IsFHYQ=0;
			IsSQD=0;
			IsHT=0;
			IsLY=0;
			IsQSR=0;
			IsSY=0;
			IsJL=0;
			IsCD=0;
			IsFX=0;
			IsGF=0;
			IsZL=0;
            Remrak ="";
			ZJNR="";
			CompanyID=0;
			DeletionTime= new DateTime(1900,1,1);
			CreationTime= new DateTime(1900,1,1);
			CreatorEmpId=0;
			CreatorEmpName="";
			CreatorDepId=0;
			CreatorDepName="";
			LastModificationTime= new DateTime(1900,1,1);
			LastModifierEmpId=0;
			LastModifierEmpName="";
			AgenCreatorEmpId=0;
			AgenCreatorEmpName="";
			AgenLastModifierEmpId=0;
			AgenLastModifierEmpName="";
			AgenDeleterEmpId=0;
			AgenDeleterEmpName="";
			DeleterEmpId=0;
			DeleterEmpName="";
            BDJson = "";
			#endregion
			#region 默认实例化
			#endregion
        }
		///<summary>报出单</summary>
        public int Id  { get; set; }

		///<summary>编号</summary>
        public string Number  { get; set; }

		///<summary>项目ID</summary>
        public int ProjId  { get; set; }

		///<summary>项目编号</summary>
        public string ProjNumber  { get; set; }

		///<summary>项目名称</summary>
        public string ProjName  { get; set; }

        /// <summary>
        /// 阶段ID
        /// </summary>
        public string ProjPhaseId { get; set; }

        /// <summary>
        /// 阶段名称
        /// </summary>
        public string ProjPhaseName { get; set; }

        ///<summary>工程类别ID</summary>
        public int ProjTypeID  { get; set; }

		///<summary>工程类别名称</summary>
        public string ProjTypeName  { get; set; }

		///<summary>卷册编号</summary>
        public string JCNumber  { get; set; }

		///<summary>卷册名称</summary>
        public string JCName  { get; set; }

		///<summary>报出数量</summary>
        public int BCS  { get; set; }

		///<summary>存档数量</summary>
        public int CDS  { get; set; }

		///<summary>自留数量</summary>
        public int ZL  { get; set; }

		///<summary>设计依据和基础资料齐全 1是 2否</summary>
        public int IsJCZD  { get; set; }

		///<summary>文件签署齐全并符合规定要求 1是 2否</summary>
        public int IsFHYQ  { get; set; }

		///<summary>当因特殊原因非岗位本人签署时有授权单 1是 2否</summary>
        public int IsSQD  { get; set; }

		///<summary>合同已签 1是 2否</summary>
        public int IsHT  { get; set; }

		///<summary>合同已履约 1是 2否</summary>
        public int IsLY  { get; set; }

		///<summary>文件签署人员符合要求 1是 2否</summary>
        public int IsQSR  { get; set; }

		///<summary>文件封面和扉页内容正确 1是 2否</summary>
        public int IsSY  { get; set; }

		///<summary>质量记录完整  1是 2否</summary>
        public int IsJL  { get; set; }

		///<summary>文件资料已存档 1是 2否</summary>
        public int IsCD  { get; set; }

		///<summary>批准放行 1是 2否</summary>
        public int IsFX  { get; set; }
        public int IsGF  { get; set; }
        public int IsZL  { get; set; }

        ///<summary>备注</summary>
        public string Remrak  { get; set; }

		///<summary>资料JSON</summary>
        public string ZJNR  { get; set; }

		///<summary>所属公司</summary>
        public int CompanyID  { get; set; }

		///<summary>删除日期</summary>
        public DateTime DeletionTime  { get; set; }

		///<summary>创建时间</summary>
        public DateTime CreationTime  { get; set; }

		///<summary>创建人ID</summary>
        public int CreatorEmpId  { get; set; }

		///<summary>创建人姓名</summary>
        public string CreatorEmpName  { get; set; }

		///<summary>创建部门</summary>
        public int CreatorDepId  { get; set; }

		///<summary>创建部门姓名</summary>
        public string CreatorDepName  { get; set; }

		///<summary>最后修改时间</summary>
        public DateTime LastModificationTime  { get; set; }

		///<summary>最后修改人ID</summary>
        public int LastModifierEmpId  { get; set; }

		///<summary>最后修改人姓名</summary>
        public string LastModifierEmpName  { get; set; }

		///<summary>代理创建人ID</summary>
        public int AgenCreatorEmpId  { get; set; }

		///<summary>代理创建人姓名</summary>
        public string AgenCreatorEmpName  { get; set; }

		///<summary>代理最后修改人ID</summary>
        public int AgenLastModifierEmpId  { get; set; }

		///<summary>代理最后修改人姓名</summary>
        public string AgenLastModifierEmpName  { get; set; }

		///<summary>代理删除人ID</summary>
        public int AgenDeleterEmpId  { get; set; }

		///<summary>代理删除人姓名</summary>
        public string AgenDeleterEmpName  { get; set; }

		///<summary>删除人员</summary>
        public int DeleterEmpId  { get; set; }

		///<summary>删除人员姓名</summary>
        public string DeleterEmpName  { get; set; }

        /// <summary>
        /// 相关表单JSON
        /// </summary>
        public string BDJson { get; set; }
		    }
}
