#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PayBalanceSum/PayStatistics.cshtml")]
    public partial class _Views_PayBalanceSum_PayStatistics_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_PayBalanceSum_PayStatistics_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
  
    Layout = "~/Areas/Core/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n        var requestUrl = \'");

            
            #line 8 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
                     Write(Url.Action("json", "PayBalanceSum", new { @area = "Pay" }));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        $(function () {\r\n\r\n            $(\"#Dept\").combobox({\r\n               " +
" prompt: \'下拉选择部门\',\r\n                valueField: \'id\',\r\n                textField" +
": \'text\',\r\n                url: \' ");

            
            #line 15 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
                  Write(Url.Action("treejson", "basedata", new { @area = "Core" }));

            
            #line default
            #line hidden
WriteLiteral("?engName=department\',\r\n                onChange: function (newVal, oldVal) {\r\n   " +
"                 if (newVal != \"0\") {\r\n                        $(\"#leftGrid\").da" +
"tagrid(\'reload\', \'");

            
            #line 18 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
                                                      Write(Url.Action("json", "PayBalanceSum", new { @area = "Pay" }));

            
            #line default
            #line hidden
WriteLiteral("?EmpDeptID=\' + newVal);\r\n                    }\r\n\r\n                },\r\n           " +
"     onLoadSuccess:function(data)\r\n                {\r\n                    var pe" +
"rmit=");

            
            #line 24 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
                          Write(ViewBag.Permit);

            
            #line default
            #line hidden
WriteLiteral(";\r\n                    if(permit==16||permit==32)\r\n                    {\r\n       " +
"                 var DeptId=\'");

            
            #line 27 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
                               Write(ViewBag.DeptId);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n                        $(\"#Dept\").combobox(\'setValue\',DeptId);\r\n            " +
"        }\r\n                }\r\n            });\r\n            //数据表格\r\n            J" +
"Q.datagrid.datagrid({\r\n                JQPrimaryID: \'EmpID\',//主键的字段\r\n           " +
"     JQID: \'leftGrid\',//数据表格ID\r\n                JQDialogTitle: \'用户信息\',//弹出窗体标题\r\n" +
"                JQWidth: \'240\',//弹出窗体宽\r\n                JQHeight: \'100%\',//弹出窗体高" +
"\r\n                JQLoadingType: \'datagrid\',//数据表格类型 [datagrid,treegrid]\r\n      " +
"          url: requestUrl,//请求的地址\r\n                checkOnSelect: false,//是否包含ch" +
"eck\r\n                singleSelect: true,\r\n                JQFields: [\"EmpID,EmpD" +
"epID\"],//追加的字段名\r\n                //JQMergeCells: { fields: [\'DepartmentName\'] }," +
"//当字段值相同时会自动的跨行(只对相邻有效)\r\n                columns: [[\r\n                    {\r\n   " +
"                     title: \'所属部门\', field: \'DepartmentName\', width: \"32%\", align" +
": \'left\', sortable: true\r\n\r\n                    },\r\n                  {\r\n       " +
"               title: \'姓名\', field: \'EmpName\', width: \"26%\", align: \'left\', sorta" +
"ble: true,\r\n                      formatter: function (val, row) {\r\n            " +
"              return \'<a class=\"easyui-linkbutton\" href=\"#\" onclick=\"Select(\' + " +
"row.EmpID + \')\">\' + row.EmpName + \'</a>\'\r\n                      }\r\n\r\n           " +
"       },\r\n                  {\r\n                      title: \'金额\', field: \'Balan" +
"ceMoney\', width: \"34%\", align: \'right\',\r\n                  }\r\n                ]]" +
",\r\n                onLoadSuccess: function (row) {\r\n                    //var we" +
"stRegionCount = $(\"#westRegion\").find(\"div[class=\'pagination-info\']\").text();\r\n " +
"                   //var countInfo = westRegionCount.split(\',\');\r\n              " +
"      //$(\"#westRegion\").find(\"div[class=\'pagination-info\']\").text(countInfo[1])" +
";\r\n                }\r\n\r\n            });\r\n\r\n            setTextAlign(\"DepartmentN" +
"ame\", \"text-align:center;\")\r\n            setTextAlign(\"EmpName\", \"text-align:cen" +
"ter;\")\r\n            setTextAlign(\"BalanceMoney\", \"text-align:center;\")\r\n        " +
"    var permit=");

            
            #line 72 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
                  Write(ViewBag.Permit);

            
            #line default
            #line hidden
WriteLiteral(";\r\n            if(permit==16||permit==32)\r\n            {\r\n                $(\"#Dep" +
"t\").combobox({disabled:true});\r\n            }\r\n            $(\"#JQSearch\").textbo" +
"x({\r\n                buttonText: \'筛选\',\r\n                buttonIcon: \'fa fa-searc" +
"h\',\r\n                height: 25,\r\n                prompt: \'批次名称\',\r\n             " +
"   //queryOptions: { \'Key\': \'LotName\', \'Contract\': \'like\' },\r\n                on" +
"ClickButton: function () {\r\n                    JQ.datagrid.searchGrid(\r\n       " +
"                 {\r\n                            dgID: \'rightGrid\',\r\n            " +
"                loadingType: \'datagrid\',\r\n                            queryParam" +
"s: {\r\n                                KeyJQSearch: $(\"#JQSearch\").val(),\r\n      " +
"                          startTime: $(\"#startTime\").textbox(\'getValue\'),\r\n     " +
"                           endTime: $(\"#endTime\").textbox(\'getValue\'),\r\n        " +
"                    }\r\n                        });\r\n                }\r\n\r\n       " +
"     });\r\n\r\n            //$(\"#westRegion\").find(\"div[class=\'datagrid-view\']\").ne" +
"xt().find(\'a\').eq(0).hide();\r\n            //$(\"#westRegion\").find(\"div[class=\'da" +
"tagrid-view\']\").next().find(\'a\').eq(3).hide();\r\n            $(\"#westRegion\").fin" +
"d(\"select[class=\'pagination-page-list\']\").hide();\r\n            $(\"#westRegion\")." +
"find(\"div[class=\'pagination-info\']\").hide();\r\n\r\n\r\n            JQ.datagrid.datagr" +
"id({\r\n                JQPrimaryID: \'FormID\',//主键的字段\r\n                JQID: \'righ" +
"tGrid\',//数据表格ID\r\n                JQDialogTitle: \'信息\',//弹出窗体标题\r\n                J" +
"QWidth: \'960\',//弹出窗体宽\r\n                JQHeight: \'100%\',//弹出窗体高\r\n               " +
" JQLoadingType: \'datagrid\',//数据表格类型 [datagrid,treegrid]\r\n                url: \'");

            
            #line 111 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
                 Write(Url.Action("Sumjson", "PayBalanceSum", new { @area = "Pay" }));

            
            #line default
            #line hidden
WriteLiteral("\',//请求的地址\r\n                checkOnSelect: true,//是否包含check\r\n                toolb" +
"ar: \'#PaySumPanel\',//工具栏的容器ID\r\n                singleSelect: true,\r\n            " +
"    frozenColumns: [[{ title: \'结算批次名称\', field: \'BalanceLotName\', width: \"15%\", a" +
"lign: \'center\', sortable: true },\r\n                { title: \'结算日期\', field: \'Bala" +
"nceDate\', width: \"10%\", align: \'center\', sortable: true, formatter: JQ.tools.Dat" +
"eTimeFormatterByT }\r\n                ]],\r\n                JQMergeCells: { fields" +
": [\'BalanceLotName\', \'BalanceDate\'] },//当字段值相同时会自动的跨行(只对相邻有效)\r\n                c" +
"olumns: [[\r\n\r\n\t{ title: \'项目编号\', field: \'ProjNumber\', width: \"12%\", align: \'left\'" +
", sortable: true },\r\n\t\t{ title: \'项目名称\', field: \'ProjName\', width: \"25%\", align: " +
"\'left\', sortable: true },\r\n{ title: \'人员\', field: \'TechEmpName\', width: \"8%\", ali" +
"gn: \'center\', sortable: true },\r\n        { title: \'来源\', field: \'BalanceReason\', " +
"width: \"8%\", align: \'coneter\', sortable: true },\r\n        { title: \'产值\', field: " +
"\'BalanceAmount\', width: \"10%\", align: \'right\', sortable: true },\r\n        { titl" +
"e: \'金额\', field: \'BalanceMoney\', width: \"10%\", align: \'right\', sortable: true }\r\n" +
"                ]],\r\n                onHeaderContextMenu: function (e, field) {\r" +
"\n                    e.preventDefault();\r\n                    if (!cmenu) {\r\n   " +
"                     createColumnMenu();\r\n                    }\r\n               " +
"     cmenu.menu(\'show\', {\r\n                        left: e.pageX,\r\n             " +
"           top: e.pageY\r\n                    });\r\n                }\r\n           " +
" });\r\n\r\n\r\n        });\r\n        var cmenu;\r\n        function createColumnMenu() {" +
"\r\n            cmenu = $(\'<div/>\').appendTo(\'body\');\r\n            cmenu.menu({\r\n " +
"               onClick: function (item) {\r\n                    if (item.iconCls " +
"== \'fa fa-check\') {\r\n                        $(\'#rightGrid\').datagrid(\'hideColum" +
"n\', item.name);\r\n                        //$(this).find(\'input[type=\"checkbox\"]\'" +
").attr(\"checked\",false);\r\n                        cmenu.menu(\'setIcon\', {\r\n     " +
"                       target: item.target,\r\n                            iconCls" +
": \'fa fa-square-o\'\r\n                        });\r\n                    } else {\r\n " +
"                       $(\'#rightGrid\').datagrid(\'showColumn\', item.name);\r\n     " +
"                   cmenu.menu(\'setIcon\', {\r\n                            target: " +
"item.target,\r\n                            iconCls: \'fa fa-check\'\r\n              " +
"          });\r\n                    }\r\n                }\r\n            });\r\n      " +
"      var fields = $(\'#rightGrid\').datagrid(\'getColumnFields\');\r\n            for" +
" (var i = 0; i < fields.length; i++) {\r\n                var field = fields[i];\r\n" +
"                var col = $(\'#rightGrid\').datagrid(\'getColumnOption\', field);\r\n " +
"               cmenu.menu(\'appendItem\', {\r\n                    text: col.title,\r" +
"\n                    name: field,\r\n                    iconCls: \'fa fa-check\'\r\n " +
"               });\r\n            }\r\n        }\r\n        function Select(EmpID) {\r\n" +
"            $(\"#rightGrid\").datagrid(\'reload\', \'");

            
            #line 175 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
                                           Write(Url.Action("Sumjson", "PayBalanceSum", new { @area = "Pay" }));

            
            #line default
            #line hidden
WriteLiteral("?EmpID=\' + EmpID);\r\n        }\r\n        ");

WriteLiteral("\r\n\r\n        function setTextAlign(filed, align) {\r\n            $(\"tr[class=\'datag" +
"rid-header-row\']\").find(\"td[field=\'\" + filed + \"\']\").children().removeAttr(\"styl" +
"e\").attr(\"style\", align);\r\n        }\r\n    </script>\r\n");

WriteLiteral("    ");

            
            #line 185 "..\..\Views\PayBalanceSum\PayStatistics.cshtml"
Write(RenderPage("~/Areas/Core/Views/Shared/_Init.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("Body_Content", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" id=\"cc\"");

WriteLiteral(" class=\"easyui-layout\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(" fit=\"true\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" data-options=\"region:\'north\'\"");

WriteLiteral(" style=\"height:40px;line-height:40px;\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" style=\"margin-left:20px;font-size:13px;\"");

WriteLiteral(">部门:</span>\r\n            <select");

WriteLiteral(" id=\"Dept\"");

WriteLiteral(" class=\"easyui-combobox\"");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral("></select>\r\n            <span");

WriteLiteral(" style=\"margin-left:20px;font-size:13px;\"");

WriteLiteral(">筛选条件:</span>\r\n            <input");

WriteLiteral(" id=\"JQSearch\"");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral(" />\r\n            <span");

WriteLiteral(" style=\"margin-left:20px;font-size:13px;\"");

WriteLiteral(">结算日期:</span>\r\n            <input");

WriteLiteral(" id=\"startTime\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" style=\"width:100px\"");

WriteLiteral(" data-options=\"prompt: \'结算开始时间\'\"");

WriteLiteral(">\r\n            --\r\n            <input");

WriteLiteral(" id=\"endTime\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" style=\"width:100px\"");

WriteLiteral(" data-options=\"prompt: \'结算结束时间\'\"");

WriteLiteral(">&nbsp;\r\n            <div");

WriteLiteral(" id=\"PayLotPanel\"");

WriteLiteral(" jqpanel=\"searchPanel\"");

WriteLiteral(" style=\"padding:5px;height:auto;\"");

WriteLiteral(">\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" id=\"westRegion\"");

WriteLiteral(" data-options=\"region:\'west\'\"");

WriteLiteral(" style=\"width:320px;\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" id=\"leftGrid\"");

WriteLiteral("></table>\r\n        </div>\r\n        <div");

WriteLiteral(" data-options=\"region:\'center\'\"");

WriteLiteral(" style=\"background:#eee;\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" id=\"rightGrid\"");

WriteLiteral("></table>\r\n        </div>\r\n    </div>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
