#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Project\IsoConfig.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Project/IsoConfig.cshtml")]
    public partial class _Views_Project_IsoConfig_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Project_IsoConfig_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

    $(function () {
        JQ.datagrid.datagrid({
            JQButtonTypes: [],
            JQPrimaryID: ""FlowID"",
            JQID: ""IsoList"",
            JQDialogTitle: ""表单"",
            JQWidth: ""1024"",//弹出窗体宽
            JQHeight: '100%',//弹出窗体高
            JQLoadingType: ""datagrid"",
            url: """);

            
            #line 14 "..\..\Views\Project\IsoConfig.cshtml"
              Write(Url.Action("GetFormsByProjID1", "IsoForm", new { @area = "Iso" }));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n            checkOnSelect: true,\r\n            singleSelect: true,\r\n          " +
"  nowrap: false,\r\n            toolbar: \"#list_toolbar\",\r\n            columns: [[" +
"\r\n                { field: \'ck\', align: \'center\', checkbox: true, JQIsExclude: t" +
"rue },\r\n                { title: \"表单标题\", field: \"FlowTitle\", width: \"40%\", align" +
": \"left\", halign: \"center\" },\r\n                { title: \"流程名称\", field: \"FlowName" +
"\", width: \"13%\", align: \"left\", halign: \"center\" },\r\n                { title: \"发" +
"起日期\", field: \"CreationTime\", width: \"10%\", align: \"center\",sortable:true, halign" +
": \"center\", formatter: JQ.tools.DateTimeFormatterByT },\r\n                { title" +
": \"发起人\", field: \"CreatorEmpName\", width: \"10%\", align: \"center\", halign: \"center" +
"\" },\r\n                {\r\n                    title: \"进度\", field: \"FlowStatusName" +
"\", width: \"13%\", align: \"left\", halign: \"center\", formatter: function (value, ro" +
"wData) {\r\n                        var a = document.createElement(\"a\");\r\n        " +
"                a.setAttribute(\"href\", \"javascript:void(0)\");\r\n                 " +
"       a.appendChild(document.createTextNode(value));\r\n                        a" +
".setAttribute(\"onclick\", \"openProgressDialog(\" + rowData.FlowId + \",\'\" + encodeU" +
"RIComponent(rowData.FlowName) + \"\');\");\r\n                        return a.outerH" +
"TML;\r\n                    }\r\n                },\r\n                {\r\n            " +
"        title: \"操作\", field: \"CZ\", width: \"8%\", align: \"center\", halign: \"center\"" +
", formatter: function (value, row, index) {\r\n                        return \'<a " +
"btn  class=\"easyui-linkbutton\"  data-options=\"iconCls:\\\'fa fa-check\\\'\"   onclick" +
"=\"Edit(\' + row.ID + \')\">\' + row.NodeState + \'</a>\';\r\n                    }\r\n    " +
"            }\r\n            ]],\r\n            queryParams: { projectID:");

            
            #line 40 "..\..\Views\Project\IsoConfig.cshtml"
                                Write(Request.Params["projId"]);

            
            #line default
            #line hidden
WriteLiteral(", phaseID:");

            
            #line 40 "..\..\Views\Project\IsoConfig.cshtml"
                                                                   Write(Request.Params["phaseID"]);

            
            #line default
            #line hidden
WriteLiteral(" },\r\n            onBeforeCheck: function (rowIndex, rowData) {\r\n                i" +
"f (rowData.FlowStatusID == 3) {\r\n                    return false;\r\n            " +
"    } else if (rowData.FlowStatusID == 2 && rowData.FlowStatusName.indexOf(\"退回至\"" +
") == -1) {\r\n                    return false;\r\n                } else if (rowDat" +
"a.FlowStatusID == 2 && rowData.FlowStatusName.indexOf(\"退回至\") != -1 && rowData.Cr" +
"eatorEmpId != rowData.FlowNodeEmpId) {\r\n                    return false;\r\n     " +
"           }\r\n            },\r\n            onClickRow: function (rowIndex, rowDat" +
"a) {\r\n                if (rowData.FlowStatusID == 3) {\r\n                    $(th" +
"is).datagrid(\'unselectRow\', rowIndex);\r\n                } else if (rowData.FlowS" +
"tatusID == 2 && rowData.FlowStatusName.indexOf(\"退回至\") == -1) {\r\n                " +
"    $(this).datagrid(\'unselectRow\', rowIndex);\r\n                } else if (rowDa" +
"ta.FlowStatusID == 2 && rowData.FlowStatusName.indexOf(\"退回至\") != -1 && rowData.C" +
"reatorEmpId != rowData.FlowNodeEmpId) {\r\n                    $(this).datagrid(\'u" +
"nselectRow\', rowIndex);\r\n                }\r\n            },\r\n            onLoadSu" +
"ccess: function (data) {\r\n                $(\"div.datagrid-header-check input[typ" +
"e=\'checkbox\']\").attr(\"style\", \"display:none\");\r\n                var rowViews = $" +
"(\"#IsoList\").parent().find(\".datagrid-view2 .datagrid-body tr.datagrid-row\");\r\n " +
"               for (var i = 0; i < data.rows.length; i++) {\r\n                   " +
" debugger;\r\n                    if (data.rows[i].FlowStatusID == 3) {\r\n         " +
"              rowViews.filter(\"[datagrid-row-index=\'\" + i + \"\']\").find(\"td[field" +
"=\'ck\'] :checkbox\").prop(\"disabled\", \"disabled\");\r\n                    } else if " +
"(data.rows[i].FlowStatusID == 2 && data.rows[i].FlowStatusName.indexOf(\"退回至\") ==" +
" -1) {\r\n                        rowViews.filter(\"[datagrid-row-index=\'\" + i + \"\'" +
"]\").find(\"td[field=\'ck\'] :checkbox\").prop(\"disabled\", \"disabled\");\r\n            " +
"        } else if (data.rows[i].FlowStatusID == 2 && data.rows[i].FlowStatusName" +
".indexOf(\"退回至\") != -1 && data.rows[i].CreatorEmpId != data.rows[i].FlowNodeEmpId" +
" && data.rows[i].CreatorEmpId == \'");

            
            #line 68 "..\..\Views\Project\IsoConfig.cshtml"
                                                                                                                                                                                                         Write(ViewBag.CurrEmpId);

            
            #line default
            #line hidden
WriteLiteral(@"') {
                        rowViews.filter(""[datagrid-row-index='"" + i + ""']"").find(""td[field='ck'] :checkbox"").prop(""disabled"", ""disabled"");
                    }
                }
            }
        });

        $(""#IsoType"").datagrid({
            url: """);

            
            #line 76 "..\..\Views\Project\IsoConfig.cshtml"
              Write(Url.Action("getAllFormJson", "IsoForm", new { @area = "Iso" }));

            
            #line default
            #line hidden
WriteLiteral(@""",
            singleSelect: true,
            columns: [[
                { title: ""表单名称"", field: ""text"", width: ""100%"", align: ""center"", halign: ""center"" }
            ]],
            onClickRow: function (index, row) {
                var addUrl = '/GoldPM9_gdgzshcj/iso/' + row.ModelRefTable + '/add?projId=");

            
            #line 82 "..\..\Views\Project\IsoConfig.cshtml"
                                                                                    Write(Request.Params["projId"]);

            
            #line default
            #line hidden
WriteLiteral("&phaseID=");

            
            #line 82 "..\..\Views\Project\IsoConfig.cshtml"
                                                                                                                      Write(Request.Params["phaseID"]);

            
            #line default
            #line hidden
WriteLiteral("&taskGroupId=");

            
            #line 82 "..\..\Views\Project\IsoConfig.cshtml"
                                                                                                                                                             Write(Request.Params["taskGroupId"]);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n                $(\"#add\").attr(\"src\", addUrl);\r\n\r\n                $(\'#IsoList" +
"\').datagrid(\'load\',{\r\n                    projectID:");

            
            #line 86 "..\..\Views\Project\IsoConfig.cshtml"
                         Write(Request.Params["projId"]);

            
            #line default
            #line hidden
WriteLiteral(",\r\n                    phaseID:");

            
            #line 87 "..\..\Views\Project\IsoConfig.cshtml"
                       Write(Request.Params["phaseID"]);

            
            #line default
            #line hidden
WriteLiteral(" ,\r\n                    tableName : row.text\r\n                });\r\n            }\r" +
"\n        });\r\n    });\r\n\r\n    function openProgressDialog(flowID, flowName) {\r\n  " +
"      JQ.Flow.showProgressDialog(decodeURIComponent(flowName), \"");

            
            #line 95 "..\..\Views\Project\IsoConfig.cshtml"
                                                              Write(Url.Action("Progress","PubFlow",new { @area="Core" }));

            
            #line default
            #line hidden
WriteLiteral(@"?flowID="" + flowID);
        JQ.Flow.stopBubble();
    }

    function add() {
        var isTrue = false;
        var row = $(""#IsoType"").datagrid(""getSelected"");
        if (row == null) {
            JQ.dialog.warning(""请选择表单类型！！！"");
            isTrue = true;
        }
        if(isTrue)
            return;

        if(row.text == '设计报出单' )
        {
            $.ajax({
                url:'");

            
            #line 112 "..\..\Views\Project\IsoConfig.cshtml"
                Write(Url.Action("GetIsFinish"));

            
            #line default
            #line hidden
WriteLiteral("?projId=");

            
            #line 112 "..\..\Views\Project\IsoConfig.cshtml"
                                                  Write(Request.Params["projId"]);

            
            #line default
            #line hidden
WriteLiteral("&phaseId=");

            
            #line 112 "..\..\Views\Project\IsoConfig.cshtml"
                                                                                    Write(Request.Params["phaseID"]);

            
            #line default
            #line hidden
WriteLiteral(@"',
                type:""get"",
                dataType:""html"",
                async:false,
                success : function(data){
                    if(data == ""False"")
                    {
                        JQ.dialog.warning(""请填写必要表单.有设计策划单,专业指导纪要,工程地质勘察条件单,工程测量条件单(设计策划单中如勾选要求评审,则需提交设计评审纪要表)"");
                        isTrue = true;
                    }
                }
            });
            if(isTrue)
                return;
        }

        var src = $(""#add"").attr(""src"");
        JQ.dialog.dialog({
            title: row.text,
            url: src,
            width: '1024',
            height: '100%',
            iconCls: 'fa fa-plus',
            onClose: function () {
                $(""#IsoList"").datagrid(""reload"");
            }
        });
    }

    function Edit(id) {
        var data = $(""#IsoList"").datagrid(""getRows"");
        var row = Enumerable.From(data).Where(""x=>x.ID=="" + id + """").FirstOrDefault();
        var FlowUrl = row.FlowUrl;

        JQ.dialog.dialog({
            title: ""查看"",
            url: """);

            
            #line 148 "..\..\Views\Project\IsoConfig.cshtml"
              Write(ViewBag.sitePath);

            
            #line default
            #line hidden
WriteLiteral("\" + FlowUrl+\'&projId=");

            
            #line 148 "..\..\Views\Project\IsoConfig.cshtml"
                                                     Write(Request.Params["projId"]);

            
            #line default
            #line hidden
WriteLiteral("&phaseId=");

            
            #line 148 "..\..\Views\Project\IsoConfig.cshtml"
                                                                                       Write(Request.Params["phaseID"]);

            
            #line default
            #line hidden
WriteLiteral("&taskGroupId=");

            
            #line 148 "..\..\Views\Project\IsoConfig.cshtml"
                                                                                                                              Write(Request.Params["taskGroupId"]);

            
            #line default
            #line hidden
WriteLiteral(@"',
            width: '1024',
            height: '100%',
            onClose: function () {
                $(""#IsoList"").datagrid(""reload"");
            }
        });
    }

    function Delete() {
        var data = $(""#IsoList"").datagrid(""getChecked"");
        if (data.length == 0) {
            JQ.dialog.warning(""请选择要删除的数据"");
            return;
        } else {
            JQ.dialog.confirm(""是否确认删除选中数据？？？"", function () {
                debugger
                $.ajax({
                    url: """);

            
            #line 166 "..\..\Views\Project\IsoConfig.cshtml"
                      Write(Url.Action("DelIso1", "Project",new { @area="Project"} ));

            
            #line default
            #line hidden
WriteLiteral(@"?Id="" + data[0].ID + ""&tableName="" + data[0].FlowName,
                    type: ""POST"",
                    dataType:""json"",
                    success: function (data) {
                        $(""#IsoList"").datagrid(""reload"");
                    }
                })
            });
        }
    }
</script>

<div");

WriteLiteral(" id=\"treePanel\"");

WriteLiteral(" class=\"easyui-layout\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(" fit=\"true\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" data-options=\"region:\'west\',split:false\"");

WriteLiteral(" style=\"width:220px;\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" id=\"IsoType\"");

WriteLiteral("></table>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" data-options=\"region:\'center\'\"");

WriteLiteral(" style=\"background:#eee;height:100%;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"list_toolbar\"");

WriteLiteral(" jqpanel=\"searchPanel\"");

WriteLiteral(" style=\"padding:5px;height:auto;\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" jqpanel=\"toolbarPanel\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" id=\"add\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'fa fa-plus\'\"");

WriteLiteral(" onclick=\"add()\"");

WriteLiteral(">新增</a>\r\n                <a");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" id=\"add\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'fa fa-plus\'\"");

WriteLiteral(" onclick=\"Delete()\"");

WriteLiteral(">删除</a>\r\n            </span>\r\n        </div>\r\n        <table");

WriteLiteral(" id=\"IsoList\"");

WriteLiteral("></table>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
