#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\WDManage\info.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/WDManage/info.cshtml")]
    public partial class _Views_WDManage_info_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_WDManage_info_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<style>\r\n    .wdplane {\r\n        height: 100%;\r\n        text-align: center;\r\n    " +
"    overflow: hidden;\r\n    }\r\n\r\n        .wdplane a {\r\n            margin-top: 87" +
"px;\r\n            margin-left: 10px;\r\n        }\r\n</style>\r\n<div");

WriteLiteral(" class=\"wdplane\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" name=\"ProjNote\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'fa fa-plus\'\"");

WriteLiteral(" onclick=\"ProjNote()\"");

WriteLiteral(">项目记事</a>\r\n    <a");

WriteLiteral(" name=\"DocUpload\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'fa fa-plus\'\"");

WriteLiteral(" onclick=\"DocUpload()\"");

WriteLiteral(">项目资料分类上传</a>\r\n</div>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    // 填写项目记事\r\n    function ProjNote() {\r\n        JQ.dialog.dialogIframe({\r\n  " +
"          title: \"项目记事\",\r\n            //title: \"填写项目记事\",\r\n            ");

WriteLiteral("\r\n            url: \'");

            
            #line 25 "..\..\Views\WDManage\info.cshtml"
             Write(Url.Action("ProjEventList", "DesEvent", new { @area = "design" }));

            
            #line default
            #line hidden
WriteLiteral("?taskGroupId=");

            
            #line 25 "..\..\Views\WDManage\info.cshtml"
                                                                                            Write(ViewBag.EngineeringID);

            
            #line default
            #line hidden
WriteLiteral("&empId=");

            
            #line 25 "..\..\Views\WDManage\info.cshtml"
                                                                                                                         Write(Request["empId"]);

            
            #line default
            #line hidden
WriteLiteral("&projID=");

            
            #line 25 "..\..\Views\WDManage\info.cshtml"
                                                                                                                                                  Write(Request["projID"]);

            
            #line default
            #line hidden
WriteLiteral(@"',
            width: '1200',
            height: '100%',
            JQID: 'ProjTable',
            JQLoadingType: 'datagrid',
            iconCls: 'fa fa-list',
        });
    }

    // 资料分类上传
    function DocUpload() {
        JQ.dialog.dialog({
            title: ""项目资料分类上传"",
            url: '");

            
            #line 38 "..\..\Views\WDManage\info.cshtml"
             Write(Url.Action("treelist", "ArchElecProject", new { @area = "archive" }));

            
            #line default
            #line hidden
WriteLiteral("?ProjID=");

            
            #line 38 "..\..\Views\WDManage\info.cshtml"
                                                                                          Write(ViewBag.ProjID);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            width: \'1200\',\r\n            height: \'100%\',\r\n            JQID: \'P" +
"rojTable\',\r\n            JQLoadingType: \'datagrid\',\r\n            iconCls: \'fa fa-" +
"list\',\r\n        });\r\n    }\r\n</script>");

        }
    }
}
#pragma warning restore 1591
