#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BaseAttach/AttachInfo.cshtml")]
    public partial class _Views_BaseAttach_AttachInfo_cshtml : System.Web.Mvc.WebViewPage<DataModel.Models.BaseAttach>
    {
        public _Views_BaseAttach_AttachInfo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<script>
    JQ.form.submitInit({
        formid: ""form_attachinfo"",
        buttonTypes: [""close""],
        beforeButtons: [
            {
                icon: ""fa-save"", text: ""保存"", onClick: function () {
                    if (!$(""#form_attachinfo"").form(""validate"")) {
                        return
                    }
                    $.ajax({
                        url: """);

            
            #line 13 "..\..\Views\BaseAttach\AttachInfo.cshtml"
                          Write(Url.Action("SaveAttachNote", "BaseAttach",new { @area="Core" }));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                        type: \"POST\",\r\n                        data: { attach" +
"ID: \"");

            
            #line 15 "..\..\Views\BaseAttach\AttachInfo.cshtml"
                                       Write(Model.AttachID);

            
            #line default
            #line hidden
WriteLiteral(@""", attachnote: $(""#attachnote"").textbox(""getText"") },
                        success: function (result) {
                            JQ.dialog.dialogClose();
                        }
                    });
                }
            }
        ],
        succesCollBack: function (data) {
        }
    });
    $(function () {
        $(""#AttachSize"").html(JQ.tools.getFileSizeText(");

            
            #line 27 "..\..\Views\BaseAttach\AttachInfo.cshtml"
                                                   Write(Model.AttachSize);

            
            #line default
            #line hidden
WriteLiteral("));\r\n    });\r\n</script>\r\n\r\n<form");

WriteLiteral(" id=\"form_attachinfo\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-hover table-bordered\"");

WriteLiteral(">\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"info\"");

WriteLiteral(">\r\n                文件名称：\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 38 "..\..\Views\BaseAttach\AttachInfo.cshtml"
           Write(Model.AttachName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"info\"");

WriteLiteral(" style=\"width: 100px;\"");

WriteLiteral(">\r\n                文件版本：\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 46 "..\..\Views\BaseAttach\AttachInfo.cshtml"
           Write(Model.AttachVer);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"info\"");

WriteLiteral(">\r\n                文件大小：\r\n            </th>\r\n            <td");

WriteLiteral(" id=\"AttachSize\"");

WriteLiteral("></td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"info\"");

WriteLiteral(">\r\n                修改时间：\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 60 "..\..\Views\BaseAttach\AttachInfo.cshtml"
           Write(Model.AttachDateChange.ToString("yyyy-MM-dd HH:mm:ss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"info\"");

WriteLiteral(">\r\n                上传时间：\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 68 "..\..\Views\BaseAttach\AttachInfo.cshtml"
           Write(Model.AttachDateUpload.ToString("yyyy-MM-dd HH:mm:ss"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"info\"");

WriteLiteral(" style=\"width: 100px;\"");

WriteLiteral(">\r\n                上传人员：\r\n            </th>\r\n            <td>\r\n");

WriteLiteral("                ");

            
            #line 76 "..\..\Views\BaseAttach\AttachInfo.cshtml"
           Write(Model.AttachEmpName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" class=\"info\"");

WriteLiteral(">备注</th>\r\n            <td>\r\n                <textarea");

WriteLiteral(" id=\"attachnote\"");

WriteLiteral(" name=\"attachnote\"");

WriteLiteral(" style=\"width:98%;height:60px\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" spellcheck=\"false\"");

WriteLiteral(" data-options=\"multiline:true\"");

WriteLiteral(" validType=\"length[0,200]\"");

WriteLiteral(">");

            
            #line 82 "..\..\Views\BaseAttach\AttachInfo.cshtml"
                                                                                                                                                                                        Write(ViewBag.Note);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n</form>");

        }
    }
}
#pragma warning restore 1591
