#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DesExch/IsoExchangeInfo.cshtml")]
    public partial class _Views_DesExch_IsoExchangeInfo_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DesExch_IsoExchangeInfo_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    JQ.form.submitInit({
        formid: 'IsoExchangeInfoForm',//formid提交需要用到
        docName: 'IsoDesExch',
        ExportName: '设计条件提供单',
        buttonTypes: ['close', 'exportForm'],//默认按钮
        succesCollBack: function (data) {//成功回调函数,data为服务器返回值
            JQ.dialog.dialogClose();//关闭窗体放在最后一步执行，以避免找不到事件源
        },
        onBefore: function (resultArr) {
            resultArr.push({ Key: ""Permission"", Value: ");

            
            #line 13 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                  Write(ViewBag.Permission);

            
            #line default
            #line hidden
WriteLiteral(" });\r\n        }\r\n    });\r\n\r\n    $(function () {\r\n        $.ajax({\r\n            ur" +
"l: \'");

            
            #line 19 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
             Write(Url.Action("RecSpecAndEmp", "DesExch", new { @area = "Design" }));

            
            #line default
            #line hidden
WriteLiteral("?ExchId=");

            
            #line 19 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                                      Write(ViewBag.DesExchModel.Id);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            dataType: \"json\",\r\n            type:\"POST\",\r\n            success:" +
" function (result, status, xhr) {\r\n                var specId = \'");

            
            #line 23 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                         Write(Request.Params["RecSpecId"]);

            
            #line default
            #line hidden
WriteLiteral(@"';
                var specItem = Enumerable.From(result.rows).Where(""x=>x.RecSpecId="" + specId + """").FirstOrDefault();
                $(""#JSSpecName"").text(specItem.RecSpecName);
                $(""#JSTime"").text(specItem.RecTime);
            }
        });
    });

</script>
<form");

WriteLiteral(" id=\"IsoExchangeInfoForm\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" style=\"width:100%;text-align:center;font-size:20px;font-weight:bold;margin-top:1" +
"0px;\"");

WriteLiteral(">\r\n            <a>设计条件提供单</a>\r\n        </div>\r\n        <div");

WriteLiteral(" style=\"float:left;margin-left:20px;margin-top:10px;\"");

WriteLiteral(">\r\n            表<label>");

            
            #line 39 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
               Write(ViewBag.TableNumber);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n        </div>\r\n        <div");

WriteLiteral(" style=\"float:right;margin-right:20px;margin-top:10px;margin-bottom:10px;\"");

WriteLiteral(">\r\n            编号<input");

WriteLiteral(" id=\"Number\"");

WriteLiteral(" name=\"Number\"");

WriteLiteral(" style=\"width:140px;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" validtype=\"length[0,50]\"");

WriteLiteral(" />\r\n        </div>\r\n        <tr>\r\n            <th>工程名称</th>\r\n            <td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" id=\"ProjName\"");

WriteLiteral(" name=\"ProjName\"");

WriteLiteral(" bookmark=\"ProjName\"");

WriteLiteral(">");

            
            #line 47 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                   Write(ViewBag.ProjName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </td>\r\n            <th>工程编号</th>\r\n            <td>\r\n        " +
"        <span");

WriteLiteral(" id=\"ProjNumber\"");

WriteLiteral(" name=\"ProjNumber\"");

WriteLiteral(" bookmark=\"ProjNumber\"");

WriteLiteral(">");

            
            #line 51 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                         Write(ViewBag.ProjNumber);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">提供专业</th>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" id=\"TGSpecName\"");

WriteLiteral(" name=\"TGSpecName\"");

WriteLiteral(" bookmark=\"TGSpecName\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                         Write(ViewBag.DesExchModel.ExchSpecName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">专业负责人</th>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" id=\"TGSpecHeader\"");

WriteLiteral(" name=\"TGSpecHeader\"");

WriteLiteral(" bookmark=\"TGSpecHeader\"");

WriteLiteral(">");

            
            #line 61 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                               Write(ViewBag.TGSpecHeader);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">提供日期</th>\r\n            <td");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" id=\"TGTime\"");

WriteLiteral(" name=\"TGTime\"");

WriteLiteral(" bookmark=\"TGTime\"");

WriteLiteral(">");

            
            #line 65 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                             Write(ViewBag.CreationTime);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">接受专业</th>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" id=\"JSSpecName\"");

WriteLiteral(" name=\"JSSpecName\"");

WriteLiteral(" bookmark=\"JSSpecName\"");

WriteLiteral("></span>\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">专业负责人</th>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" id=\"JSSpecHeader\"");

WriteLiteral(" name=\"JSSpecHeader\"");

WriteLiteral(" bookmark=\"JSSpecHeader\"");

WriteLiteral(">");

            
            #line 75 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                               Write(ViewBag.JSSpecHeader);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">接受日期</th>\r\n            <td");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" id=\"JSTime\"");

WriteLiteral(" name=\"JSTime\"");

WriteLiteral(" bookmark=\"JSTime\"");

WriteLiteral("></span>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <td");

WriteLiteral(" colspan=\"6\"");

WriteLiteral(" bookmark=\"ExchContent\"");

WriteLiteral(">\r\n                设计条件（主要控制数据及文字说明、所附文件及简图的名称）：\r\n                <br>\r\n         " +
"       <div");

WriteLiteral(" id=\"TZNR\"");

WriteLiteral(" name=\"TZNR\"");

WriteLiteral(" style=\"height:500px;\"");

WriteLiteral(" bookmark=\"TZNR\"");

WriteLiteral(">");

            
            #line 86 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                            Write(ViewBag.DesExchModel.ExchContent);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>设计人/日期</t" +
"h>\r\n            <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral("><span");

WriteLiteral(" id=\"TZR_EmpName\"");

WriteLiteral(" name=\"TZR_EmpName\"");

WriteLiteral(" bookmark=\"TZR_EmpName\"");

WriteLiteral(" style=\"padding-right:20px;\"");

WriteLiteral(">");

            
            #line 91 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                                                                    Write(ViewBag.DesExchModel.ExchEmpName);

            
            #line default
            #line hidden
WriteLiteral("</span><span");

WriteLiteral(" id=\"TZTime\"");

WriteLiteral(" name=\"TZTime\"");

WriteLiteral(" bookmark=\"TZTime\"");

WriteLiteral(">");

            
            #line 91 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                                                                                                                                                              Write(ViewBag.CreationTime);

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n            <th>校核人（专业负责人）/日期</th>\r\n            <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral("><span");

WriteLiteral(" id=\"JHR_EmpName\"");

WriteLiteral(" name=\"JHR_EmpName\"");

WriteLiteral(" bookmark=\"JHR_EmpName\"");

WriteLiteral(" style=\"padding-right:20px;\"");

WriteLiteral(">");

            
            #line 93 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                                                                    Write(ViewBag.JHR);

            
            #line default
            #line hidden
WriteLiteral("</span><span");

WriteLiteral(" id=\"JHTime\"");

WriteLiteral(" name=\"JHTime\"");

WriteLiteral(" bookmark=\"JHTime\"");

WriteLiteral(">");

            
            #line 93 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                                                                                                                                         Write(ViewBag.JHTime);

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n        </tr>\r\n        <tr>\r\n            <th>审核人/日期</th>\r\n         " +
"   <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral("><span");

WriteLiteral(" id=\"SHR_EmpName\"");

WriteLiteral(" name=\"SHR_EmpName\"");

WriteLiteral(" bookmark=\"SHR_EmpName\"");

WriteLiteral(" style=\"padding-right:20px;\"");

WriteLiteral(">");

            
            #line 97 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                                                                    Write(ViewBag.SHR);

            
            #line default
            #line hidden
WriteLiteral("</span><span");

WriteLiteral(" id=\"SHTime\"");

WriteLiteral(" name=\"SHTime\"");

WriteLiteral(" bookmark=\"SHTime\"");

WriteLiteral(">");

            
            #line 97 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                                                                                                                                         Write(ViewBag.SHTime);

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n            <th>审定人/日期</th>\r\n            <td");

WriteLiteral(" colspan=\"2\"");

WriteLiteral("><span");

WriteLiteral(" id=\"SDR_EmpName\"");

WriteLiteral(" name=\"SDR_EmpName\"");

WriteLiteral(" bookmark=\"SDR_EmpName\"");

WriteLiteral(" style=\"padding-right:20px;\"");

WriteLiteral(">");

            
            #line 99 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                                                                    Write(ViewBag.SDR);

            
            #line default
            #line hidden
WriteLiteral("</span><span");

WriteLiteral(" id=\"SDTime\"");

WriteLiteral(" name=\"SDTime\"");

WriteLiteral(" bookmark=\"SDTime\"");

WriteLiteral(">");

            
            #line 99 "..\..\Views\DesExch\IsoExchangeInfo.cshtml"
                                                                                                                                                                                         Write(ViewBag.SDTime);

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n        </tr>\r\n    </table>\r\n</form>");

        }
    }
}
#pragma warning restore 1591
