#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\DesExch\IsoExchList.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/DesExch/IsoExchList.cshtml")]
    public partial class _Views_DesExch_IsoExchList_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_DesExch_IsoExchList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\DesExch\IsoExchList.cshtml"
  
    Layout = "~/Areas/Core/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var requestUrl = \'");

            
            #line 7 "..\..\Views\DesExch\IsoExchList.cshtml"
                     Write(Url.Action("ProjExchList", "DesExch", new { @area = "Design" }));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        var params = {\r\n            \'IsAll\': \'new\',\r\n        };\r\n        $(fu" +
"nction () {\r\n            JQ.datagrid.datagrid({\r\n                toolbar: \'#DesE" +
"xchPanel\',\r\n                JQPrimaryID: \'Id\',//主键的字段\r\n                JQID: \"De" +
"sExchGrid\",//数据表格ID\r\n                JQLoadingType: \'datagrid\',//数据表格类型 [datagri" +
"d,datagrid]\r\n                checkOnSelect: false,\r\n                selectOnChec" +
"k: false,\r\n                fit: true,\r\n                pagination: true,\r\n      " +
"          collapsible: true,\r\n                JQMergeCells: { fields: [\'Id\', \'Ex" +
"chTitle\', \'ExchSpecName\', \'ExchEmpName\', \'SpecIdent\', \'EmpIdent\', \'dateIdent\', \'" +
"NumberIdent\', \'projIdent\', \'process\', \'opr\', \'CreationTime\'] },\r\n               " +
" url: requestUrl,\r\n                columns: [[\r\n                    {\r\n         " +
"               title: \'项目名称\', field: \'NumberIdent\', width: \"18%\", halign: \'cente" +
"r\', align: \'left\',\r\n                        formatter: function (val, row) {\r\n  " +
"                          if (row.ExchIsInvalid == false) {\r\n                   " +
"             return \'<span style=\"color:red;\">\' + row.ProjName + \'</span>\'\r\n    " +
"                        }\r\n                            else {\r\n                 " +
"               return row.ProjName;\r\n                            }\r\n\r\n          " +
"              }\r\n                    },\r\n                    //{\r\n              " +
"      //    title: \'项目阶段\', field: \'projIdent\', width: \'100\', halign: \'center\', a" +
"lign: \'center\',\r\n                    //    formatter: function (val, row) {\r\n   " +
"                 //        return row.Phasename;\r\n                    //    }\r\n " +
"                   //},\r\n                    {\r\n                        title: \'" +
"资料名称\', field: \'ExchTitle\', width: \"15%\", align: \'left\', halign: \'center\',\r\n     " +
"                   formatter: function (val, row) {\r\n                           " +
" return row.ExchTitle;//\'<b>\'+row.ExchTitle+\'</b>\';\r\n                        }\r\n" +
"                    },\r\n                    {\r\n                        title: \'提" +
"资专业\', field: \'SpecIdent\', width: \"8%\", align: \'center\', halign: \'center\',\r\n     " +
"                   formatter: function (val, row, index) {\r\n                    " +
"        return row.ExchSpecName;\r\n                        }\r\n                   " +
" },\r\n                    {\r\n                        title: \'提资人\', field: \'EmpIde" +
"nt\', width: \"6%\", align: \'center\', halign: \'center\',\r\n                        fo" +
"rmatter: function (val, row) {\r\n                            return row.ExchEmpNa" +
"me;\r\n                        }\r\n                    },\r\n\r\n                    {\r" +
"\n                        title: \'提资时间\', field: \'CreationTime\', width: \"12%\", ali" +
"gn: \'center\', halign: \'center\'\r\n                    },\r\n\r\n                    { " +
"title: \'收资专业\', field: \'RecSpecName\', width: \"8%\", align: \'center\', halign: \'cent" +
"er\' },\r\n                    { title: \'收资人\', field: \'RecEmpName\', width: \"6%\", al" +
"ign: \'center\', halign: \'center\' },\r\n                    { title: \'接收时间\', field: " +
"\'RecTime\', width: \"8%\", align: \'left\', halign: \'center\', formatter: JQ.tools.Dat" +
"eTimeFormatterByT }, //\r\n\r\n                    {\r\n                        title:" +
" \'提资期限\', field: \'dateIdent\', width: \"8%\", align: \'center\', halign: \'center\',\r\n  " +
"                      formatter: function (val, row)//JQ.tools.DateTimeFormatter" +
"ByT\r\n                        {\r\n                            var value = \"\";\r\n   " +
"                         if (JQ.tools.isNotEmpty(row.ExcLastPutTime)) {\r\n       " +
"                         value = row.ExcLastPutTime.replace(\"T\", \" \").substring(" +
"0, 10);\r\n\r\n                                if (row.ExcLastPutTime.substring(0, 4" +
") <= 1900)\r\n                                    value = \"\";\r\n                   " +
"         }\r\n                            return value;\r\n                        }" +
"\r\n                    },\r\n                    {\r\n                        title: " +
"\'提资单\', field: \'projIdent\', width: \"8%\", align: \'center\',\r\n                      " +
"  formatter: function (value, row) {\r\n                            return \'<a Exc" +
"hange  class=\"easyui-linkbutton\"    onclick=\"Exchange(\' + row.Id + \')\">提资单</a>  " +
"\';\r\n                        }\r\n                    }\r\n                    //,\r\n " +
"                   //  {\r\n                    //      field: \"process\", title: \"" +
"流程进度\", align: \"center\", halign: \"center\", width: 80,\r\n                    //    " +
"  formatter: JQ.Flow.showFlowProgress(\"DesExchGrid\", \"DesExch\", \"Id\")\r\n         " +
"           //  }\r\n                ]],\r\n                queryParams: params,\r\n   " +
"             onLoadSuccess: function (row) {\r\n                    $(\"a[Exchange]" +
"\").linkbutton({ iconCls: \'fa fa-edit\' });\r\n                }\r\n            })\r\n  " +
"          $(\"#JQSearch\").textbox({\r\n                buttonText: \'筛选\',\r\n         " +
"       buttonIcon: \'fa fa-search\',\r\n                height: 25,\r\n               " +
" prompt: \'资料名称、资料内容\',\r\n                onClickButton: function () {\r\n           " +
"        \r\n                    params.KeyText = $(\"#JQSearch\").textbox(\'getValue\'" +
");\r\n                    params.SpecId = JSON.stringify($(\"#SpecialCtl\").combotre" +
"e(\"getValues\"));\r\n                    JQ.datagrid.searchGrid(\r\n                 " +
"       {\r\n                            dgID: \'DesExchGrid\',\r\n                    " +
"        loadingType: \'datagrid\',\r\n                            queryParams: param" +
"s\r\n                        });\r\n                }\r\n            });\r\n\r\n          " +
"  function getProgress(grid, refTable, refID, url) {\r\n                if (!JQ.Fl" +
"ow._progress) {\r\n                    JQ.Flow._progress = {\r\n                    " +
"};\r\n                }\r\n                JQ.Flow._progress[\"$flow\" + grid] = {\r\n  " +
"                  url: url, refTable: refTable, ids: []\r\n                };\r\n   " +
"             return JQ.Flow._progress[\"$flow\" + grid];\r\n            }\r\n\r\n       " +
"     $(\"#SpecId\").combobox({\r\n                prompt: \'下拉选择专业\',\r\n               " +
" valueField: \'id\',\r\n                textField: \'text\',\r\n                url: \'");

            
            #line 134 "..\..\Views\DesExch\IsoExchList.cshtml"
                 Write(Url.Action("treejson", "basedata", new { @area= "Core" }));

            
            #line default
            #line hidden
WriteLiteral("?engName=Special\',\r\n                editable: false,\r\n                onChange: f" +
"unction (newVal, oldVal) {\r\n                    $(\"#DesExchGrid\").datagrid(\"relo" +
"ad\", \'");

            
            #line 137 "..\..\Views\DesExch\IsoExchList.cshtml"
                                                     Write(Url.Action("InHandExchList", "DesExch",new { @area="Design"}));

            
            #line default
            #line hidden
WriteLiteral(@"?SpecId=' + newVal);
                }
            });
        });


        //提资单页面信息
        function Exchange(ExchId) {
            JQ.dialog.dialog({
                title: '提资单信息',
                width: '800',
                height: '650',
                url: '");

            
            #line 149 "..\..\Views\DesExch\IsoExchList.cshtml"
                 Write(Url.Action("IsoExchangeInfo", "DesExch", new { @area = "Design" }));

            
            #line default
            #line hidden
WriteLiteral(@"?Id=' + ExchId
            });
        }

        function ShowAll() {
            if ($(""#showAll"").attr(""attrTootip"") == ""all"") {
                $(""#showAll"").attr(""attrTootip"", ""new"");
                $(""#showAll"").linkbutton({
                    text: ""显示最新""
                });
                params.IsAll = ""all"";
            }
            else {
                $(""#showAll"").attr(""attrTootip"", ""all"");
                $(""#showAll"").linkbutton({
                    text: ""显示全部""
                });
                params.IsAll = ""new"";
            }
            params.KeyText = $(""#JQSearch"").textbox('getValue');
            params.SpecId = JSON.stringify($(""#SpecialCtl"").combotree(""getValues""));
            JQ.datagrid.searchGrid({
                dgID: 'DesExchGrid',
                loadingType: 'datagrid',
                queryParams: params
            });

            ");

WriteLiteral("\r\n\r\n        }\r\n    </script>\r\n");

WriteLiteral("    ");

            
            #line 180 "..\..\Views\DesExch\IsoExchList.cshtml"
Write(RenderPage("~/Areas/Core/Views/Shared/_Init.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("Body_Content", () => {

WriteLiteral("\r\n    <table");

WriteLiteral(" id=\"DesExchGrid\"");

WriteLiteral("></table>\r\n    <div");

WriteLiteral(" id=\"DesExchPanel\"");

WriteLiteral(" jqpanel=\"searchPanel\"");

WriteLiteral(" style=\"padding:5px;height:auto;\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" jqpanel=\"toolbarPanel\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 187 "..\..\Views\DesExch\IsoExchList.cshtml"
       Write(BaseData.getBases(new Params()
    {
        isMult = true,
        controlName = "SpecialCtl",
        isRequired = false,
        engName = "Special",
        queryOptions = "{'Key':'SpecId','Contract':'in','filedType':'Int'}",
        width = "120px",
    }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </span>\r\n        <span>筛选条件：</span>\r\n        <input");

WriteLiteral(" id=\"JQSearch\"");

WriteLiteral(" style=\"width:250px;\"");

WriteLiteral(" />\r\n        ");

WriteLiteral("\r\n        <span");

WriteLiteral(" style=\"margin-left:40px;\"");

WriteLiteral(">\r\n            提资专业：\r\n            ");

WriteLiteral("\r\n\r\n        </span>\r\n        <a");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'fa fa-refresh\'\"");

WriteLiteral(" onclick=\"ShowAll();\"");

WriteLiteral(" id=\"showAll\"");

WriteLiteral(" attrTootip=\"all\"");

WriteLiteral(">显示全部</a>\r\n    </div>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
