#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2017-01-06 15:18:06
#endregion
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace DataModel.Models.Mapping
{
public class ArchProjectFolderMap : EntityTypeConfiguration<ArchProjectFolder>
    {
        public ArchProjectFolderMap()
        {
			this.HasKey(t => new { t.Id}); 
				  
			this.Property(t => t.FolderName).IsRequired().HasMaxLength(100);
	  
			this.Property(t => t.FolderParentID);
	  
			this.Property(t => t.FolderRemark).IsRequired().HasMaxLength(500);
	  
			this.Property(t => t.FolderTemplateId).IsRequired();
	  
			this.Property(t => t.FolderProjectId).IsRequired();
	  
			this.Property(t => t.FolderProjectName).IsRequired().HasMaxLength(200);
	  
			this.Property(t => t.CreationTime).IsRequired();
	  
			this.Property(t => t.CreatorEmpId).IsRequired();
	  
			this.Property(t => t.CreatorEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.CreatorDepID).IsRequired();
	  
			this.Property(t => t.CreatorDepName).IsRequired().HasMaxLength(50);


			 // Table & Column Mappings
			this.ToTable("ArchProjectFolder");
			this.Property(t => t.Id).HasColumnName("Id");
			this.Property(t => t.FolderName).HasColumnName("FolderName");
			this.Property(t => t.FolderParentID).HasColumnName("FolderParentID");
			this.Property(t => t.FolderRemark).HasColumnName("FolderRemark");
			this.Property(t => t.FolderTemplateId).HasColumnName("FolderTemplateId");
			this.Property(t => t.FolderProjectId).HasColumnName("FolderProjectId");
			this.Property(t => t.FolderProjectName).HasColumnName("FolderProjectName");
			this.Property(t => t.CreationTime).HasColumnName("CreationTime");
			this.Property(t => t.CreatorEmpId).HasColumnName("CreatorEmpId");
			this.Property(t => t.CreatorEmpName).HasColumnName("CreatorEmpName");
			this.Property(t => t.CreatorDepID).HasColumnName("CreatorDepID");
			this.Property(t => t.CreatorDepName).HasColumnName("CreatorDepName");
			           
			#region Relationships
			#endregion
        }
    }
}  
