#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2016-09-06 20:09:48
#endregion
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace DataModel.Models.Mapping
{
public class BaseQualificationMap : EntityTypeConfiguration<BaseQualification>
    {
        public BaseQualificationMap()
        {
			this.HasKey(t => new { t.QualificationEmpID,t.QualificationSpecID,t.QualificationValue}); 
				  
			this.Property(t => t.QualificationSpecID).IsRequired();
	  
			this.Property(t => t.QualificationValue).IsRequired();


			 // Table & Column Mappings
			this.ToTable("BaseQualification");
			this.Property(t => t.QualificationEmpID).HasColumnName("QualificationEmpID");
			this.Property(t => t.QualificationSpecID).HasColumnName("QualificationSpecID");
			this.Property(t => t.QualificationValue).HasColumnName("QualificationValue");
			           
			#region Relationships
			this.HasRequired(t => t.FK_BaseQualification_QualificationEmpID).WithMany(t => t.FK_BaseQualification_QualificationEmpID).HasForeignKey(d => d.QualificationEmpID);
			this.HasRequired(t => t.FK_BaseQualification_QualificationSpecID).WithMany(t => t.FK_BaseQualification_QualificationSpecID).HasForeignKey(d => d.QualificationSpecID);
			this.HasRequired(t => t.FK_BaseQualification_QualificationValue).WithMany(t => t.FK_BaseQualification_QualificationValue).HasForeignKey(d => d.QualificationValue);
			#endregion
        }
    }
}  
