#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2016-09-06 20:09:48
#endregion
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace DataModel.Models.Mapping
{
public class BussBiddingInfoPackageMap : EntityTypeConfiguration<BussBiddingInfoPackage>
    {
        public BussBiddingInfoPackageMap()
        {
			this.HasKey(t => new { t.Id}); 
				  
			this.Property(t => t.BussBiddingInfoID).IsRequired();
	  
			this.Property(t => t.PackageNumber).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.BiddingProgress).IsRequired();
	  
			this.Property(t => t.WinTime).IsRequired();


			 // Table & Column Mappings
			this.ToTable("BussBiddingInfoPackage");
			this.Property(t => t.Id).HasColumnName("Id");
			this.Property(t => t.BussBiddingInfoID).HasColumnName("BussBiddingInfoID");
			this.Property(t => t.PackageNumber).HasColumnName("PackageNumber");
			this.Property(t => t.BiddingProgress).HasColumnName("BiddingProgress");
			this.Property(t => t.WinTime).HasColumnName("WinTime");
			           
			#region Relationships
			this.HasRequired(t => t.FK_BussBiddingInfoPackage_BiddingProgress).WithMany(t => t.FK_BussBiddingInfoPackage_BiddingProgress).HasForeignKey(d => d.BiddingProgress);
			this.HasRequired(t => t.FK_BussBiddingInfoPackage_BussBiddingInfoID).WithMany(t => t.FK_BussBiddingInfoPackage_BussBiddingInfoID).HasForeignKey(d => d.BussBiddingInfoID);
			#endregion
        }
    }
}  
