#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2016-09-12 11:45:53
#endregion
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace DataModel.Models.Mapping
{
public class DesTaskFeeDetailsMap : EntityTypeConfiguration<DesTaskFeeDetails>
    {
        public DesTaskFeeDetailsMap()
        {
			this.HasKey(t => new { t.Id}); 
				  
			this.Property(t => t.ProjId).IsRequired();
	  
			this.Property(t => t.TaskGroupId).IsRequired();
	  
			this.Property(t => t.PhaseID).IsRequired();
	  
			this.Property(t => t.TaskID).IsRequired();
	  
			this.Property(t => t.FeeZBF).IsRequired().HasPrecision(18,2);
	  
			this.Property(t => t.FeeXMQQF).IsRequired().HasPrecision(18,2);
	  
			this.Property(t => t.FeeKCF).IsRequired().HasPrecision(18,2);
	  
			this.Property(t => t.FeeSJF).IsRequired().HasPrecision(18,2);
	  
			this.Property(t => t.FeeYSBZF).IsRequired().HasPrecision(18,2);
	  
			this.Property(t => t.FeeJGTBZF).IsRequired().HasPrecision(18,2);
	  
			this.Property(t => t.FeeZTZ).IsRequired().HasPrecision(18,2);
	  
			this.Property(t => t.CreationTime).IsRequired();
	  
			this.Property(t => t.CreatorEmpId).IsRequired();
	  
			this.Property(t => t.CreatorEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.CreatorDepId).IsRequired();
	  
			this.Property(t => t.CreatorDepName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.LastModificationTime).IsRequired();
	  
			this.Property(t => t.LastModifierEmpId).IsRequired();
	  
			this.Property(t => t.LastModifierEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.DeleterEmpId).IsRequired();
	  
			this.Property(t => t.DeleterEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.DeletionTime).IsRequired();
	  
			this.Property(t => t.AgenEmpId).IsRequired();
	  
			this.Property(t => t.AgenEmpName).IsRequired().HasMaxLength(50);


			 // Table & Column Mappings
			this.ToTable("DesTaskFeeDetails");
			this.Property(t => t.Id).HasColumnName("Id");
			this.Property(t => t.ProjId).HasColumnName("ProjId");
			this.Property(t => t.TaskGroupId).HasColumnName("TaskGroupId");
			this.Property(t => t.PhaseID).HasColumnName("PhaseID");
			this.Property(t => t.TaskID).HasColumnName("TaskID");
			this.Property(t => t.FeeZBF).HasColumnName("FeeZBF");
			this.Property(t => t.FeeXMQQF).HasColumnName("FeeXMQQF");
			this.Property(t => t.FeeKCF).HasColumnName("FeeKCF");
			this.Property(t => t.FeeSJF).HasColumnName("FeeSJF");
			this.Property(t => t.FeeYSBZF).HasColumnName("FeeYSBZF");
			this.Property(t => t.FeeJGTBZF).HasColumnName("FeeJGTBZF");
			this.Property(t => t.FeeZTZ).HasColumnName("FeeZTZ");
			this.Property(t => t.CreationTime).HasColumnName("CreationTime");
			this.Property(t => t.CreatorEmpId).HasColumnName("CreatorEmpId");
			this.Property(t => t.CreatorEmpName).HasColumnName("CreatorEmpName");
			this.Property(t => t.CreatorDepId).HasColumnName("CreatorDepId");
			this.Property(t => t.CreatorDepName).HasColumnName("CreatorDepName");
			this.Property(t => t.LastModificationTime).HasColumnName("LastModificationTime");
			this.Property(t => t.LastModifierEmpId).HasColumnName("LastModifierEmpId");
			this.Property(t => t.LastModifierEmpName).HasColumnName("LastModifierEmpName");
			this.Property(t => t.DeleterEmpId).HasColumnName("DeleterEmpId");
			this.Property(t => t.DeleterEmpName).HasColumnName("DeleterEmpName");
			this.Property(t => t.DeletionTime).HasColumnName("DeletionTime");
			this.Property(t => t.AgenEmpId).HasColumnName("AgenEmpId");
			this.Property(t => t.AgenEmpName).HasColumnName("AgenEmpName");
			           
			#region Relationships
			#endregion
        }
    }
}  
