#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2017-01-16 15:24:34
#endregion
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace DataModel.Models.Mapping
{
public class HRAchievementMap : EntityTypeConfiguration<HRAchievement>
    {
        public HRAchievementMap()
        {
			this.HasKey(t => new { t.Id}); 
				  
			this.Property(t => t.CreationTime).IsRequired();
	  
			this.Property(t => t.CreatorEmpId).IsRequired();
	  
			this.Property(t => t.CreatorEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.CreatorDepId).IsRequired();
	  
			this.Property(t => t.CreatorDepName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.DeleterEmpId).IsRequired();
	  
			this.Property(t => t.DeleterEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.DeletionTime).IsRequired();
	  
			this.Property(t => t.EmpID).IsRequired();
	  
			this.Property(t => t.AchievementDate).IsRequired();
	  
			this.Property(t => t.AchievementNatureID).IsRequired();
	  
			this.Property(t => t.AchievementLevelID).IsRequired();
	  
			this.Property(t => t.Content).IsRequired().HasMaxLength(500);


			 // Table & Column Mappings
			this.ToTable("HRAchievement");
			this.Property(t => t.Id).HasColumnName("Id");
			this.Property(t => t.CreationTime).HasColumnName("CreationTime");
			this.Property(t => t.CreatorEmpId).HasColumnName("CreatorEmpId");
			this.Property(t => t.CreatorEmpName).HasColumnName("CreatorEmpName");
			this.Property(t => t.CreatorDepId).HasColumnName("CreatorDepId");
			this.Property(t => t.CreatorDepName).HasColumnName("CreatorDepName");
			this.Property(t => t.DeleterEmpId).HasColumnName("DeleterEmpId");
			this.Property(t => t.DeleterEmpName).HasColumnName("DeleterEmpName");
			this.Property(t => t.DeletionTime).HasColumnName("DeletionTime");
			this.Property(t => t.EmpID).HasColumnName("EmpID");
			this.Property(t => t.AchievementDate).HasColumnName("AchievementDate");
			this.Property(t => t.AchievementNatureID).HasColumnName("AchievementNatureID");
			this.Property(t => t.AchievementLevelID).HasColumnName("AchievementLevelID");
			this.Property(t => t.Content).HasColumnName("Content");
			           
			#region Relationships
			#endregion
        }
    }
}  
