#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2017-04-20 09:23:17
#endregion
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace DataModel.Models.Mapping
{
public class IsoConstructionCoordinationMap : EntityTypeConfiguration<IsoConstructionCoordination>
    {
        public IsoConstructionCoordinationMap()
        {
			this.HasKey(t => new { t.Id});

            this.Property(t => t.TableNumber).IsRequired().HasMaxLength(50);

            this.Property(t => t.Number).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.ProjId).IsRequired();
	  
			this.Property(t => t.ProjNumber).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.ProjName).IsRequired().HasMaxLength(100);

            this.Property(t => t.ProjPhaseId).IsRequired().HasMaxLength(50);

            this.Property(t => t.ProjPhaseName).IsRequired().HasMaxLength(100);

            this.Property(t => t.Specialty).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.Wather).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.ConstructCompany).IsRequired().HasMaxLength(200);
	  
			this.Property(t => t.CoordinationIds).IsRequired().HasMaxLength(500);
	  
			this.Property(t => t.CoordinationType).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.CoordinationValue).IsRequired().HasMaxLength(2000);
	  
			this.Property(t => t.DesignChange).IsRequired().HasMaxLength(200);
	  
			this.Property(t => t.Problem).IsRequired().HasMaxLength(2000);
	  
			this.Property(t => t.Attachment).IsRequired().HasMaxLength(2000);
	  
			this.Property(t => t.DeletionTime).IsRequired();
	  
			this.Property(t => t.CreationTime).IsRequired();
	  
			this.Property(t => t.CreatorEmpId).IsRequired();
	  
			this.Property(t => t.CreatorEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.CreatorDepId).IsRequired();
	  
			this.Property(t => t.CreatorDepName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.LastModificationTime).IsRequired();
	  
			this.Property(t => t.LastModifierEmpId).IsRequired();
	  
			this.Property(t => t.LastModifierEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.AgenCreatorEmpId).IsRequired();
	  
			this.Property(t => t.AgenCreatorEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.AgenLastModifierEmpId).IsRequired();
	  
			this.Property(t => t.AgenLastModifierEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.AgenDeleterEmpId).IsRequired();
	  
			this.Property(t => t.AgenDeleterEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.DeleterEmpId).IsRequired();
	  
			this.Property(t => t.DeleterEmpName).IsRequired().HasMaxLength(50);

			this.Property(t => t.CoordinationDate).IsRequired();


            // Table & Column Mappings
            this.ToTable("IsoConstructionCoordination");
			this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.TableNumber).HasColumnName("TableNumber");
            this.Property(t => t.Number).HasColumnName("Number");
			this.Property(t => t.ProjId).HasColumnName("ProjId");
			this.Property(t => t.ProjNumber).HasColumnName("ProjNumber");
			this.Property(t => t.ProjName).HasColumnName("ProjName");
            this.Property(t => t.ProjPhaseId).HasColumnName("ProjPhaseId");
            this.Property(t => t.ProjPhaseName).HasColumnName("ProjPhaseName");
            this.Property(t => t.Specialty).HasColumnName("Specialty");
			this.Property(t => t.Wather).HasColumnName("Wather");
			this.Property(t => t.ConstructCompany).HasColumnName("ConstructCompany");
			this.Property(t => t.CoordinationIds).HasColumnName("CoordinationIds");
			this.Property(t => t.CoordinationType).HasColumnName("CoordinationType");
			this.Property(t => t.CoordinationValue).HasColumnName("CoordinationValue");
			this.Property(t => t.DesignChange).HasColumnName("DesignChange");
			this.Property(t => t.Problem).HasColumnName("Problem");
			this.Property(t => t.Attachment).HasColumnName("Attachment");
			this.Property(t => t.DeletionTime).HasColumnName("DeletionTime");
			this.Property(t => t.CreationTime).HasColumnName("CreationTime");
			this.Property(t => t.CreatorEmpId).HasColumnName("CreatorEmpId");
			this.Property(t => t.CreatorEmpName).HasColumnName("CreatorEmpName");
			this.Property(t => t.CreatorDepId).HasColumnName("CreatorDepId");
			this.Property(t => t.CreatorDepName).HasColumnName("CreatorDepName");
			this.Property(t => t.LastModificationTime).HasColumnName("LastModificationTime");
			this.Property(t => t.LastModifierEmpId).HasColumnName("LastModifierEmpId");
			this.Property(t => t.LastModifierEmpName).HasColumnName("LastModifierEmpName");
			this.Property(t => t.AgenCreatorEmpId).HasColumnName("AgenCreatorEmpId");
			this.Property(t => t.AgenCreatorEmpName).HasColumnName("AgenCreatorEmpName");
			this.Property(t => t.AgenLastModifierEmpId).HasColumnName("AgenLastModifierEmpId");
			this.Property(t => t.AgenLastModifierEmpName).HasColumnName("AgenLastModifierEmpName");
			this.Property(t => t.AgenDeleterEmpId).HasColumnName("AgenDeleterEmpId");
			this.Property(t => t.AgenDeleterEmpName).HasColumnName("AgenDeleterEmpName");
			this.Property(t => t.DeleterEmpId).HasColumnName("DeleterEmpId");
			this.Property(t => t.DeleterEmpName).HasColumnName("DeleterEmpName");
			this.Property(t => t.CoordinationDate).HasColumnName("CoordinationDate");
			           
			#region Relationships
			#endregion
        }
    }
}  
