#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2017-04-17 20:07:14
#endregion
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace DataModel.Models.Mapping
{
public class IsoSJJSDMap : EntityTypeConfiguration<IsoSJJSD>
    {
        public IsoSJJSDMap()
        {
			this.HasKey(t => new { t.Id}); 
				  
			this.Property(t => t.TableNumber).HasMaxLength(50);
	  
			this.Property(t => t.Number).HasMaxLength(50);
	  
			this.Property(t => t.ProjID).IsRequired();
	  
			this.Property(t => t.ProjNumber).HasMaxLength(50);
	  
			this.Property(t => t.ProjName).HasMaxLength(50);
	  
			this.Property(t => t.ProjPhaseId).HasMaxLength(50);
	  
			this.Property(t => t.ProjPhaseName).HasMaxLength(100);
	  
			this.Property(t => t.SpecId).HasMaxLength(50);
	  
			this.Property(t => t.SpecName).HasMaxLength(100);
	  
			this.Property(t => t.CreationTime).IsRequired();
	  
			this.Property(t => t.CreatorEmpId).IsRequired();
	  
			this.Property(t => t.CreatorEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.CreatorDepID).IsRequired();
	  
			this.Property(t => t.CreatorDepName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.LastModificationTime).IsRequired();
	  
			this.Property(t => t.LastModifierEmpId).IsRequired();
	  
			this.Property(t => t.LastModifierEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.DeleterEmpId).IsRequired();
	  
			this.Property(t => t.DeleterEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.DeletionTime).IsRequired();
	  
			this.Property(t => t.AgenCreatorEmpId).IsRequired();
	  
			this.Property(t => t.AgenCreatorEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.AgenLastModifierEmpId).IsRequired();
	  
			this.Property(t => t.AgenLastModifierEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.AgenDeleterEmpId).IsRequired();
	  
			this.Property(t => t.AgenDeleterEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.ManageLevel).IsRequired();
	  
			this.Property(t => t.SSTime).IsRequired();
	  
			this.Property(t => t.JSNR).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.JSWJ).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.SJEmpId).IsRequired();
	  
			this.Property(t => t.SJEmpName).IsRequired().HasMaxLength(50);
	  
			this.Property(t => t.JSNote).IsRequired().HasMaxLength(1000);
	  
			this.Property(t => t.ModifyNote).IsRequired().HasMaxLength(500);

            this.Property(t => t.CheckFileID).IsRequired().HasMaxLength(50);

            this.Property(t => t.CheckFlow).IsRequired().HasMaxLength(5000);



            // Table & Column Mappings
            this.ToTable("IsoSJJSD");
			this.Property(t => t.Id).HasColumnName("Id");
			this.Property(t => t.TableNumber).HasColumnName("TableNumber");
			this.Property(t => t.Number).HasColumnName("Number");
			this.Property(t => t.ProjID).HasColumnName("ProjID");
			this.Property(t => t.ProjNumber).HasColumnName("ProjNumber");
			this.Property(t => t.ProjName).HasColumnName("ProjName");
			this.Property(t => t.ProjPhaseId).HasColumnName("ProjPhaseId");
			this.Property(t => t.ProjPhaseName).HasColumnName("ProjPhaseName");
			this.Property(t => t.SpecId).HasColumnName("SpecId");
			this.Property(t => t.SpecName).HasColumnName("SpecName");
			this.Property(t => t.CreationTime).HasColumnName("CreationTime");
			this.Property(t => t.CreatorEmpId).HasColumnName("CreatorEmpId");
			this.Property(t => t.CreatorEmpName).HasColumnName("CreatorEmpName");
			this.Property(t => t.CreatorDepID).HasColumnName("CreatorDepID");
			this.Property(t => t.CreatorDepName).HasColumnName("CreatorDepName");
			this.Property(t => t.LastModificationTime).HasColumnName("LastModificationTime");
			this.Property(t => t.LastModifierEmpId).HasColumnName("LastModifierEmpId");
			this.Property(t => t.LastModifierEmpName).HasColumnName("LastModifierEmpName");
			this.Property(t => t.DeleterEmpId).HasColumnName("DeleterEmpId");
			this.Property(t => t.DeleterEmpName).HasColumnName("DeleterEmpName");
			this.Property(t => t.DeletionTime).HasColumnName("DeletionTime");
			this.Property(t => t.AgenCreatorEmpId).HasColumnName("AgenCreatorEmpId");
			this.Property(t => t.AgenCreatorEmpName).HasColumnName("AgenCreatorEmpName");
			this.Property(t => t.AgenLastModifierEmpId).HasColumnName("AgenLastModifierEmpId");
			this.Property(t => t.AgenLastModifierEmpName).HasColumnName("AgenLastModifierEmpName");
			this.Property(t => t.AgenDeleterEmpId).HasColumnName("AgenDeleterEmpId");
			this.Property(t => t.AgenDeleterEmpName).HasColumnName("AgenDeleterEmpName");
			this.Property(t => t.ManageLevel).HasColumnName("ManageLevel");
			this.Property(t => t.SSTime).HasColumnName("SSTime");
			this.Property(t => t.JSNR).HasColumnName("JSNR");
			this.Property(t => t.JSWJ).HasColumnName("JSWJ");
			this.Property(t => t.SJEmpId).HasColumnName("SJEmpId");
			this.Property(t => t.SJEmpName).HasColumnName("SJEmpName");
			this.Property(t => t.JSNote).HasColumnName("JSNote");
			this.Property(t => t.ModifyNote).HasColumnName("ModifyNote");
            this.Property(t => t.CheckFileID).HasColumnName("CheckFileID");
            this.Property(t => t.CheckFlow).HasColumnName("CheckFlow");

            #region Relationships
            #endregion
        }
    }
}  
