#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2017-03-04 08:47:45
#endregion
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
namespace DataModel.Models.Mapping
{
public class SSManageMap : EntityTypeConfiguration<SSManage>
    {
        public SSManageMap()
        {
			this.HasKey(t => new { t.Id,t.EngineeringID,t.IsSSFA,t.IsNS,t.IsWS,t.Address,t.Level}); 
			  
			this.Property(t => t.Id);
	  
			this.Property(t => t.EngineeringID);
	  
			this.Property(t => t.IsSSFA);
	  
			this.Property(t => t.IsNS);
	  
			this.Property(t => t.IsWS);
	  
			this.Property(t => t.Address).HasMaxLength(50);
	  
			this.Property(t => t.Level);

            this.Property(t => t.EmpManageId).IsRequired();

            // Table & Column Mappings
            this.ToTable("SSManage");
			this.Property(t => t.Id).HasColumnName("Id");
			this.Property(t => t.EngineeringID).HasColumnName("EngineeringID");
			this.Property(t => t.IsSSFA).HasColumnName("IsSSFA");
			this.Property(t => t.IsNS).HasColumnName("IsNS");
			this.Property(t => t.IsWS).HasColumnName("IsWS");
			this.Property(t => t.Address).HasColumnName("Address");
			this.Property(t => t.Level).HasColumnName("Level");
			this.Property(t => t.EmpManageId).HasColumnName("EmpManageId");

            #region Relationships
            #endregion
        }
    }
}  
