#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\role\info.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/role/info.cshtml")]
    public partial class _Views_role_info_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_role_info_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\role\info.cshtml"
  
    Layout = "~/Areas/Core/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n        #treeempdiv .datagrid-header {\r\n            position: absolute;\r\n     " +
"       visibility: hidden;\r\n        }\r\n    </style>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 271), Tuple.Create("\"", 305)
, Tuple.Create(Tuple.Create("", 277), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/datagrid-filter.js")
, 277), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        $(function () {\r\n            //debugger;\r\n            $(\'#lefttreerole" +
"\').treegrid({\r\n                url: \'");

            
            #line 18 "..\..\Views\role\info.cshtml"
                 Write(Url.Action("treejson", "basedata",new { @area="Core", engName ="role"}));

            
            #line default
            #line hidden
WriteLiteral(@"',
                idField: 'id',
                treeField: 'text',
                border: 0,
                fit: true,
                animate: true,
                singleSelect: true,
                columns: [[
                   { title: '<b>选择角色</b>', field: 'text', width: 240, align: 'left' }
                ]],
                onLoadSuccess: function (row, data) {

                },
                onSelect: function (node) {
                    $('#menulist').treegrid('load', {
                        MenuID: $(""#MenuCombox"").combobox('getValue'),
                        RoleID: node.id
                    });
                    //设置文本
                    $('#PermitTitle').html(""<b>设置权限：</b>"" + node.text);
                    $('#PermitTitle').attr({ ""RoleID"": node.id, ""EmpID"": 0 });
                }
            });
            //debugger;
            $('#lefttreeemp').treegrid({
                url: '");

            
            #line 43 "..\..\Views\role\info.cshtml"
                 Write(Url.Action("employeeByDepJson", "usercontrol", new { @area = "Core", state = "closed" }));

            
            #line default
            #line hidden
WriteLiteral(@"',
                idField: 'id',
                treeField: 'text',
                border: 0,
                fit: true,
                animate: true,
                singleSelect: true,
                columns: [[
                   { title: '', field: 'text', width: 240, align: 'left' }
                ]],
                onLoadSuccess: function (row, data) {
                    //debugger;
                },
                onSelect: function (node) {
                    if (node.isEmp) {
                        $('#menulist').treegrid('load', {
                            MenuID: $(""#MenuCombox"").combobox('getValue'),
                            EmpID: node.empid
                        });
                        //设置文本
                        $('#PermitTitle').html(""<b>设置人员</b>："" + node.text);
                        $('#PermitTitle').attr({ ""RoleID"": 0, ""EmpID"": node.empid });
                    }
                }
            });

            $('#MenuCombox').combobox({
                url: '");

            
            #line 70 "..\..\Views\role\info.cshtml"
                 Write(Url.Action("PermitTopjson", "menu", new { @area = "Core"}));

            
            #line default
            #line hidden
WriteLiteral(@"',
                valueField: 'MenuID',
                textField: 'MenuName',
                panelHeight: ""auto"",
                editable: false, //不允许手动输入
                onLoadSuccess: function () { //数据加载完毕事件
                    var data = $('#MenuCombox').combobox('getData');
                    if (data.length > 0) {
                        $(""#MenuCombox"").combobox('select', data[0].MenuID);
                    }
                },
                onSelect: function (node) {
                    $('#menulist').treegrid('reload');
                    $('#menulist').treegrid('load', {
                        MenuID: $(""#MenuCombox"").combobox('getValue'),
                        EmpID: $('#PermitTitle').attr(""EmpID""),
                        RoleID: $('#PermitTitle').attr(""RoleID"")
                    });
                }
            });

            JQ.treegrid.treegrid({
                JQPrimaryID: 'id',
                JQID: 'menulist',
                JQDialogTitle: '菜单信息',
                JQWidth: '100%',
                JQHeight: '100%',
                JQLoadingType: 'treegrid',
                url: '");

            
            #line 98 "..\..\Views\role\info.cshtml"
                 Write(Url.Action("Permitjson", "menu",new {@area="Core" }));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                toolbar: \'#tbMenu\',\r\n                JQExcludeCol: [6, 7],\r\n " +
"               animate: true,\r\n                checkOnSelect: false, selectOnChe" +
"ck: false,\r\n\r\n                columns: [[\r\n                    { title: \'全选\' },\r" +
"\n                    { field: \'opt1\', title: \'<input id=\\\"add\\\"  type=\\\"checkbox" +
"\\\" onclick=\\\"CheckAll(\\\'add\\\')\\\" >\' },\r\n                    { field: \'opt2\', tit" +
"le: \'<input id=\\\"edit\\\" type=\\\"checkbox\\\" onclick=\\\"CheckAll(\\\'edit\\\')\\\" >\' },\r\n" +
"                    { field: \'opt3\', title: \'<input id=\\\"del\\\" type=\\\"checkbox\\\"" +
"  onclick=\\\"CheckAll(\\\'del\\\')\\\" >\' },\r\n                    { field: \'opt4\', titl" +
"e: \'<input id=\\\"export\\\" type=\\\"checkbox\\\" onclick=\\\"CheckAll(\\\'export\\\')\\\" >\' }" +
",\r\n                    { field: \'opt5\', title: \'<input id=\\\"emp\\\" type=\\\"checkbo" +
"x\\\"  onclick=\\\"CheckAll(\\\'emp\\\')\\\" >\' },\r\n                    { field: \'opt6\', t" +
"itle: \'<input id=\\\"dep\\\" type=\\\"checkbox\\\" onclick=\\\"CheckAll(\\\'dep\\\')\\\" >\' },\r\n" +
"                    { field: \'opt7\', title: \'<input id=\\\"allview\\\" type=\\\"checkb" +
"ox\\\" onclick=\\\"CheckAll(\\\'allview\\\')\\\" >\' },\r\n                    { field: \'opt8" +
"\', title: \'<input id=\\\"alledit\\\" type=\\\"checkbox\\\" onclick=\\\"CheckAll(\\\'alledit\\" +
"\')\\\" >\' },\r\n                     { field: \'opt9\', title: \'<input id=\\\"allDown\\\" " +
"type=\\\"checkbox\\\" onclick=\\\"CheckAll(\\\'allDown\\\')\\\" >\' }\r\n                ],\r\n  " +
"              [\r\n                   { title: \'菜单名称\', field: \'text\', width: 250, " +
"align: \'left\' },\r\n                   {\r\n                       title: \'新增\', fiel" +
"d: \'add\', align: \'center\', JQIsExclude: true, formatter: function (value, row, i" +
"ndex) {\r\n                           return value == \"NoPermit\" ? \"\" : \"<input ty" +
"pe=\'checkbox\' name=\'add\' value=\'1\' \" + row.add + \" MenuID=\'\" + row.id + \"\' />\";\r" +
"\n                       }\r\n                   },\r\n                   {\r\n        " +
"               title: \'修改\', field: \'edit\', align: \'center\', JQIsExclude: true, f" +
"ormatter: function (value, row, index) {\r\n\r\n                           return va" +
"lue == \"NoPermit\" ? \"\" : \"<input type=\'checkbox\' name=\'edit\' value=\'2\' \" + row.e" +
"dit + \" MenuID=\'\" + row.id + \"\'/>\";\r\n                       }\r\n                 " +
"  },\r\n                   {\r\n                       title: \'删除\', field: \'del\', al" +
"ign: \'center\', JQIsExclude: true, formatter: function (value, row, index) {\r\n   " +
"                        return value == \"NoPermit\" ? \"\" : \"<input type=\'checkbox" +
"\' name=\'del\' value=\'4\' \" + row.del + \" MenuID=\'\" + row.id + \"\'/>\";\r\n            " +
"           }\r\n                   },\r\n                   {\r\n                     " +
"  title: \'导出\', field: \'export\', align: \'center\', JQIsExclude: true, formatter: f" +
"unction (value, row, index) {\r\n                           return value == \"NoPer" +
"mit\" ? \"\" : \"<input type=\'checkbox\' name=\'export\' value=\'8\' \" + row.export + \" M" +
"enuID=\'\" + row.id + \"\'/>\";\r\n                       }\r\n                   },\r\n   " +
"                {\r\n                       title: \'个人\', field: \'emp\', align: \'cen" +
"ter\', JQIsExclude: true, formatter: function (value, row, index) {\r\n            " +
"               return value == \"NoPermit\" ? \"\" : \"<input type=\'checkbox\' name=\'e" +
"mp\'  value=\'16\' \" + row.emp + \" MenuID=\'\" + row.id + \"\'/>\";\r\n                   " +
"    }\r\n                   },\r\n                   {\r\n                       title" +
": \'部门\', field: \'dep\', align: \'center\', JQIsExclude: true, formatter: function (v" +
"alue, row, index) {\r\n                           return value == \"NoPermit\" ? \"\" " +
": \"<input type=\'checkbox\' name=\'dep\' value=\'32\'  \" + row.dep + \" MenuID=\'\" + row" +
".id + \"\'/>\";\r\n                       }\r\n                   },\r\n                 " +
"  {\r\n                       title: \'全部\', field: \'allview\', align: \'center\', JQIs" +
"Exclude: true, formatter: function (value, row, index) {\r\n                      " +
"     return value == \"NoPermit\" ? \"\" : \"<input type=\'checkbox\' name=\'allview\'  v" +
"alue=\'64\' \" + row.allview + \" MenuID=\'\" + row.id + \"\'/>\";\r\n                     " +
"  }\r\n                   },\r\n                   {\r\n                       title: " +
"\'维护\', field: \'alledit\', align: \'center\', JQIsExclude: true, formatter: function " +
"(value, row, index) {\r\n                           return value == \"NoPermit\" ? \"" +
"\" : \"<input type=\'checkbox\' name=\'alledit\'  value=\'128\' \" + row.alledit + \" Menu" +
"ID=\'\" + row.id + \"\'/>\";\r\n                       }\r\n                   },\r\n      " +
"             {\r\n                       title: \'下载\', field: \'allDown\', align: \'ce" +
"nter\', JQIsExclude: true, formatter: function (value, row, index) {\r\n           " +
"                return value == \"NoPermit\" ? \"\" : \"<input type=\'checkbox\' name=\'" +
"allDown\'  value=\'256\' \" + row.allDown + \" MenuID=\'\" + row.id + \"\'/>\";\r\n         " +
"              }\r\n                   },\r\n                ]],\r\n                onL" +
"oadSuccess: function () {\r\n                    $(\"#add\").unbind();\r\n            " +
"        $(\"#edit\").unbind();\r\n                    $(\"#del\").unbind();\r\n         " +
"           $(\"#export\").unbind();\r\n                    $(\"#emp\").unbind();\r\n    " +
"                $(\"#dep\").unbind();\r\n                    $(\"#allview\").unbind();" +
"\r\n                    $(\"#alledit\").unbind();\r\n                    $(\"#allDown\")" +
".unbind();\r\n\r\n                },\r\n                queryParams: {\r\n              " +
"      MenuID: 0,\r\n                    RoleID: 0,\r\n                    EmpID: 0\r\n" +
"                }\r\n            });\r\n        });\r\n\r\n        function saveMenu() {" +
"\r\n            debugger;\r\n            var checkedItems = $(\'#menulist\').treegrid(" +
"\'getChecked\');\r\n            var list = [];\r\n            $.each(checkedItems, fun" +
"ction (index, item) {\r\n                if (item.attr(\"MenuID\") != undefined)\r\n  " +
"                  list.push({ MenuID: item.attr(\"MenuID\"), MenuPermissions: item" +
".attr(\"value\") });\r\n            });\r\n            var MenuID = $(\"#MenuCombox\").c" +
"ombobox(\'getValue\');\r\n            var url = \'");

            
            #line 194 "..\..\Views\role\info.cshtml"
                  Write(Url.Action("SavePermit", "menu",new { @area="Core"}));

            
            #line default
            #line hidden
WriteLiteral("?RoleID=\' + $(\'#PermitTitle\').attr(\"RoleID\") + \"&EmpID=\" + $(\'#PermitTitle\').attr" +
"(\"EmpID\") + \"&MenuID=\" + MenuID;\r\n\r\n            $.ajax({\r\n                url: u" +
"rl,\r\n                data: {\r\n                    \'list\': JSON.stringify(list)\r\n" +
"                },\r\n                type: \'POST\',\r\n                dataType: \'js" +
"on\',\r\n                success: function (result) {\r\n                    JQ.dialo" +
"g.info(\"保存成功！\");\r\n                }\r\n            });\r\n        }\r\n\r\n\r\n        $.e" +
"xtend($.fn.datagrid.methods, {\r\n            getChecked: function (jq) {\r\n       " +
"         var rr = [];\r\n                var rows = jq.datagrid(\'getRows\');\r\n     " +
"           jq.datagrid(\'getPanel\').find(\'div.datagrid-cell input:checked\').each(" +
"function () {\r\n                    rr.push($(this));\r\n                });\r\n     " +
"           return rr;\r\n            }\r\n        });\r\n\r\n        function removeChec" +
"ked(nodes) {\r\n            if (JQ.tools.isArray(nodes)) {\r\n                var $t" +
" = $(\'#roleLeftTree\');\r\n                for (var i = 0; i < nodes.length; i++) {" +
"\r\n                    $t.tree(\'uncheck\', nodes[i].target);\r\n                }\r\n " +
"           }\r\n        }\r\n\r\n        function CheckAll(id) {\r\n            if ($(\'#" +
"\' + id).attr(\'checked\') == \'checked\') {\r\n                $(\"input[name=\'\" + id +" +
" \"\']\").attr(\"checked\", \'checked\');\r\n            } else {\r\n                $(\"inp" +
"ut[name=\'\" + id + \"\']\").removeAttr(\"checked\");\r\n            }\r\n            retur" +
"n false;\r\n        }\r\n\r\n        //人员查询事件\r\n        function SeachEpmList() {\r\n    " +
"        var keys = $(\"input[name=searchtxt]\").val();\r\n            var urls = \'");

            
            #line 242 "..\..\Views\role\info.cshtml"
                   Write(Url.Action("employeeByDepJson_Search", "usercontrol", new { @area = "Core"}));

            
            #line default
            #line hidden
WriteLiteral("\' + \'?keys=\' + keys;\r\n            $.get(urls, {}, function (ret) {\r\n             " +
"   $(\'#lefttreeemp\').treegrid(\"loadData\", ret);\r\n            }, \"json\");\r\n      " +
"  }\r\n    </script>\r\n");

});

WriteLiteral("\r\n");

DefineSection("Body_Content", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" id=\"cc\"");

WriteLiteral(" class=\"easyui-layout\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(" fit=\"true\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" data-options=\"region:\'west\',split:false\"");

WriteLiteral(" style=\"width:250px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"tt\"");

WriteLiteral(" class=\"easyui-tabs\"");

WriteLiteral(" data-options=\"fit:true\"");

WriteLiteral(" style=\"width:300px;height:100%;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" title=\"按角色\"");

WriteLiteral(" style=\"padding:2px;\"");

WriteLiteral(">\r\n                    <table");

WriteLiteral(" id=\"lefttreerole\"");

WriteLiteral("></table>\r\n                </div>\r\n                <div");

WriteLiteral(" title=\"按人员\"");

WriteLiteral(" data-options=\"closable:false\"");

WriteLiteral(" style=\"padding:2px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"easyui-layout\"");

WriteLiteral(" fit=\"true\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" data-options=\"region:\'north\'\"");

WriteLiteral(" style=\"height:30px\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" name=\"searchtxt\"");

WriteLiteral(" class=\"easyui-searchbox\"");

WriteLiteral(" data-options=\"prompt:\'输入姓名\',searcher:SeachEpmList\"");

WriteLiteral(" style=\"width:240px\"");

WriteLiteral(">\r\n                        </div>\r\n                        <div");

WriteLiteral(" data-options=\"region:\'center\'\"");

WriteLiteral(" id=\"treeempdiv\"");

WriteLiteral(">\r\n                            <table");

WriteLiteral(" id=\"lefttreeemp\"");

WriteLiteral("></table>\r\n                        </div>\r\n                    </div>\r\n          " +
"      </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" data-options=\"region:\'center\'\"");

WriteLiteral(" style=\"background:#eee;\"");

WriteLiteral(">\r\n            <table");

WriteLiteral(" id=\"menulist\"");

WriteLiteral("> </table>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"tbMenu\"");

WriteLiteral(" style=\"padding:5px;height:auto;\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" id=\"PermitTitle\"");

WriteLiteral(">设置：</span>\r\n            <select");

WriteLiteral(" id=\"MenuCombox\"");

WriteLiteral(" name=\"MenuCombox\"");

WriteLiteral(" style=\"width:100px;height:28px;\"");

WriteLiteral(" data-options=\"editable: false\"");

WriteLiteral("></select>\r\n            <a");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'fa fa-save\'\"");

WriteLiteral(" onclick=\"saveMenu()\"");

WriteLiteral(">保存权限</a>\r\n        </div>\r\n    </div>\r\n");

});

        }
    }
}
#pragma warning restore 1591
