#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/OaNew/Editor.cshtml")]
    public partial class _Views_OaNew_Editor_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_OaNew_Editor_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\OaNew\Editor.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n<html>\r\n<head>\r\n</head>\r\n<body>\r\n    <textarea");

WriteLiteral(" id=\"txtContent\"");

WriteLiteral(" name=\"txtContent\"");

WriteLiteral(" style=\"width:100%;height:300px;\"");

WriteLiteral(" validType=\"length[0,2000]\"");

WriteLiteral(" data-options=\"multiline:true\"");

WriteLiteral("></textarea>\r\n</body>\r\n</html>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    document.body.style.overflow = \"hidden\";\r\n    window.UEDITOR_HOME_URL = \"");

            
            #line 13 "..\..\Views\OaNew\Editor.cshtml"
                           Write(ViewBag.sitePath);

            
            #line default
            #line hidden
WriteLiteral("Scripts/ueditor/\";\r\n</script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 419), Tuple.Create("\"", 478)
            
            #line 15 "..\..\Views\OaNew\Editor.cshtml"
, Tuple.Create(Tuple.Create("", 425), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ueditor/ueditor.config.js")
            
            #line default
            #line hidden
, 425), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 521), Tuple.Create("\"", 581)
            
            #line 16 "..\..\Views\OaNew\Editor.cshtml"
, Tuple.Create(Tuple.Create("", 527), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ueditor/ueditor.all.min.js")
            
            #line default
            #line hidden
, 527), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 624), Tuple.Create("\"", 685)
            
            #line 17 "..\..\Views\OaNew\Editor.cshtml"
, Tuple.Create(Tuple.Create("", 630), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/ueditor/lang/zh-cn/zh-cn.js")
            
            #line default
            #line hidden
, 630), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var height = document.documentElement.clientHeight;\r\n    if (height > 100)" +
" {\r\n        height = height - 92;\r\n    }\r\n    else {\r\n        height = 300;\r\n   " +
" }\r\n    var originalContent;\r\n    var editor;\r\n    window.loadEditor = function " +
"(content) {\r\n        originalContent = content;\r\n        editor = UE.getEditor(\"" +
"txtContent\", {\r\n            toolbars: [[\"undo\", \"redo\", \"bold\", \"italic\", \"under" +
"line\", \"|\", \"forecolor\", \"backcolor\", \"fontsize\", \"fontfamily\", \"insertcode\", \"s" +
"uperscript\", \"subscript\", \"spechars\", \"|\", \"pasteplain\", \"formatmatch\", \"autotyp" +
"eset\", \"removeformat\", \"cleardoc\"], [\"directionalityltr\", \"directionalityrtl\", \"" +
"indent\", \"lineheight\", \"|\", \"justifyleft\", \"justifycenter\", \"justifyright\", \"jus" +
"tifyjustify\", \"|\", \"inserttable\", \"deletetable\", \"insertparagraphbeforetable\", \"" +
"insertrow\", \"deleterow\", \"insertcol\", \"deletecol\", \"mergecells\", \"mergeright\", \"" +
"mergedown\", \"splittocells\", \"splittorows\", \"splittocols\", \"|\", \"link\", \"unlink\"," +
" \"anchor\"]], elementPathEnabled: false, enableAutoSave: false, wordCount: false," +
" scaleEnabled: true, autotypeset: { mergeEmptyline: true, removeEmptyline: true," +
" removeEmptyNode: true, tobdc: true }, autoClearEmptyNode: true, initialFrameHei" +
"ght: height\r\n        });\r\n        editor.addListener(\"ready\", function (_editor)" +
" {\r\n            document.body.style.overflowY = \"auto\";\r\n            editor.setC" +
"ontent(content);\r\n        })\r\n    }\r\n\r\n    window.getContent = function () {\r\n  " +
"      if (!editor) {\r\n            return \"\";\r\n        }\r\n        return editor.g" +
"etContent();\r\n    }\r\n\r\n    window.resetEditor = function () {\r\n        if (!edit" +
"or) {\r\n            return;\r\n        }\r\n        editor.setContent(originalContent" +
");\r\n    }\r\n\r\n    window.clearEditor = function () {\r\n        if (!editor) {\r\n   " +
"         return;\r\n        }\r\n        editor.setContent(\"\");\r\n    }\r\n</script>");

        }
    }
}
#pragma warning restore 1591
