#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Scheduler/Edit.cshtml")]
    public partial class _Views_Scheduler_Edit_cshtml : System.Web.Mvc.WebViewPage<DataModel.Models.Scheduler>
    {
        public _Views_Scheduler_Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var buttons=[];\r\n");

            
            #line 4 "..\..\Views\Scheduler\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 4 "..\..\Views\Scheduler\Edit.cshtml"
     if (Model.ID > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n    buttons.push({ icon: \"fa-minus-circle\", text: \"删除\", onClick: function () {\r" +
"\n        deleteData();\r\n    }});\r\n    ");

WriteLiteral("\r\n");

            
            #line 11 "..\..\Views\Scheduler\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral(@"    JQ.form.submitInit({
        formid: ""schedulerform"",
        buttonTypes: [""submit"", ""close""],//默认按钮
        succesCollBack: function (data) {
            if(typeof(data.stateValue)==""string"")
            {
                JQ.dialog.error(data.stateValue);
            }
            else
            {
                data.stateValue.start_date=parseDateTimeValue(data.stateValue.StartTime,false);
                data.stateValue.end_date=parseDateTimeValue(data.stateValue.EndTime,data.stateValue.IsFullDay);
                window.top.document.getElementById(""");

            
            #line 24 "..\..\Views\Scheduler\Edit.cshtml"
                                                Write(Request.QueryString["parentID"]);

            
            #line default
            #line hidden
WriteLiteral("\").contentWindow.afterSchedulerSave(data.stateValue,");

            
            #line 24 "..\..\Views\Scheduler\Edit.cshtml"
                                                                                                                                      Write(Request.QueryString["id"]);

            
            #line default
            #line hidden
WriteLiteral(@");
                JQ.dialog.dialogClose();
            }
        },
        buttons: buttons
    });
    function parseDateTimeValue(str,isFullDay) {
        var matches = /^\/Date\((-?[0-9]*)\)\/$/.exec(str);
        return new Date(isFullDay?(parseInt(matches[1])+24*60*60*1000) :parseInt(matches[1]));
    }
</script>

");

            
            #line 36 "..\..\Views\Scheduler\Edit.cshtml"
 using (Html.BeginForm("Save", "Scheduler", FormMethod.Post, new { @area = "OA", @id = "schedulerform", @name = "schedulerform" }))
{

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"id\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1467), Tuple.Create("\"", 1486)
            
            #line 38 "..\..\Views\Scheduler\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1475), Tuple.Create<System.Object, System.Int32>(Model.ID
            
            #line default
            #line hidden
, 1475), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("    <table");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(">\r\n        <tr>\r\n            <th");

WriteLiteral(" style=\"width:12%\"");

WriteLiteral(">时间</th>\r\n            <td");

WriteLiteral(" style=\"width:88%;height:45px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"float:left;position:relative; margin-left:-10px\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"cbIsFullDay\"");

WriteLiteral(" name=\"cbIsFullDay\"");

WriteLiteral(" style=\"position: absolute;top: 6px;width: 32px;left:0px\"");

WriteLiteral(" /><label");

WriteLiteral(" for=\"cbIsFullDay\"");

WriteLiteral(" style=\"position: absolute;top: 7px;width: 32px;left:29px;-webkit-user-select:non" +
"e\"");

WriteLiteral(">全天</label>\r\n                </div>\r\n                <div");

WriteLiteral(" style=\"float:left;margin-left:50px\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" id=\"txtStartDate\"");

WriteLiteral(" name=\"txtStartDate\"");

WriteLiteral(" style=\"width:100px\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2144), Tuple.Create("\"", 2193)
            
            #line 47 "..\..\Views\Scheduler\Edit.cshtml"
             , Tuple.Create(Tuple.Create("", 2152), Tuple.Create<System.Object, System.Int32>(Model.StartTime.ToString("yyyy-MM-dd")
            
            #line default
            #line hidden
, 2152), false)
);

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" id=\"divStartTime\"");

WriteLiteral(" style=\"float:left;margin-left:5px\"");

WriteLiteral(">\r\n                    <select");

WriteLiteral(" id=\"txtStartMinute\"");

WriteLiteral(" name=\"txtStartMinute\"");

WriteLiteral(">\r\n");

            
            #line 51 "..\..\Views\Scheduler\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Scheduler\Edit.cshtml"
                          
                            for (var i = 0; i < 24; i++)
                            {
                                if (i == Model.StartTime.Hour)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 2628), Tuple.Create("\"", 2655)
            
            #line 56 "..\..\Views\Scheduler\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2636), Tuple.Create<System.Object, System.Int32>(i.ToString("00")
            
            #line default
            #line hidden
, 2636), false)
);

WriteLiteral(" selected=\"selected\"");

WriteLiteral(">");

            
            #line 56 "..\..\Views\Scheduler\Edit.cshtml"
                                                                                        Write(i.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 57 "..\..\Views\Scheduler\Edit.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 2858), Tuple.Create("\"", 2885)
            
            #line 60 "..\..\Views\Scheduler\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2866), Tuple.Create<System.Object, System.Int32>(i.ToString("00")
            
            #line default
            #line hidden
, 2866), false)
);

WriteLiteral(">");

            
            #line 60 "..\..\Views\Scheduler\Edit.cshtml"
                                                                    Write(i.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 61 "..\..\Views\Scheduler\Edit.cshtml"
                                }
                            }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                    </select>\r\n                    <span>:</span>\r\n            " +
"        <select");

WriteLiteral(" id=\"txtStartSecond\"");

WriteLiteral(" name=\"txtStartSecond\"");

WriteLiteral(">\r\n");

            
            #line 67 "..\..\Views\Scheduler\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Scheduler\Edit.cshtml"
                          
                            for (var i = 0; i < 60; i = i + 5)
                            {
                                if (i == Model.StartTime.Minute)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 3416), Tuple.Create("\"", 3443)
            
            #line 72 "..\..\Views\Scheduler\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3424), Tuple.Create<System.Object, System.Int32>(i.ToString("00")
            
            #line default
            #line hidden
, 3424), false)
);

WriteLiteral(" selected=\"selected\"");

WriteLiteral(">");

            
            #line 72 "..\..\Views\Scheduler\Edit.cshtml"
                                                                                        Write(i.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 73 "..\..\Views\Scheduler\Edit.cshtml"
                                }
                                else
                                {


            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 3648), Tuple.Create("\"", 3675)
            
            #line 77 "..\..\Views\Scheduler\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3656), Tuple.Create<System.Object, System.Int32>(i.ToString("00")
            
            #line default
            #line hidden
, 3656), false)
);

WriteLiteral(">");

            
            #line 77 "..\..\Views\Scheduler\Edit.cshtml"
                                                                    Write(i.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 78 "..\..\Views\Scheduler\Edit.cshtml"
                                }
                            }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                    </select>\r\n                </div>\r\n                <div");

WriteLiteral(" style=\"float:left;margin:0px 5px 0px 5px;line-height:26px;cursor:default; -webki" +
"t-user-select:none\"");

WriteLiteral(">\r\n                    –\r\n                </div>\r\n                <div");

WriteLiteral(" style=\"float:left\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" id=\"txtEndDate\"");

WriteLiteral(" name=\"txtEndDate\"");

WriteLiteral(" style=\"width:100px\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4147), Tuple.Create("\"", 4194)
            
            #line 87 "..\..\Views\Scheduler\Edit.cshtml"
         , Tuple.Create(Tuple.Create("", 4155), Tuple.Create<System.Object, System.Int32>(Model.EndTime.ToString("yyyy-MM-dd")
            
            #line default
            #line hidden
, 4155), false)
);

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" id=\"divEndTime\"");

WriteLiteral(" style=\"float:left;margin-left:5px\"");

WriteLiteral(">\r\n                    <select");

WriteLiteral(" id=\"txtEndMinute\"");

WriteLiteral(" name=\"txtEndMinute\"");

WriteLiteral(">\r\n");

            
            #line 91 "..\..\Views\Scheduler\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 91 "..\..\Views\Scheduler\Edit.cshtml"
                          
                            for (var i = 0; i < 24; i++)
                            {
                                if (i == Model.EndTime.Hour)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 4621), Tuple.Create("\"", 4648)
            
            #line 96 "..\..\Views\Scheduler\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4629), Tuple.Create<System.Object, System.Int32>(i.ToString("00")
            
            #line default
            #line hidden
, 4629), false)
);

WriteLiteral(" selected=\"selected\"");

WriteLiteral(">");

            
            #line 96 "..\..\Views\Scheduler\Edit.cshtml"
                                                                                        Write(i.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 97 "..\..\Views\Scheduler\Edit.cshtml"
                                }
                                else
                                {


            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 4853), Tuple.Create("\"", 4880)
            
            #line 101 "..\..\Views\Scheduler\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4861), Tuple.Create<System.Object, System.Int32>(i.ToString("00")
            
            #line default
            #line hidden
, 4861), false)
);

WriteLiteral(">");

            
            #line 101 "..\..\Views\Scheduler\Edit.cshtml"
                                                                    Write(i.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 102 "..\..\Views\Scheduler\Edit.cshtml"
                                }
                            }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                    </select>\r\n                    <span>:</span>\r\n            " +
"        <select");

WriteLiteral(" id=\"txtEndSecond\"");

WriteLiteral(" name=\"txtEndSecond\"");

WriteLiteral(">\r\n");

            
            #line 108 "..\..\Views\Scheduler\Edit.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 108 "..\..\Views\Scheduler\Edit.cshtml"
                          
                            for (var i = 0; i < 60; i = i + 5)
                            {
                                if (i == Model.EndTime.Minute)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 5405), Tuple.Create("\"", 5432)
            
            #line 113 "..\..\Views\Scheduler\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5413), Tuple.Create<System.Object, System.Int32>(i.ToString("00")
            
            #line default
            #line hidden
, 5413), false)
);

WriteLiteral(" selected=\"selected\"");

WriteLiteral(">");

            
            #line 113 "..\..\Views\Scheduler\Edit.cshtml"
                                                                                        Write(i.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 114 "..\..\Views\Scheduler\Edit.cshtml"
                                }
                                else
                                {


            
            #line default
            #line hidden
WriteLiteral("                                    <option");

WriteAttribute("value", Tuple.Create(" value=\"", 5637), Tuple.Create("\"", 5664)
            
            #line 118 "..\..\Views\Scheduler\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5645), Tuple.Create<System.Object, System.Int32>(i.ToString("00")
            
            #line default
            #line hidden
, 5645), false)
);

WriteLiteral(">");

            
            #line 118 "..\..\Views\Scheduler\Edit.cshtml"
                                                                    Write(i.ToString("00"));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 119 "..\..\Views\Scheduler\Edit.cshtml"
                                }
                            }
                        
            
            #line default
            #line hidden
WriteLiteral("\r\n                    </select>\r\n                </div>\r\n            </td>\r\n     " +
"   </tr>\r\n        <tr>\r\n            <th>\r\n                提醒\r\n            </th>\r" +
"\n            <td");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"divRemind1\"");

WriteLiteral(" style=\"float:left;position:relative;margin:5px 0px 0px -2px;\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" id=\"cbIsRemind\"");

WriteLiteral(" name=\"cbIsRemind\"");

WriteLiteral(" style=\"position:absolute\"");

WriteLiteral(" /><label");

WriteLiteral(" for=\"cbIsRemind\"");

WriteLiteral(" style=\"position:absolute;left:20px;width:32px;top:1px;-webkit-user-select:none\"");

WriteLiteral(">提醒</label>\r\n                </div>\r\n                <div");

WriteLiteral(" id=\"divRemind\"");

WriteLiteral(" style=\"float:left; margin:1px 0px 0px 50px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" style=\"float:left;line-height:28px\"");

WriteLiteral(">\r\n                        提前\r\n                    </div>\r\n                    <d" +
"iv");

WriteLiteral(" style=\"float:left;margin-left:5px\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" id=\"txtRemindBefore\"");

WriteLiteral(" name=\"txtRemindBefore\"");

WriteLiteral(" style=\"width:36px\"");

WriteLiteral(" type=\"text\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6703), Tuple.Create("\"", 6757)
            
            #line 139 "..\..\Views\Scheduler\Edit.cshtml"
                                  , Tuple.Create(Tuple.Create("", 6711), Tuple.Create<System.Object, System.Int32>(Model.RemindBefore==-1?5:Model.RemindBefore
            
            #line default
            #line hidden
, 6711), false)
);

WriteLiteral(" />\r\n                    </div>\r\n                    <div");

WriteLiteral(" style=\"float:left;margin-left:5px\"");

WriteLiteral(">\r\n                        <select");

WriteLiteral(" id=\"txtRemindBeforeType\"");

WriteLiteral(" name=\"txtRemindBeforeType\"");

WriteLiteral(">\r\n                            <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">分</option>\r\n                            <option");

WriteLiteral(" value=\"2\"");

WriteLiteral(">时</option>\r\n                            <option");

WriteLiteral(" value=\"3\"");

WriteLiteral(">天</option>\r\n                        </select>\r\n                    </div>\r\n     " +
"           </div>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <" +
"th>\r\n                参与人员\r\n            </th>\r\n            <td");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" name=\"joinEmpIDs\"");

WriteLiteral(" id=\"joinEmpIDs\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7416), Tuple.Create("\"", 7443)
            
            #line 156 "..\..\Views\Scheduler\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 7424), Tuple.Create<System.Object, System.Int32>(Model.JoinEmpIDs
            
            #line default
            #line hidden
, 7424), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" id=\"joinEmpIDsDisplay\"");

WriteLiteral(" name=\"joinEmpIDsDisplay\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7542), Tuple.Create("\"", 7573)
            
            #line 157 "..\..\Views\Scheduler\Edit.cshtml"
                      , Tuple.Create(Tuple.Create("", 7550), Tuple.Create<System.Object, System.Int32>(ViewBag.JoinEmpNames
            
            #line default
            #line hidden
, 7550), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>\r\n          " +
"      内容\r\n            </th>\r\n            <td>\r\n                <textarea");

WriteLiteral(" id=\"Content\"");

WriteLiteral(" name=\"Content\"");

WriteLiteral(" style=\"width:488px;height:160px\"");

WriteLiteral(" placeholder=\"请输入日程内容\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" data-options=\"multiline:true,required:true\"");

WriteLiteral(">");

            
            #line 165 "..\..\Views\Scheduler\Edit.cshtml"
                                                                                                                                                                            Write(Model.Content);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n            </td>\r\n        </tr>\r\n    </table>\r\n");

            
            #line 169 "..\..\Views\Scheduler\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    $(\"#txtStartDate,#txtEndDate\").datebox({\r\n        required: true,\r\n       " +
" validType: [\"dateISO\"]\r\n    });\r\n    $(\"#txtStartMinute,#txtEndMinute\").combobo" +
"x({\r\n        editable: false\r\n    });\r\n    $(\"#txtRemindBeforeType\").val(\"");

            
            #line 178 "..\..\Views\Scheduler\Edit.cshtml"
                               Write(Model.RemindBeforeType);

            
            #line default
            #line hidden
WriteLiteral(@""");
    $(""#txtStartSecond,#txtEndSecond,#txtRemindBeforeType"").combobox({
        editable: false,
        panelHeight: ""auto"",
    });
    $(""#txtRemindBefore"").numberbox({
        min:0,
        precision:0
    }).numberbox(""textbox"").css({ textAlign: ""right"" });
    document.getElementById(""cbIsFullDay"").onchange = function () {
        onIsFullDayChanged();
    }
");

            
            #line 190 "..\..\Views\Scheduler\Edit.cshtml"
    
            
            #line default
            #line hidden
            
            #line 190 "..\..\Views\Scheduler\Edit.cshtml"
     if (Model.IsFullDay)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n    document.getElementById(\"cbIsFullDay\").checked=true;\r\n    ");

WriteLiteral("\r\n");

            
            #line 195 "..\..\Views\Scheduler\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 196 "..\..\Views\Scheduler\Edit.cshtml"
     if (Model.RemindBefore>-1&&Model.ID>0)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("\r\n    document.getElementById(\"cbIsRemind\").checked=true;\r\n    ");

WriteLiteral("\r\n");

            
            #line 201 "..\..\Views\Scheduler\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    function onIsFullDayChanged() {\r\n        if (document.getElementById(\"cbIsFul" +
"lDay\").checked) {\r\n            $(\"#txtRemindBeforeType\").combobox(\"setValue\",\"3\"" +
").combobox(\"disable\");\r\n            document.getElementById(\"divStartTime\").styl" +
"e.display = \"none\";\r\n            document.getElementById(\"divEndTime\").style.dis" +
"play = \"none\";\r\n        }\r\n        else {\r\n            $(\"#txtRemindBeforeType\")" +
".combobox(\"enable\");\r\n            document.getElementById(\"divStartTime\").style." +
"display = \"\";\r\n            document.getElementById(\"divEndTime\").style.display =" +
" \"\";\r\n        }\r\n    }\r\n    document.getElementById(\"cbIsRemind\").onchange = fun" +
"ction () {\r\n        onIsRemindChanged();\r\n    }\r\n\r\n    function onIsRemindChange" +
"d() {\r\n        if (document.getElementById(\"cbIsRemind\").checked) {\r\n           " +
" document.getElementById(\"divRemind1\").style.margin = \"6px 0px 0px -2px\";\r\n     " +
"       document.getElementById(\"divRemind\").style.display = \"\";\r\n        }\r\n    " +
"    else {\r\n            document.getElementById(\"divRemind1\").style.margin = \"-8" +
"px 0px 0px -2px\";\r\n            document.getElementById(\"divRemind\").style.displa" +
"y = \"none\";\r\n        }\r\n    }\r\n\r\n    onIsFullDayChanged();\r\n\r\n    onIsRemindChan" +
"ged();\r\n\r\n    JQ.textbox.selEmp({\r\n        id: \"joinEmpIDsDisplay\",\r\n        set" +
"ID: \"joinEmpIDs\",\r\n        width: 488\r\n    });\r\n\r\n    function deleteData(){\r\n  " +
"      $.messager.confirm(\"提示\",\"确定要删除吗\",function(r){\r\n            if(!r) {\r\n     " +
"           return;\r\n            }\r\n            window.top.document.getElementByI" +
"d(\"");

            
            #line 244 "..\..\Views\Scheduler\Edit.cshtml"
                                            Write(Request.QueryString["parentID"]);

            
            #line default
            #line hidden
WriteLiteral("\").contentWindow.deleteSchedulerData(");

            
            #line 244 "..\..\Views\Scheduler\Edit.cshtml"
                                                                                                                   Write(Request.QueryString["id"]);

            
            #line default
            #line hidden
WriteLiteral(",true);\r\n            JQ.dialog.dialogClose();\r\n        });\r\n    }\r\n</script>");

        }
    }
}
#pragma warning restore 1591
