#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 5 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IsoSJPSJYBMobile/info.cshtml")]
    public partial class _Views_IsoSJPSJYBMobile_info_cshtml : System.Web.Mvc.WebViewPage<DataModel.Models.IsoSJPSJYB>
    {
        public _Views_IsoSJPSJYBMobile_info_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
  
    Layout = "~/Areas/Core/Views/Mobile/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n    <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .aui-btn {\r\n        padding: 10px 15px;\r\n        font-size: 13px;\r\n    }\r\n" +
"\r\n    .aui-btn-row:after {\r\n        border: 0;\r\n    }\r\n    .p-15{\r\n        paddi" +
"ng:15px;\r\n    }\r\n\r\n\r\n    .set-disabled {\r\n        pointer-events: none !importan" +
"t\r\n    }\r\n\r\n        .error {\r\n            color: red;\r\n            font-size: 14" +
"px;\r\n        }\r\n\r\n    .hidden {\r\n        display: none;\r\n    }\r\n\r\n    .aui-input" +
"-hook {\r\n        line-height: 34px;\r\n        text-align: left;\r\n        padding-" +
"left: 20px;\r\n        background: #efefef;\r\n    }\r\n\r\n    .aui-display-hook {\r\n   " +
"     display: none;\r\n        width: 30%;\r\n        float: right;\r\n        font-si" +
"ze: 13px;\r\n        line-height: 33px;\r\n        margin-right: 6px;\r\n        paddi" +
"ng: 3px 6px;\r\n    }\r\n\r\n    .aui-input-width {\r\n        width: 98%;\r\n    }\r\n\r\n   " +
" .hiddenShow {\r\n        height: 0;\r\n    }\r\n\r\n    .aui-input-row label.aui-input-" +
"addon {\r\n        min-width: 90px;\r\n    }\r\n\r\n    .set-selected-icon select {\r\n   " +
"     float: right;\r\n        margin-right: 5px;\r\n        border: 0;\r\n        marg" +
"in-bottom: 0;\r\n    }\r\n\r\n    .set-selected-icon i {\r\n        position: absolute;\r" +
"\n        right: 25px;\r\n        top: 15px;\r\n    }\r\n    .aui-input-row-position {\r" +
"\n        position: relative;\r\n        display: table;\r\n        padding: 6px 0;\r\n" +
"    }\r\n\r\n    .aui-input-row label.aui-input-addon {\r\n        font-size: 14px;\r\n " +
"   }\r\n\r\n    .jq-text-disabled {\r\n        color: #898787;\r\n        width: 98%;\r\n " +
"       pointer-events: none;\r\n        background-color: #efefef !important;\r\n   " +
"     border: 0;\r\n        font-size: 13px;\r\n    }\r\n    .aui-input-check-disable {" +
"\r\n        font-size: 12px !important;\r\n        font-weight: normal !important;\r\n" +
"    }\r\n\r\n    .aui-input-check-disable label {\r\n        line-height: 45px;\r\n     " +
"   margin-right: 15px;\r\n    }\r\n\r\n        .aui-input-check-disable input[type=\"ch" +
"eckbox\"], .aui-input-check-disable input[type=\"radio\"] {\r\n            width: aut" +
"o;\r\n            margin: 0 5px 0 0;\r\n            line-height: 45px;\r\n        }\r\n<" +
"/style>\r\n");

});

WriteLiteral("\r\n");

DefineSection("Body_Content", () => {

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"aui-content\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" id=\"IsoSJPSJYBForm\"");

WriteLiteral(" class=\"aui-form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"p-15\"");

WriteLiteral(">\r\n               表 <label>");

            
            #line 117 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
                   Write(Model.TableNumber);

            
            #line default
            #line hidden
WriteLiteral("</label><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"TableNumber\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2408), Tuple.Create("\"", 2434)
            
            #line 117 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
                 , Tuple.Create(Tuple.Create("", 2416), Tuple.Create<System.Object, System.Int32>(Model.TableNumber
            
            #line default
            #line hidden
, 2416), false)
);

WriteLiteral(" />\r\n                <br />编号 <input");

WriteLiteral(" id=\"Number\"");

WriteLiteral(" name=\"Number\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"aui-input\"");

WriteLiteral(" style=\"display:inline;min-width: 60px;max-width: 60%;border: 1px solid #dbdbdb; " +
"border-radius: 6px;padding: 3px 6px;margin:0 3px;text-align:center;\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" validType=\"length[0,200]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2723), Tuple.Create("\"", 2744)
            
            #line 118 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
                                                                                                                                                                                                                   , Tuple.Create(Tuple.Create("", 2731), Tuple.Create<System.Object, System.Int32>(Model.Number
            
            #line default
            #line hidden
, 2731), false)
);

WriteLiteral(" />\r\n            </div>\r\n            ");

WriteLiteral("\r\n            <div");

WriteLiteral(" class=\"aui-input-row\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"aui-input-addon\"");

WriteLiteral(">&nbsp;&nbsp;项目名称</label>\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ProjId\"");

WriteLiteral(" name=\"ProjId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3411), Tuple.Create("\"", 3432)
            
            #line 128 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
, Tuple.Create(Tuple.Create("", 3419), Tuple.Create<System.Object, System.Int32>(Model.ProjId
            
            #line default
            #line hidden
, 3419), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" name=\"ProjName\"");

WriteLiteral(" id=\"ProjName\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" class=\"aui-input\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3522), Tuple.Create("\"", 3545)
            
            #line 129 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
            , Tuple.Create(Tuple.Create("", 3530), Tuple.Create<System.Object, System.Int32>(Model.ProjName
            
            #line default
            #line hidden
, 3530), false)
);

WriteLiteral(" />\r\n                <div");

WriteLiteral(" class=\"aui-input-block\"");

WriteLiteral(">");

            
            #line 130 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
                                        Write(Model.ProjName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"aui-input-row\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"aui-input-addon\"");

WriteLiteral(">&nbsp;&nbsp;项目阶段</label>\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ProjPhaseName\"");

WriteLiteral(" name=\"ProjPhaseName\"");

WriteLiteral(" class=\"aui-input\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3847), Tuple.Create("\"", 3875)
            
            #line 134 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
                      , Tuple.Create(Tuple.Create("", 3855), Tuple.Create<System.Object, System.Int32>(Model.ProjPhaseName
            
            #line default
            #line hidden
, 3855), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"ProjPhaseId\"");

WriteLiteral(" id=\"ProjPhaseId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3953), Tuple.Create("\"", 3979)
            
            #line 135 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
, Tuple.Create(Tuple.Create("", 3961), Tuple.Create<System.Object, System.Int32>(Model.ProjPhaseId
            
            #line default
            #line hidden
, 3961), false)
);

WriteLiteral(" />\r\n                <div");

WriteLiteral(" class=\"aui-input-block\"");

WriteLiteral(">");

            
            #line 136 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
                                        Write(Model.ProjPhaseName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"aui-input-row aui-input-check-disable\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"aui-input-addon\"");

WriteLiteral(">&nbsp;&nbsp;评审日期</label>\r\n                <input");

WriteLiteral(" type=\"date\"");

WriteLiteral(" id=\"Time\"");

WriteLiteral(" name=\"Time\"");

WriteLiteral(" class=\"aui-input\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4290), Tuple.Create("\"", 4332)
            
            #line 140 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
  , Tuple.Create(Tuple.Create("", 4298), Tuple.Create<System.Object, System.Int32>(Model.Time.ToString("yyyy-MM-dd")
            
            #line default
            #line hidden
, 4298), false)
);

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"aui-input-row\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"aui-input-addon\"");

WriteLiteral(">&nbsp;&nbsp;参加人员</label>\r\n                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"JoinEmpName\"");

WriteLiteral(" name=\"JoinEmpName\"");

WriteLiteral(" class=\"aui-input\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4560), Tuple.Create("\"", 4586)
            
            #line 144 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
                , Tuple.Create(Tuple.Create("", 4568), Tuple.Create<System.Object, System.Int32>(Model.JoinEmpName
            
            #line default
            #line hidden
, 4568), false)
);

WriteLiteral(" />\r\n                ");

WriteLiteral("\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"aui-input-row\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"aui-input-addon\"");

WriteLiteral(">&nbsp;&nbsp;议题</label>\r\n                <textarea");

WriteLiteral(" rows=\"6\"");

WriteLiteral(" name=\"YT\"");

WriteLiteral(" id=\"YT\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"aui-input\"");

WriteLiteral(" data-options=\"multiline:true\"");

WriteLiteral(" validType=\"length[0,500]\"");

WriteLiteral(">");

            
            #line 149 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
                                                                                                                                             Write(Model.YT);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"aui-input-row\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" class=\"aui-input-addon\"");

WriteLiteral(">&nbsp;&nbsp;结论意见：</label>\r\n                <textarea");

WriteLiteral(" rows=\"6\"");

WriteLiteral(" name=\"JLYJ\"");

WriteLiteral(" id=\"JLYJ\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"aui-input\"");

WriteLiteral(" data-options=\"multiline:true\"");

WriteLiteral(" validType=\"length[0,500]\"");

WriteLiteral(">");

            
            #line 153 "..\..\Views\IsoSJPSJYBMobile\info.cshtml"
                                                                                                                                                 Write(Model.JLYJ);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n            </div>\r\n\r\n\r\n\r\n\r\n            ");

WriteLiteral("\r\n        </form>\r\n    </div>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n        $(function () {\r\n            if (window.JinQuMobile == undefined) {\r" +
"\n                //initFormBegin(JSON.stringify({\r\n                //    \"Result" +
"\": true,\r\n                //    \"Message\": null,\r\n                //    \"NodeNam" +
"e\": null,\r\n                //    \"AllowEditControls\": \"ColAttVal1;btnChooseProje" +
"ct;ProjIDName;Number;ProjID;Words;ConstructUnit;SupplyUnit;FormDate;ColAttVal2;M" +
"odifyContent;DesignName;FormNote;DesChangeUpload;ColAttVal3;ProjName;DesignReaso" +
"n;ColAttVal4\",\r\n                //    \"SignControls\": \"DesignName(签名)\",\r\n       " +
"         //    \"SignControls\": null,\r\n                //    //\"AllowEditControls" +
"\":\"\"\r\n\r\n                //}));\r\n                //initFormBegin();\r\n            " +
"}\r\n\r\n        })\r\n        //页面初始化\r\n        function initFormBegin(params) {\r\n\r\n\r\n" +
"            //去除换行\r\n            //alert(window.location.href)\r\n            param" +
"s = params.replace(/[\\r\\n]/g, \"\");\r\n            params = params.replace(/\\s/g, \"" +
"\");\r\n            var paramsObj = JSON.parse(params);\r\n\r\n\r\n            //按钮替换\r\n  " +
"          paramsObj.AllowEditControls = paramsObj.AllowEditControls || \'-\';\r\n\r\n " +
"           //清除评审日期，默认为1900-01-01改为空\r\n            var Time = $(\'#Time\').val();;\r" +
"\n            if ((Time == \'1900-01-01\')) {\r\n                $(\'#Time\').val(\'\');\r" +
"\n            }\r\n    \r\n\r\n             //设置表单不可编辑样式及只读\r\n            $(\'form :input" +
"\').addClass(\'jq-text-disabled\').attr(\"readonly\", \"readonly\");\r\n            DomUt" +
"il.setCtrlsReadonly(paramsObj.AllowEditControls, document.getElementById(\'IsoSJP" +
"SJYBForm\'));\r\n\r\n            //议题，替换换行符\r\n            var YTValue = $(\'#YT\').val()" +
";\r\n            YTValue = YTValue.replace(/[\\r\\n]/g, \"\").replace(/\\s/g, \"\")\r\n    " +
"        $(\'#YT\').val(YTValue);\r\n\r\n\r\n            //JLYJ，替换换行符\r\n            var JL" +
"YJValue = $(\'#JLYJ\').val();\r\n            JLYJValue = JLYJValue.replace(/[\\r\\n]/g" +
", \"\").replace(/\\s/g, \"\")\r\n            $(\'#JLYJ\').val(JLYJValue);\r\n\r\n\r\n          " +
"  if (paramsObj.AllowEditControls == \"{}\") {\r\n\r\n                $(\"#JLYJ, #YT\")." +
"removeClass(\'jq-text-disabled\')\r\n                $(\"#JLYJ,#YT\").css({\r\n         " +
"           overflow: \'auto\',\r\n                })\r\n            }\r\n            els" +
"e {\r\n                $(\'#JLYJ,#YT\').removeClass(\'jq-text-disabled\').attr(\"readon" +
"ly\", \"readonly\")\r\n                $(\"#JLYJ,#YT\").css({\r\n                    over" +
"flow: \'auto\',\r\n                    background: \'#efefef\',\r\n                    c" +
"olor: \'#898787\'\r\n                })\r\n\r\n            }\r\n\r\n\r\n\r\n\r\n            \r\n    " +
"        //告诉移动端页面初始完完毕\r\n            if (window.JinQuMobile) {\r\n                w" +
"indow.JinQuMobile.FormEnd();\r\n            }\r\n        }\r\n\r\n        \r\n        /*--" +
"--------------------------------------------------------------------------------" +
"------------*/\r\n        //表单验证交互\r\n\r\n        function validateFormBegin() {\r\n    " +
"        var formVali = $(\'#IsoSJPSJYBForm\').validate({\r\n                //rules:" +
" {\r\n                //    Number:\'required\',//编号\r\n                //    ProjectN" +
"ame: \'required\',//项目名称\r\n                //    ColAttVal2:\'required\',//变更原因\r\n    " +
"            //    ModifyContent: { //修改内容\r\n                //        required: f" +
"alse,\r\n                //        maxlength: 500\r\n                //    },\r\n     " +
"           //    FormNote: { // 监理单位意见\r\n                //        required: fals" +
"e,\r\n                //        maxlength: 500\r\n                //    }\r\n         " +
"       //},\r\n                //messages: {\r\n                //    Number:\'请输入编号\'" +
",\r\n                //    ProjectName: \'请输入项目名称 \',\r\n                //    ColAttV" +
"al2:\'请输入变更原因\',\r\n                //    ModifyContent: {\r\n                //      " +
"  maxlength: \'内容长度必须介于0-500之间\'\r\n                //    },\r\n                //    " +
"FormNote: {\r\n                //        maxlength: \'内容长度必须介于0-500之间\'\r\n           " +
"     //    }\r\n                //}\r\n            });\r\n            //if ($(\'#ProjNa" +
"me\').val() == \'\') {\r\n            //    $.alert(\'请选择项目！\')\r\n            //    retu" +
"rn false;\r\n            //}\r\n            isValidate = formVali.form();\r\n         " +
"   if (isValidate) {\r\n                var formData = DomUtil.serialize(document." +
"getElementById(\'IsoSJPSJYBForm\'));//json or =&\r\n                console.log(form" +
"Data)\r\n                //告诉移动端页面初始完完毕\r\n                if (window.JinQuMobile) {" +
"\r\n                    window.JinQuMobile.validateFormEnd(JSON.stringify(formData" +
"));\r\n                }\r\n            }\r\n        }\r\n\r\n        /*------------------" +
"----------------------------------------------------------------------------*/\r\n" +
"        //不走验证流程\r\n        function noValidateFormBegin() {\r\n            var form" +
"Data = DomUtil.serialize(document.getElementById(\'IsoSJPSJYBForm\'));//json or =&" +
"\r\n            //告诉移动端页面验证完毕\r\n            if (window.JinQuMobile) {\r\n            " +
"    window.JinQuMobile.validateFormEnd(JSON.stringify(formData));\r\n            }" +
"\r\n        }\r\n\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
