#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36373
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Decision\ContractReport.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Decision/ContractReport.cshtml")]
    public partial class _Views_Decision_ContractReport_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Decision_ContractReport_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Decision\ContractReport.cshtml"
  
    Layout = "~/Areas/Core/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("head", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(function () {
            JQ.datagrid.datagrid({
                JQButtonTypes: [],//需要显示的按钮

                JQPrimaryID: 'Id',//主键的字段
                JQID: 'BussContractOtherInvoiceGrid',//数据表格ID
                JQDialogTitle: '信息',//弹出窗体标题
                JQWidth: '1024',//弹出窗体宽
                JQHeight: '100%',//弹出窗体高
                JQLoadingType: 'datagrid',//数据表格类型 [datagrid,treegrid]
                //JQCustomSearch: [  //自定义搜索的字段
                //{ value: 'DepartmentName', key: '人员部门', type: 'string' }//type支持三种类型string,datetime,combox,默认为string,combox必须提供engname
                //],
                JQExcludeCol: [1],//导出execl排除的列
                //JQMergeCells: { fields: ['DepartmentName', 'EmpName', 'EmpLogin'], Only: 'DepartmentName' },//当字段值相同时会自动的跨行(只对相邻有效)
                //JQEnableFilter: true,//是否启用表格字段检索，只支持当页数据
                //JQFields: ["""", """"],//追加的字段名
                url: '");

            
            #line 24 "..\..\Views\Decision\ContractReport.cshtml"
                 Write(Url.Action("ContractReportList", "Decision", new { @area = "Project" }));

            
            #line default
            #line hidden
WriteLiteral("?ConMonth=\' + $(\'#ConMonth\').textbox(\"getValue\") + \"&ConYear=\" + $(\'#ConYear\').te" +
"xtbox(\"getValue\"),//请求的地址\r\n                checkOnSelect: true,//是否包含check\r\n    " +
"            toolbar: \'#BussContractOtherInvoicePanel\',//工具栏的容器ID\r\n              " +
"  columns: [[\r\n                        { title: \'合同类型\', field: \'BaseName\', width" +
": \"15%\", align: \'left\', sortable: false },\r\n                        { title: \'本月" +
"合同个数\', field: \'ConMonthAll\', width: \"15%\", align: \'left\', sortable: false },\r\n  " +
"                      { title: \'年初至本月累计数\', field: \'ConAll\', width: \"14%\", align:" +
" \'left\', sortable: false },\r\n                        { title: \'本月金额\', field: \'Co" +
"nMonthAllM\', width: \"9%\", align: \'right\', sortable: true },\r\n                   " +
"     { title: \'年初至本月累计金额\', field: \'ConAllM\', width: \"9%\", align: \'right\', sortab" +
"le: true },\r\n                        { title: \'上年同期金额数\', field: \'LConAllM\', widt" +
"h: \"9%\", align: \'right\', sortable: true },\r\n                        { title: \'上年" +
"同期数比例\', field: \'Tqbl\', width: \"9%\", align: \'right\', sortable: true },\r\n         " +
"       ]]\r\n            });\r\n            $(\"#JQSearch\").textbox({\r\n              " +
"  buttonText: \'筛选\',\r\n                buttonIcon: \'fa fa-search\',\r\n              " +
"  height: 25,\r\n                prompt: \'合同编号、合同名称、客户单位\',\r\n                queryO" +
"ptions: { \'Key\': \'FK_BussContractOtherInvoice_RefID.ConrName,FK_BussContractOthe" +
"rInvoice_RefID.ConNumber,FK_BussContractOtherInvoice_RefID.CustName\', \'Contract\'" +
": \'like\' },\r\n                onClickButton: function () {\r\n                    J" +
"Q.datagrid.searchGrid(\r\n                        {\r\n                            d" +
"gID: \'BussContractOtherInvoiceGrid\',\r\n                            loadingType: \'" +
"datagrid\',\r\n                            queryParams: null\r\n                     " +
"   });\r\n                  //  $(\'#BussContractOtherInvoiceGrid\').datagrid(\'reloa" +
"d\');\r\n                }\r\n            });\r\n\r\n            JQ.datagrid.searchGrid(\r" +
"\n                    {\r\n                        dgID: \'BussContractOtherInvoiceG" +
"rid\',\r\n                        loadingType: \'datagrid\',\r\n                       " +
" queryParams: null\r\n                    });\r\n        });\r\n    </script>\r\n");

WriteLiteral("    ");

            
            #line 62 "..\..\Views\Decision\ContractReport.cshtml"
Write(RenderPage("~/Areas/Core/Views/Shared/_Init.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("Body_Content", () => {

WriteLiteral("\r\n    <table");

WriteLiteral(" id=\"BussContractOtherInvoiceGrid\"");

WriteLiteral("></table>\r\n    <div");

WriteLiteral(" id=\"BussContractOtherInvoicePanel\"");

WriteLiteral(" jqpanel=\"searchPanel\"");

WriteLiteral(" style=\"padding: 5px; height: auto;\"");

WriteLiteral(">\r\n        <span");

WriteLiteral(" jqpanel=\"toolbarPanel\"");

WriteLiteral("></span>\r\n              <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" style=\"width: 70px; height: 25px;\"");

WriteLiteral(" id=\"ConYear\"");

WriteLiteral(" value=\"2016\"");

WriteLiteral(" jqwhereoptions=\"{ Key:\'ConYear\', Contract:\'=\',filedType:\'int\' }\"");

WriteLiteral("/>\r\n              <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" style=\"width: 70px; height: 25px;\"");

WriteLiteral(" id=\"ConMonth\"");

WriteLiteral(" value=\"10\"");

WriteLiteral(" jqwhereoptions=\"{ Key:\'ConMonth\', Contract:\'=\',filedType:\'int\' }\"");

WriteLiteral("/>\r\n        <input");

WriteLiteral(" id=\"JQSearch\"");

WriteLiteral(" style=\"width: 250px;\"");

WriteLiteral(" jqwhereoptions=\"{ Key:\'FK_BussContractOtherInvoice_RefID.ConrName,FK_BussContrac" +
"tOtherInvoice_RefID.ConNumber,FK_BussContractOtherInvoice_RefID.CustName\', Contr" +
"act:\'like\'}\"");

WriteLiteral(" />\r\n\r\n        <div");

WriteLiteral(" class=\"moreSearchPanel\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" id=\"startTime\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" style=\"width: 110px\"");

WriteLiteral(" data-options=\"prompt: \'开票日期开始\'\"");

WriteLiteral(" jqwhereoptions=\"{ Key:\'InvoiceDate\', Contract:\'>=\',filedType:\'Date\' }\"");

WriteLiteral(">\r\n            至\r\n            <input");

WriteLiteral(" id=\"endTime\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" style=\"width: 110px\"");

WriteLiteral(" data-options=\"prompt: \'开票日期结束\'\"");

WriteLiteral(" jqwhereoptions=\"{ Key:\'InvoiceDate\', Contract:\'<=\',filedType:\'Date\' }\"");

WriteLiteral(">&nbsp;\r\n        </div>\r\n    </div>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
