#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ArchPaperFolderType\info.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ArchPaperFolderType/info.cshtml")]
    public partial class _Views_ArchPaperFolderType_info_cshtml : System.Web.Mvc.WebViewPage<DataModel.Models.ArchPaperFolderType>
    {
        public _Views_ArchPaperFolderType_info_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    JQ.form.submitInit({\r\n        formid: \'ArchPaperFolderTypeForm\',//formid提交" +
"需要用到\r\n        buttonTypes: [\'submit\', \'close\'],//默认按钮\r\n        succesCollBack: f" +
"unction (data) {//成功回调函数,data为服务器返回值\r\n            var divId = \'");

            
            #line 8 "..\..\Views\ArchPaperFolderType\info.cshtml"
                    Write(Request.Params["divid"]);

            
            #line default
            #line hidden
WriteLiteral(@"';
            debugger;
            if (divId != null) {
                if (typeof (window.top[""_tree_"" + divId]) == ""function"") {
                    window.top[""_tree_"" + divId]();
                }
            }
            JQ.dialog.dialogClose();//关闭窗体放在最后一步执行，以避免找不到事件源
        }
    });

    $(function () {
        var Id = '");

            
            #line 20 "..\..\Views\ArchPaperFolderType\info.cshtml"
             Write(Request.Params["Id"].ToString());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        $(\"#ArchPaperFolderId\").val(Id);\r\n        var ParentId = \'");

            
            #line 22 "..\..\Views\ArchPaperFolderType\info.cshtml"
                   Write(Request.Params["ParentId"].ToString());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        $(\"#ParentId\").val(ParentId);\r\n        var type = \'");

            
            #line 24 "..\..\Views\ArchPaperFolderType\info.cshtml"
               Write(Model.Type);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        $(\"#SType\").val(type);\r\n\r\n        $(\"#SType\").combobox({\r\n           " +
" onSelect: function (data) {\r\n                $(\"#Type\").val(data.value);\r\n     " +
"       }\r\n        });\r\n    });\r\n</script>\r\n");

            
            #line 34 "..\..\Views\ArchPaperFolderType\info.cshtml"
 using (Html.BeginForm("save", "ArchPaperFolderType", FormMethod.Post, new { @area = "Archive", @id = "ArchPaperFolderTypeForm" }))
{
    
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\ArchPaperFolderType\info.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\ArchPaperFolderType\info.cshtml"
                              

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(">\r\n        <tr>\r\n            <th>编号</th>\r\n            <td>\r\n                <inpu" +
"t");

WriteLiteral(" name=\"Number\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" validType=\"length[0,50]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1474), Tuple.Create("\"", 1495)
            
            #line 41 "..\..\Views\ArchPaperFolderType\info.cshtml"
                               , Tuple.Create(Tuple.Create("", 1482), Tuple.Create<System.Object, System.Int32>(Model.Number
            
            #line default
            #line hidden
, 1482), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ArchPaperFolderId\"");

WriteLiteral(" name=\"ArchPaperFolderId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1585), Tuple.Create("\"", 1617)
            
            #line 42 "..\..\Views\ArchPaperFolderType\info.cshtml"
            , Tuple.Create(Tuple.Create("", 1593), Tuple.Create<System.Object, System.Int32>(Model.ArchPaperFolderId
            
            #line default
            #line hidden
, 1593), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ParentId\"");

WriteLiteral(" name=\"ParentId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1689), Tuple.Create("\"", 1712)
            
            #line 43 "..\..\Views\ArchPaperFolderType\info.cshtml"
, Tuple.Create(Tuple.Create("", 1697), Tuple.Create<System.Object, System.Int32>(Model.ParentId
            
            #line default
            #line hidden
, 1697), false)
);

WriteLiteral(" />\r\n            </td>\r\n            \r\n        </tr>\r\n\r\n        <tr>\r\n            " +
"<th>名称</th>\r\n            <td>\r\n                <input");

WriteLiteral(" name=\"Name\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" data-options=\"required:true\"");

WriteLiteral(" validType=\"length[0,50]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1955), Tuple.Create("\"", 1974)
            
            #line 51 "..\..\Views\ArchPaperFolderType\info.cshtml"
                                                          , Tuple.Create(Tuple.Create("", 1963), Tuple.Create<System.Object, System.Int32>(Model.Name
            
            #line default
            #line hidden
, 1963), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <th>类型</th>\r\n " +
"           <td>\r\n                <select");

WriteLiteral(" class=\"easyui-combobox\"");

WriteLiteral(" data-options=\"editable:false\"");

WriteLiteral(" id=\"SType\"");

WriteLiteral(" name=\"SType\"");

WriteLiteral(" >\r\n                    <option");

WriteLiteral(" value=\"0\"");

WriteLiteral(">档案</option>\r\n                    <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(">设计文件</option>\r\n                </select>\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"Type\"");

WriteLiteral(" name=\"Type\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2367), Tuple.Create("\"", 2386)
            
            #line 62 "..\..\Views\ArchPaperFolderType\info.cshtml"
, Tuple.Create(Tuple.Create("", 2375), Tuple.Create<System.Object, System.Int32>(Model.Type
            
            #line default
            #line hidden
, 2375), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n    </table>\r\n");

            
            #line 66 "..\..\Views\ArchPaperFolderType\info.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
