#region <auto-generated>
//此代码由T4模板自动生成 
//生成时间 2017-11-16 17:31:05
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using Common.Data;
using Common.Data.Extenstions;
using DAL;
namespace DBSql.Engineering
{
    public class ProjManage : EFRepository<DataModel.Models.ProjManage>
    {

    }
}
