#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\ArchShareFolderFile\info.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/ArchShareFolderFile/info.cshtml")]
    public partial class _Views_ArchShareFolderFile_info_cshtml : System.Web.Mvc.WebViewPage<DataModel.Models.ArchShareFolderFile>
    {
        public _Views_ArchShareFolderFile_info_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    JQ.form.submitInit({
        formid: 'ArchShareFolderFileForm',//formid提交需要用到
        buttonTypes: ['submit', 'close'],//默认按钮
        succesCollBack: function (data) {//成功回调函数,data为服务器返回值
            JQ.datagrid.autoRefdatagrid();//刷新上一级数据表格，必须在close窗体前调用
            JQ.dialog.dialogClose();//关闭窗体放在最后一步执行，以避免找不到事件源
        }
    });
</script>
");

            
            #line 13 "..\..\Views\ArchShareFolderFile\info.cshtml"
 using (Html.BeginForm("save", "ArchShareFolderFile", FormMethod.Post, new { @area = "Archive", @id = "ArchShareFolderFileForm" }))
{
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\ArchShareFolderFile\info.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\ArchShareFolderFile\info.cshtml"
                              

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(">\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"15%\"");

WriteLiteral(">文件夹名称</th>\r\n            <td>\r\n                <input");

WriteLiteral(" name=\"DirName\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" data-options=\"required:true\"");

WriteLiteral(" validType=\"length[0,100]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 888), Tuple.Create("\"", 912)
            
            #line 20 "..\..\Views\ArchShareFolderFile\info.cshtml"
                                                                                   , Tuple.Create(Tuple.Create("", 896), Tuple.Create<System.Object, System.Int32>(ViewBag.DirName
            
            #line default
            #line hidden
, 896), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" name=\"ArchShareFolderId\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 979), Tuple.Create("\"", 1011)
            
            #line 21 "..\..\Views\ArchShareFolderFile\info.cshtml"
, Tuple.Create(Tuple.Create("", 987), Tuple.Create<System.Object, System.Int32>(Model.ArchShareFolderId
            
            #line default
            #line hidden
, 987), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>文件名称</th>\r\n " +
"           <td>\r\n                <input");

WriteLiteral(" name=\"FileName\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" data-options=\"required:true\"");

WriteLiteral(" validType=\"length[0,100]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1245), Tuple.Create("\"", 1268)
            
            #line 27 "..\..\Views\ArchShareFolderFile\info.cshtml"
                                                               , Tuple.Create(Tuple.Create("", 1253), Tuple.Create<System.Object, System.Int32>(Model.FileName
            
            #line default
            #line hidden
, 1253), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <th>文件描述</th>\r" +
"\n            <td>\r\n                <input");

WriteLiteral(" name=\"FileRemark\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" validType=\"length[0,500]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1477), Tuple.Create("\"", 1502)
            
            #line 34 "..\..\Views\ArchShareFolderFile\info.cshtml"
                                    , Tuple.Create(Tuple.Create("", 1485), Tuple.Create<System.Object, System.Int32>(Model.FileRemark
            
            #line default
            #line hidden
, 1485), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>创建时间</th>\r\n " +
"           <td>\r\n                <input");

WriteLiteral(" name=\"CreationTime\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" validType=\"length[0,23]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1710), Tuple.Create("\"", 1737)
            
            #line 40 "..\..\Views\ArchShareFolderFile\info.cshtml"
                                     , Tuple.Create(Tuple.Create("", 1718), Tuple.Create<System.Object, System.Int32>(Model.CreationTime
            
            #line default
            #line hidden
, 1718), false)
);

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>\r\n          " +
"      上传附件\r\n            </th>\r\n            <td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

            
            #line 48 "..\..\Views\ArchShareFolderFile\info.cshtml"
                
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\ArchShareFolderFile\info.cshtml"
                  
                    var uploader = new DataModel.FileUploader();
                    uploader.RefID = Model.Id;
                    uploader.RefTable = "ArchShareFolderFile";
                    uploader.Name = "UploadFile1";
                    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\ArchShareFolderFile\info.cshtml"
                Write(Html.Partial("~/Areas/Core/Views/UserControl/FileUploader.cshtml", uploader));

            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\ArchShareFolderFile\info.cshtml"
                                                                                                   
                
            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n    </table>\r\n");

            
            #line 58 "..\..\Views\ArchShareFolderFile\info.cshtml"

                    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
