#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\IsoSJTJTGD\info.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IsoSJTJTGD/info.cshtml")]
    public partial class _Views_IsoSJTJTGD_info_cshtml : System.Web.Mvc.WebViewPage<DataModel.Models.IsoSJTJTGD>
    {
        public _Views_IsoSJTJTGD_info_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    JQ.form.submitInit({
        formid: 'IsoSJTJTGDForm',//formid提交需要用到
        buttonTypes: ['close'],//默认按钮
        succesCollBack: function (data) {//成功回调函数,data为服务器返回值
            JQ.datagrid.autoRefdatagrid();//刷新上一级数据表格，必须在close窗体前调用
            JQ.dialog.dialogClose();//关闭窗体放在最后一步执行，以避免找不到事件源
        }, flow: {
            flowNodeID: """);

            
            #line 11 "..\..\Views\IsoSJTJTGD\info.cshtml"
                     Write(Request.QueryString["flowNodeID"]==null? 0 : int.Parse(Request.QueryString["flowNodeID"]));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n            flowMultiSignID: \"");

            
            #line 12 "..\..\Views\IsoSJTJTGD\info.cshtml"
                          Write(Request.QueryString["flowMultiSignID"] ==null? 0 : int.Parse(Request.QueryString["flowMultiSignID"]));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n            url: \"");

            
            #line 13 "..\..\Views\IsoSJTJTGD\info.cshtml"
              Write(Url.Action("FlowWidget", "PubFlow",new { @area="Core"} ));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n            instance: \"_flowInstance\",\r\n            processor: \"ISO,ISO.FlowP" +
"rocessor.IsoSJTJTGDFlow\",\r\n            refID: \"");

            
            #line 16 "..\..\Views\IsoSJTJTGD\info.cshtml"
                Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n            refTable: \"IsoSJTJTGD\",\r\n            dataCreator: \"");

            
            #line 18 "..\..\Views\IsoSJTJTGD\info.cshtml"
                      Write(ViewBag.CurrEmpID);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n        },onBefore: function (resultArr) {\r\n            resultArr.push({ Key:" +
" \"Permission\", Value: ");

            
            #line 20 "..\..\Views\IsoSJTJTGD\info.cshtml"
                                                  Write(ViewBag.Permission);

            
            #line default
            #line hidden
WriteLiteral(" });\r\n        }\r\n    });\r\n\r\n    //选择项目\r\n    function SelectMainProject() {\r\n     " +
"   JQ.dialog.dialog({\r\n            title: \"选择项目\",\r\n            url: \'");

            
            #line 28 "..\..\Views\IsoSJTJTGD\info.cshtml"
             Write(Url.Action("ChooseProjectList1", "EmpManage", new { @area = "Engineering" }));

            
            #line default
            #line hidden
WriteLiteral(@"?CompanyType=&TaskGroupId=' + $(""#ProjId"").val(),
            width: '1024',
            height: '100%',
            JQID: 'ProjTable',
            JQLoadingType: 'datagrid',
            iconCls: 'fa fa-list',
        });
    }

    //确定选择回调
    var _ProjCallBack = function (row) {
        var data = row[0];
        $(""#ProjId"").val(data.Id);
        $(""#ProjName"").textbox(""setValue"", data.ProjName);
        $(""#ProjNumber"").textbox(""setValue"", data.ProjNumber);
        $(""#ProjPhaseName"").val(data.ProjPhaseName);
        $(""#ProjPhaseId"").val(data.ProjPhaseId);
    }
</script>
");

            
            #line 47 "..\..\Views\IsoSJTJTGD\info.cshtml"
 using (Html.BeginForm("save", "IsoSJTJTGD", FormMethod.Post, new { @area = "Iso", @id = "IsoSJTJTGDForm" }))
{
    
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\IsoSJTJTGD\info.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\IsoSJTJTGD\info.cshtml"
                              

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"width:100%;text-align:center;font-size:20px;font-weight:bold;margin-top:1" +
"0px;\"");

WriteLiteral(">\r\n            <a>设计条件提供单</a>\r\n        </div>\r\n        <div");

WriteLiteral(" style=\"float:left;margin-left:20px;margin-top:10px;\"");

WriteLiteral(">\r\n            表<label>");

            
            #line 55 "..\..\Views\IsoSJTJTGD\info.cshtml"
               Write(Model.TableNumber);

            
            #line default
            #line hidden
WriteLiteral("</label><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"TableNumber\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2413), Tuple.Create("\"", 2439)
            
            #line 55 "..\..\Views\IsoSJTJTGD\info.cshtml"
             , Tuple.Create(Tuple.Create("", 2421), Tuple.Create<System.Object, System.Int32>(Model.TableNumber
            
            #line default
            #line hidden
, 2421), false)
);

WriteLiteral(" />\r\n        </div>\r\n        <div");

WriteLiteral(" style=\"float:right;margin-right:20px;margin-top:10px;margin-bottom:10px;\"");

WriteLiteral(">\r\n            编号<input");

WriteLiteral(" id=\"Number\"");

WriteLiteral(" name=\"Number\"");

WriteLiteral(" style=\"width:140px;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" validtype=\"length[0,50]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2665), Tuple.Create("\"", 2686)
            
            #line 58 "..\..\Views\IsoSJTJTGD\info.cshtml"
                                           , Tuple.Create(Tuple.Create("", 2673), Tuple.Create<System.Object, System.Int32>(Model.Number
            
            #line default
            #line hidden
, 2673), false)
);

WriteLiteral(" />\r\n        </div>\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">项目编号</th>\r\n            <td");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"ProjNumber\"");

WriteLiteral(" name=\"ProjNumber\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" data-options=\"required:true,editable:false\"");

WriteLiteral(" validType=\"length[0,50]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2958), Tuple.Create("\"", 2983)
            
            #line 63 "..\..\Views\IsoSJTJTGD\info.cshtml"
                                                                                               , Tuple.Create(Tuple.Create("", 2966), Tuple.Create<System.Object, System.Int32>(Model.ProjNumber
            
            #line default
            #line hidden
, 2966), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"ProjPhaseId\"");

WriteLiteral(" id=\"ProjPhaseId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3061), Tuple.Create("\"", 3087)
            
            #line 64 "..\..\Views\IsoSJTJTGD\info.cshtml"
, Tuple.Create(Tuple.Create("", 3069), Tuple.Create<System.Object, System.Int32>(Model.ProjPhaseId
            
            #line default
            #line hidden
, 3069), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"ProjPhaseName\"");

WriteLiteral(" id=\"ProjPhaseName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3169), Tuple.Create("\"", 3197)
            
            #line 65 "..\..\Views\IsoSJTJTGD\info.cshtml"
    , Tuple.Create(Tuple.Create("", 3177), Tuple.Create<System.Object, System.Int32>(Model.ProjPhaseName
            
            #line default
            #line hidden
, 3177), false)
);

WriteLiteral(" />\r\n                <a");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" name=\"btnChoice\"");

WriteLiteral(" id=\"btnChoice\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'fa fa-minus-circle\'\"");

WriteLiteral(" onclick=\"SelectMainProject()\"");

WriteLiteral(">选择项目</a>\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">项目名称</th>\r\n            <td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ProjId\"");

WriteLiteral(" name=\"ProjId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3525), Tuple.Create("\"", 3546)
            
            #line 70 "..\..\Views\IsoSJTJTGD\info.cshtml"
, Tuple.Create(Tuple.Create("", 3533), Tuple.Create<System.Object, System.Int32>(Model.ProjId
            
            #line default
            #line hidden
, 3533), false)
);

WriteLiteral(" />\r\n                <input");

WriteLiteral(" id=\"ProjName\"");

WriteLiteral(" name=\"ProjName\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" data-options=\"required:true,editable:false\"");

WriteLiteral(" validType=\"length[0,50]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3715), Tuple.Create("\"", 3738)
            
            #line 71 "..\..\Views\IsoSJTJTGD\info.cshtml"
                                                                                           , Tuple.Create(Tuple.Create("", 3723), Tuple.Create<System.Object, System.Int32>(Model.ProjName
            
            #line default
            #line hidden
, 3723), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">提供专业</th>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" name=\"TGSpecName\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" validType=\"length[0,50]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3949), Tuple.Create("\"", 3974)
            
            #line 77 "..\..\Views\IsoSJTJTGD\info.cshtml"
                , Tuple.Create(Tuple.Create("", 3957), Tuple.Create<System.Object, System.Int32>(Model.TGSpecName
            
            #line default
            #line hidden
, 3957), false)
);

WriteLiteral(" />\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">专业负责人</th>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" name=\"TGSpecHeader\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" validType=\"length[0,10]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4159), Tuple.Create("\"", 4186)
            
            #line 81 "..\..\Views\IsoSJTJTGD\info.cshtml"
                  , Tuple.Create(Tuple.Create("", 4167), Tuple.Create<System.Object, System.Int32>(Model.TGSpecHeader
            
            #line default
            #line hidden
, 4167), false)
);

WriteLiteral(" />\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">提供日期</th>\r\n            <td");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" name=\"TGTime\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" validType=\"length[0,23]\"");

WriteLiteral(" data-options=\"editable:false\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4394), Tuple.Create("\"", 4415)
            
            #line 85 "..\..\Views\IsoSJTJTGD\info.cshtml"
                                          , Tuple.Create(Tuple.Create("", 4402), Tuple.Create<System.Object, System.Int32>(Model.TGTime
            
            #line default
            #line hidden
, 4402), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">接受专业</th>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" name=\"JSSpecName\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" validType=\"length[0,50]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4628), Tuple.Create("\"", 4653)
            
            #line 92 "..\..\Views\IsoSJTJTGD\info.cshtml"
                , Tuple.Create(Tuple.Create("", 4636), Tuple.Create<System.Object, System.Int32>(Model.JSSpecName
            
            #line default
            #line hidden
, 4636), false)
);

WriteLiteral(" />\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">专业负责人</th>\r\n            <td");

WriteLiteral(" width=\"25%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" name=\"JSSpecHeader\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" validType=\"length[0,50]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4838), Tuple.Create("\"", 4865)
            
            #line 96 "..\..\Views\IsoSJTJTGD\info.cshtml"
                  , Tuple.Create(Tuple.Create("", 4846), Tuple.Create<System.Object, System.Int32>(Model.JSSpecHeader
            
            #line default
            #line hidden
, 4846), false)
);

WriteLiteral(" />\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">接受日期</th>\r\n            <td");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" name=\"JSTime\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" validType=\"length[0,23]\"");

WriteLiteral(" data-options=\"editable:false\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5073), Tuple.Create("\"", 5094)
            
            #line 100 "..\..\Views\IsoSJTJTGD\info.cshtml"
                                          , Tuple.Create(Tuple.Create("", 5081), Tuple.Create<System.Object, System.Int32>(Model.JSTime
            
            #line default
            #line hidden
, 5081), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n\r\n        <tr>\r\n            <th");

WriteLiteral(" colspan=\"6\"");

WriteLiteral(" style=\"text-align:left;\"");

WriteLiteral(">\r\n                设计条件(主要控制数据及文字说明、所附文件及简图的名称)：<br />\r\n                <input");

WriteLiteral(" name=\"SJNote\"");

WriteLiteral(" style=\"width:98%;height:150px;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" data-options=\"multiline:true\"");

WriteLiteral(" validType=\"length[0,500]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5405), Tuple.Create("\"", 5426)
            
            #line 107 "..\..\Views\IsoSJTJTGD\info.cshtml"
                                                                           , Tuple.Create(Tuple.Create("", 5413), Tuple.Create<System.Object, System.Int32>(Model.SJNote
            
            #line default
            #line hidden
, 5413), false)
);

WriteLiteral(" />\r\n            </th>\r\n        </tr>\r\n        <tr");

WriteLiteral(" id=\"SignTd\"");

WriteLiteral(">\r\n            <th></th>\r\n            <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral("></td>\r\n        </tr>\r\n        <tr>\r\n            <th>\r\n                上传附件\r\n    " +
"        </th>\r\n            <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">\r\n");

            
            #line 119 "..\..\Views\IsoSJTJTGD\info.cshtml"
                
            
            #line default
            #line hidden
            
            #line 119 "..\..\Views\IsoSJTJTGD\info.cshtml"
                  
                    var uploader = new DataModel.FileUploader();
                    uploader.RefID = Model.Id;
                    uploader.RefTable = "IsoSJTJTGD";
                    uploader.Name = "UploadFile1";
                    
            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\IsoSJTJTGD\info.cshtml"
                Write(Html.Partial("~/Areas/Core/Views/UserControl/FileUploader.cshtml", uploader));

            
            #line default
            #line hidden
            
            #line 124 "..\..\Views\IsoSJTJTGD\info.cshtml"
                                                                                                   
                
            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n    </table>\r\n");

            
            #line 129 "..\..\Views\IsoSJTJTGD\info.cshtml"
                    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
