#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\IsoFile\info.cshtml"
    using JQ.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/IsoFile/info.cshtml")]
    public partial class _Views_IsoFile_info_cshtml : System.Web.Mvc.WebViewPage<DataModel.Models.IsoFile>
    {
        public _Views_IsoFile_info_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    JQ.form.submitInit({\r\n        formid: \'IsoFileForm\',//formid提交需要用到\r\n      " +
"  buttonTypes: ");

            
            #line 6 "..\..\Views\IsoFile\info.cshtml"
                Write(Html.Raw(ViewBag.editPermission));

            
            #line default
            #line hidden
WriteLiteral(",//默认按钮\r\n        succesCollBack: function (data) {//成功回调函数,data为服务器返回值\r\n         " +
"   JQ.datagrid.autoRefdatagrid();//刷新上一级数据表格，必须在close窗体前调用\r\n            JQ.dialo" +
"g.dialogClose();//关闭窗体放在最后一步执行，以避免找不到事件源\r\n        }\r\n    });\r\n</script>\r\n");

            
            #line 13 "..\..\Views\IsoFile\info.cshtml"
 using (Html.BeginForm("save", "IsoFile", FormMethod.Post, new { @area = "Iso", @id = "IsoFileForm" }))
{
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\IsoFile\info.cshtml"
Write(Html.HiddenFor(m => m.FileID));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\IsoFile\info.cshtml"
                                  

            
            #line default
            #line hidden
WriteLiteral("    <table");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(">\r\n        ");

WriteLiteral("\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">文件编号</th>\r\n            <td");

WriteLiteral(" width=\"40%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"FileNumber\"");

WriteLiteral(" name=\"FileNumber\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1008), Tuple.Create("\"", 1033)
            
            #line 26 "..\..\Views\IsoFile\info.cshtml"
                          , Tuple.Create(Tuple.Create("", 1016), Tuple.Create<System.Object, System.Int32>(Model.FileNumber
            
            #line default
            #line hidden
, 1016), false)
);

WriteLiteral("  data-options=\"required:true\"");

WriteLiteral("/>\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">文件名称</th>\r\n            <td");

WriteLiteral(" width=\"40%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"FileName\"");

WriteLiteral(" name=\"FileName\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1250), Tuple.Create("\"", 1273)
            
            #line 30 "..\..\Views\IsoFile\info.cshtml"
                      , Tuple.Create(Tuple.Create("", 1258), Tuple.Create<System.Object, System.Int32>(Model.FileName
            
            #line default
            #line hidden
, 1258), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">当前版本号</th>\r\n            <td");

WriteLiteral(" width=\"40%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"FileVersion\"");

WriteLiteral(" name=\"FileVersion\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1497), Tuple.Create("\"", 1523)
            
            #line 36 "..\..\Views\IsoFile\info.cshtml"
                            , Tuple.Create(Tuple.Create("", 1505), Tuple.Create<System.Object, System.Int32>(Model.FileVersion
            
            #line default
            #line hidden
, 1505), false)
);

WriteLiteral(" />\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">状态</th>\r\n            <td");

WriteLiteral(" width=\"40%\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 40 "..\..\Views\IsoFile\info.cshtml"
           Write(Html.DropDownListFor(f => f.FileIsModules, ViewData["statusdata"] as IEnumerable<SelectListItem>, new { @class = "easyui-combobox", editable = "false" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">类型</th>\r\n            <td");

WriteLiteral(" width=\"40%\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 46 "..\..\Views\IsoFile\info.cshtml"
           Write(Html.DropDownListFor(f => f.FileType, ViewData["typedata"] as IEnumerable<SelectListItem>, new { @class = "easyui-combobox", editable = "false" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">发布人</th>\r\n            <td");

WriteLiteral(" width=\"40%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" id=\"FileTypeName\"");

WriteLiteral(" name=\"FileTypeName\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" readonly=\"readonly\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2276), Tuple.Create("\"", 2303)
            
            #line 50 "..\..\Views\IsoFile\info.cshtml"
                                                  , Tuple.Create(Tuple.Create("", 2284), Tuple.Create<System.Object, System.Int32>(Model.FileTypeName
            
            #line default
            #line hidden
, 2284), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">实施日期</th>\r\n            <td");

WriteLiteral(" width=\"40%\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" name=\"FileDate\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" validtype=\"length[0,16]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2531), Tuple.Create("\"", 2554)
            
            #line 56 "..\..\Views\IsoFile\info.cshtml"
                                 , Tuple.Create(Tuple.Create("", 2539), Tuple.Create<System.Object, System.Int32>(Model.FileDate
            
            #line default
            #line hidden
, 2539), false)
);

WriteLiteral(" />\r\n            </td>\r\n            <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">作废日期</th>\r\n            <td");

WriteLiteral(" width=\"40%\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" name=\"FileZFDate\"");

WriteLiteral(" style=\"width:98%;\"");

WriteLiteral(" class=\"easyui-datebox\"");

WriteLiteral(" validtype=\"length[0,16]\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2797), Tuple.Create("\"", 2822)
            
            #line 60 "..\..\Views\IsoFile\info.cshtml"
                                   , Tuple.Create(Tuple.Create("", 2805), Tuple.Create<System.Object, System.Int32>(Model.FileZFDate
            
            #line default
            #line hidden
, 2805), false)
);

WriteLiteral(" />\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">\r\n                文件说明\r\n            </th>\r\n            <td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" rows=\"3\"");

WriteLiteral(" cols=\"80\"");

WriteLiteral(" name=\"FileNote\"");

WriteLiteral(" id=\"FileNote\"");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" data-options=\"multiline:true\"");

WriteLiteral(" style=\"width:99%;height:80px;\"");

WriteLiteral(">");

            
            #line 68 "..\..\Views\IsoFile\info.cshtml"
                                                                                                                                                          Write(Model.FileNote);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n            </td>\r\n        </tr>\r\n        <tr>\r\n            <th>\r\n  " +
"              上传附件\r\n            </th>\r\n            <td");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">\r\n");

            
            #line 76 "..\..\Views\IsoFile\info.cshtml"
                
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\IsoFile\info.cshtml"
                  
                    var uploader = new DataModel.FileUploader();
                    uploader.RefID = Model.FileID;
                    uploader.RefTable = "IsoFile";
                    uploader.Name = "uploadfile1";
                    
            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\IsoFile\info.cshtml"
                Write(Html.Partial("~/Areas/Core/Views/UserControl/FileUploader.cshtml", uploader));

            
            #line default
            #line hidden
            
            #line 81 "..\..\Views\IsoFile\info.cshtml"
                                                                                                   
                
            
            #line default
            #line hidden
WriteLiteral("\r\n            </td>\r\n        </tr>\r\n    </table>\r\n");

            
            #line 86 "..\..\Views\IsoFile\info.cshtml"

                    }

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
